import {useEffect,useState} from 'react';
import {Check} from 'lucide-react';
import {Asset,AssetKind,kindLabels,money,priceLabel,propertyMoney} from './data';
import {typeSpec,formType} from './product-types';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export function AssetForm({edit,type,setType,onSubmit,busy,canSave,error}:{edit:Asset|null;type:string;setType:(v:string)=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean;canSave:boolean;error:string}){
 const {kind,currency}=typeSpec(type),[price,setPrice]=useState(edit?.price.toString()??''),[area,setArea]=useState(edit?.area?.toString()??''),[base,setBase]=useState(String(edit?.quoteBase??(kind==='bond'?10000:kind==='fund'?1000:1)));
 useEffect(()=>{if(!edit)setBase(String(kind==='bond'?(currency==='USD'?100:10000):kind==='fund'?(currency==='USD'?1:1000):1))},[kind,currency,edit]);
 const p=Number(price),a=Number(area),preview={kind,currency,price:p,quoteBase:Number(base)} as Asset;
 return <form onSubmit={onSubmit}><fieldset disabled={busy} className="management-body">
 <div className="form-columns"><div className="form-field"><label htmlFor="asset-kind">상품 종류</label><Select value={kind} onValueChange={v=>setType(formType({kind:v as AssetKind,currency:v==='property'?'KRW':currency}))} disabled={!!edit}><SelectTrigger id="asset-kind"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(kindLabels).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></div><div className="form-field"><label htmlFor="asset-currency">통화</label><Select value={currency} onValueChange={v=>setType(formType({kind,currency:v as 'KRW'|'USD'}))} disabled={!!edit||kind==='property'}><SelectTrigger id="asset-currency"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="KRW">원화 KRW</SelectItem><SelectItem value="USD">달러 USD</SelectItem></SelectContent></Select></div></div>
 <div className="form-field"><label htmlFor="asset-name">{kind==='property'?'매물 이름':'상품 이름'}</label><input id="asset-name" name="name" required maxLength={60} defaultValue={edit?.name}/></div>
 <div className="form-field"><label htmlFor="asset-sub">{kind==='property'?'지역 · 주소':kind==='bond'?'발행기관 · 구분':kind==='fund'?'운용사 · 클래스':'종목코드 · 시장'}</label><input id="asset-sub" name="sub" required maxLength={120} defaultValue={edit?.sub}/></div>
 {['bond','fund'].includes(kind)&&<div className="form-field"><label htmlFor="asset-base">{kind==='bond'?'단가 기준 액면금액 ('+(currency==='USD'?'달러':'원')+')':'기준가의 좌수 (좌)'}</label><input id="asset-base" name="quoteBase" type="number" min="1" max="1000000000" step="1" required value={base} onChange={e=>setBase(e.target.value)}/></div>}
 <div className="form-columns"><div className="form-field"><label htmlFor="asset-price">{priceLabel(preview)} ({currency==='USD'?'달러':'원'})</label><input id="asset-price" name="price" type="number" min="0.01" max="100000000000000" step="0.01" required value={price} onChange={e=>setPrice(e.target.value)}/><p className="input-help" aria-live="polite">{p>0&&Number.isFinite(p)?kind==='property'?propertyMoney(p):money(preview):''}</p></div>{kind==='property'&&<div className="form-field"><label htmlFor="asset-area">전용 면적 (㎡)</label><input id="asset-area" name="area" type="number" min="0.01" max="100000" step="0.01" required value={area} onChange={e=>setArea(e.target.value)}/><p className="input-help">{a>0?'약 '+(a/3.3058).toFixed(1)+'평':''}</p></div>}</div>
 {kind==='etf'&&<div className="form-field"><label htmlFor="asset-benchmark">기초지수 · 선택</label><input id="asset-benchmark" name="benchmark" maxLength={80} defaultValue={edit?.benchmark}/></div>}
 {kind==='fund'&&<div className="form-field"><label htmlFor="asset-fund-type">유형 · 선택</label><input id="asset-fund-type" name="fundType" maxLength={40} defaultValue={edit?.fundType} placeholder="주식형 · 채권형 · 혼합형"/></div>}
 {['etf','fund'].includes(kind)&&<div className="form-field"><label htmlFor="asset-expense">총보수 (연 %) · 선택</label><input id="asset-expense" name="expenseRatio" type="number" min="0" max="100" step="any" defaultValue={edit?.expenseRatio}/></div>}
 {kind==='bond'&&<div className="form-columns"><div className="form-field"><label htmlFor="asset-coupon">표면금리 (연 %) · 선택</label><input id="asset-coupon" name="couponRate" type="number" min="0" max="100" step="any" defaultValue={edit?.couponRate}/></div><div className="form-field"><label htmlFor="asset-maturity">만기 · 선택</label><input id="asset-maturity" name="maturity" type="date" defaultValue={edit?.maturity}/></div><div className="form-field"><label htmlFor="asset-rating">신용등급 · 선택</label><input id="asset-rating" name="creditRating" maxLength={20} defaultValue={edit?.creditRating}/></div></div>}
 {kind==='bond'&&<p className="input-help">단가: 경과이자 제외 · 표면금리는 만기수익률과 다릅니다.</p>}
 <div className="form-field"><label htmlFor="asset-url">원본 링크 · 선택</label><input id="asset-url" name="url" type="url" maxLength={1000} defaultValue={edit?.url} placeholder="https://"/></div>
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="primary full-width" type="submit" disabled={busy||!canSave}>{busy?'저장 중…':edit?'수정 내용 저장':'관심 목록에 추가'}<Check size={17}/></button></fieldset></form>;
}
