'use client';
import {useEffect,useState} from 'react';
import {Landmark,ChartNoAxesCombined,Bell,Wallet,Apple,ArrowDownRight,ArrowRight,ArrowUpRight,BarChart3,BookOpen,Building2,Check,ChevronDown,ChevronRight,CircleHelp,ExternalLink,Heart,Home,Layers3,ListChecks,LockKeyhole,PencilLine,Plus,RefreshCw,Ruler,Search,Settings2,Star,TrendingUp,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from '@/components/ui/collapsible';
import {Switch} from '@/components/ui/switch';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Asset,money,priceLabel,quantityUnit,hasPriceChart} from './data';
import {useAssets} from './use-assets';
import {FinanceProductList} from './finance-product-list';
import {FinanceComparison} from './finance-comparison';
import {FinanceFilters} from './finance-filters';
import {AssetForm} from './asset-form';
import {PriceChart} from './price-chart';
import {ManagementDialog} from './management-dialog';
import {statusLabels,targetMet,position} from './management';
import {emptyFilters,sortOptions} from './asset-filters';
import {plainChange,areaLabel,assetGroup,compareSummary,productFacts} from './asset-content';
const colors=['#335d5b','#b07b43','#527baa','#91658b'];
const stamp=(value:string)=>new Date(value).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const menu=[{id:'overview',label:'전체',icon:Home},{id:'stock',label:'주식',icon:TrendingUp},{id:'etf',label:'ETF',icon:Layers3},{id:'bond',label:'채권',icon:Landmark},{id:'fund',label:'펀드',icon:ChartNoAxesCombined},{id:'property',label:'부동산',icon:Building2},{id:'saved',label:'관심 목록',icon:Star},{id:'compare',label:'비교',icon:Layers3},{id:'alerts',label:'조건 알림',icon:Bell},{id:'holdings',label:'보유 상품',icon:Wallet}];
function Picker({value,onChange,label,options}:{value:string;onChange:(s:string)=>void;label:string;options:[string,string][]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select>}
function Chart({items}:{items:Asset[]}){
 const [period,setPeriod]=useState('전체');
 const plot=items.filter(a=>a.series.length>1).map(a=>{const s=period==='최근 구간'?a.series.slice(-5):a.series;return {...a,values:s.map(v=>v/s[0]*100)}});
 const all=plot.flatMap(p=>p.values);const low=Math.floor((Math.min(98,...all)-2)/5)*5,high=Math.ceil((Math.max(108,...all)+2)/5)*5;
 const coords=(vs:number[])=>vs.map((v,i)=>`${i*800/(vs.length-1)},${195-(v-low)/(high-low)*190}`).join(' ');
 return <section className="panel chart-panel"><div className="panel-heading"><div><h2>가격 변동 비교</h2><p>첫 시점 = 100 · 예시</p></div><div className="periods">{['전체','최근 구간'].map(p=><button key={p} onClick={()=>setPeriod(p)} aria-pressed={p===period} className={p===period?'active':''}>{p}</button>)}</div></div><div className="chart-legends">{plot.map((a,i)=><span key={a.id}><i style={{background:colors[i%4]}}/>{a.name}</span>)}<span className="subtle">{period} · 예시</span></div>{plot.length?<div className="main-chart"><div className="y-axis">{[high,Math.round((high+low)/2),low].map((n,i)=><span key={i}>{n}</span>)}</div><div className="chart-grid"><svg viewBox="0 0 800 200" preserveAspectRatio="none" role="img" aria-label={`${plot.map(a=>a.name).join(', ')} ${period} 예시 가격 지수`}><defs><linearGradient id="chart-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0b9090" stopOpacity=".16"/><stop offset="100%" stopColor="#0b9090" stopOpacity="0"/></linearGradient></defs><polygon points={`0,200 ${coords(plot[0].values)} 800,200`} fill="url(#chart-area)"/>{plot.map((a,i)=><polyline key={a.id} points={coords(a.values)} fill="none" stroke={colors[i%4]} strokeWidth="2.5" vectorEffect="non-scaling-stroke" strokeLinejoin="round"/>)}</svg><div className="x-axis"><span>구간 시작</span><span></span><span>구간 마지막</span></div></div></div>:<div className="empty-state"><BarChart3/><h3>가격 이력이 없습니다</h3><p>직접 입력한 자산은 현재 입력 가격으로 비교하세요.</p></div>}<div className="chart-foot"><CircleHelp size={14}/><span>분배금·이자·환율 미반영 · 가격 이력 있는 상품</span></div></section>
}

export default function Dashboard(){
 const assetStore=useAssets();
 const {templateMode,managed,setManaged,getManagement,targetAssets,holdings,openManagement,saveManagement,filters,setFilters,invalidCount,noteDirty,requestDetailClose,closePrompt,setClosePrompt,startEdit,draftRevision,view,navigate,query,setQuery,market,setMarket,sort,setSort,records,ready,signedIn,busy,refreshing,error,checked,automatic,setAutomatic,selected,setSelected,detail,setDetail,note,setNote,settings,setSettings,addOpen,setAddOpen,edit,setEdit,addType,setAddType,formError,setFormError,refresh,assets,watched,savedNote,save,toggleWatch,choose,openDetail,showing,comparisons,addAsset}=assetStore;
 const [embedded,setEmbedded]=useState(false),[chartId,setChartId]=useState('005930'),[compareFields,setCompareFields]=useState(['space','unit','metrics']);
 useEffect(()=>{setEmbedded(new URLSearchParams(location.search).has('embedded'));try{const saved=JSON.parse(localStorage.getItem('aider-compare-fields')??'null');if(Array.isArray(saved)&&saved.every(v=>typeof v==='string'))setCompareFields(saved.slice(0,8));}catch{}},[]);
 const toggleField=(id:string)=>{setCompareFields(old=>{const next=old.includes(id)?old.filter(v=>v!==id):[...old,id];try{localStorage.setItem('aider-compare-fields',JSON.stringify(next))}catch{}return next})};
 const chartAssets=showing.filter(hasPriceChart);const chartAsset=chartAssets.find(a=>a.id===chartId)??chartAssets[0];
 const savedAssets=assets.filter(a=>watched(a.id));
 const filterCount=Number(filters.region!=='all')+Number(filters.budget!=='all')+Number(filters.area!=='all')+Number(filters.notesOnly)+Number(filters.status!=='all')+Number(filters.tag!=='all');
 const startAdd=()=>{if(templateMode)return;setEdit(null);setAddType(['etf','bond','fund','property'].includes(view)?view:'kr');setFormError('');setAddOpen(true)};
 return <div className="asset-app personal-finance-preview">
 <Toaster position="bottom-right"/>
 <main className="personal-finance-page">
 <header className="personal-finance-heading"><div><nav className="personal-finance-path" aria-label="페이지 위치"><span>PERSONAL</span><ChevronRight size={12}/><span aria-current="page">재테크</span></nav><h1>재테크 {templateMode&&<span className="finance-template-badge">미리보기</span>}</h1></div><div className="personal-finance-actions"><span className="finance-sample-state">예시 · 시세 미연결</span><button className="outline finance-settings-button" aria-label="데이터 설정" onClick={()=>setSettings(true)}><Settings2 size={16}/></button><button className="primary" disabled={busy||templateMode} onClick={startAdd} title={templateMode?'미리보기에서는 등록하지 않습니다.':undefined}><Plus size={15}/> 상품 등록</button></div></header>
 <section className="personal-finance-surface" aria-label="재테크 관리"><div className="finance-navigation"><Tabs value={view} onValueChange={navigate} className="finance-section-tabs"><TabsList className="finance-section-tablist" aria-label="재테크 보기">{menu.slice(0,6).map(({id,label})=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}<span className="finance-nav-divider" aria-hidden="true"/>{menu.slice(6).map(({id,label})=><TabsTrigger key={id} value={id}>{label}<span className="finance-nav-count">{id==='saved'?savedAssets.length:id==='alerts'?targetAssets.length:id==='holdings'?holdings.length:selected.length}</span></TabsTrigger>)}</TabsList></Tabs><div className="finance-view-picker"><Picker value={view} onChange={navigate} label="재테크 보기" options={menu.map(item=>[item.id,item.label])}/></div></div>
 <div className="asset-main">
 {invalidCount>0&&<div className="error-banner" role="status">읽을 수 없는 직접 등록 자산 {invalidCount}개를 제외했습니다. 나머지 자산은 계속 사용할 수 있어요.</div>}{error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>void refresh()}>다시 확인</button></div>}
 {!templateMode&&!signedIn&&<div className="login-notice"><LockKeyhole size={16}/><span>로그인 후 저장 가능</span>{embedded?<button onClick={()=>window.parent.postMessage({type:'aider-assets-login'},location.origin)}>로그인</button>:<a href="/signin-with-chatgpt?return_to=/" target="_top">로그인</a>}</div>}

 {(view==='overview'||view==='saved')&&<section className="collection-summary" aria-label="내 관심 상품 요약"><button onClick={()=>navigate('saved')}><span>관심 상품</span><strong>{savedAssets.length}<small>개</small></strong></button><button onClick={()=>navigate('holdings')}><span>보유 상품</span><strong>{holdings.length}<small>개</small></strong></button><button onClick={()=>{navigate('saved');setMarket('property')}}><span>관심 매물</span><strong>{savedAssets.filter(a=>a.kind==='property').length}<small>곳</small></strong></button><button onClick={()=>{navigate('saved');setFilters({...emptyFilters,notesOnly:true})}}><span>메모</span><strong>{savedAssets.filter(a=>savedNote(a.id).trim()).length}<small>개</small></strong></button></section>}
 {view==='alerts'&&<div className="finance-alert-controls"><Tabs value={filters.alert} onValueChange={alert=>setFilters({...filters,alert})}><TabsList className="filter-tabs">{[['all','전체 목표',targetAssets.length],['met','충족',targetAssets.filter(a=>targetMet(a,getManagement(a.id))).length],['pending','대기',targetAssets.filter(a=>!targetMet(a,getManagement(a.id))).length]].map(([id,label,count])=><TabsTrigger key={id} value={String(id)}>{label}<span>{count}</span></TabsTrigger>)}</TabsList></Tabs><span className="view-data-basis">예시/입력값 · 화면 내 알림</span></div>}{view==='holdings'&&<div className="holdings-summary">{(['KRW','USD'] as const).map(currency=>{const list=holdings.filter(a=>a.currency===currency),value=list.reduce((sum,a)=>sum+position(a,getManagement(a.id))!.value,0),profit=list.reduce((sum,a)=>sum+position(a,getManagement(a.id))!.profit,0);return <div key={currency}><span>{currency==='KRW'?'원화':'달러'} 평가금액 · 예시/입력값</span><strong>{currency==='USD'?String.fromCharCode(36)+value.toLocaleString('en-US',{maximumFractionDigits:2}):value.toLocaleString('ko-KR',{maximumFractionDigits:2})+'원'}</strong><small className={profit>=0?'profit-up':'profit-down'}>평가손익 {profit>=0?'+':''}{currency==='USD'?String.fromCharCode(36)+profit.toLocaleString('en-US',{maximumFractionDigits:2}):profit.toLocaleString('ko-KR',{maximumFractionDigits:2})+'원'}</small></div>})}</div>}{['stock','etf','fund'].includes(view)&&chartAsset&&<section className="stock-chart-panel"><div className="stock-chart-title"><h2>{view==='fund'?'기준가 추이':'가격 추이'} <span>예시</span></h2><Picker value={chartAsset.id} onChange={setChartId} label="차트 종목" options={chartAssets.map(a=>[a.id,a.name])}/></div><PriceChart key={chartAsset.id} asset={chartAsset}/></section>}
 {view==='compare'&&<section className="comparison-workspace"><div className="finance-selection-bar"><div className="finance-selected-items">{comparisons.map(a=><button key={a.id} onClick={()=>choose(a.id)} aria-label={a.name+' 비교 해제'}>{a.name}<X size={13}/></button>)}<span>{comparisons.length} / 4</span></div>{comparisons.length>0&&<button className="text-button" onClick={()=>setSelected([])}>전체 해제</button>}</div>{comparisons.length>=2?<><Collapsible className="compare-options"><CollapsibleTrigger className="text-button"><Settings2 size={14}/> 비교 항목</CollapsibleTrigger><CollapsibleContent><div className="compare-field-picker"><span>가격 고정</span>{[['space','기본 정보'],['unit','단가·통화'],['note','메모'],['status','상태·태그'],['target','목표가'],['holding','보유손익'],['fee','관리비'],['metrics','상품 지표']].map(([id,label])=><label key={id}><Checkbox checked={compareFields.includes(id)} onCheckedChange={()=>toggleField(id)}/>{label}</label>)}</div></CollapsibleContent></Collapsible><div className="comparison-reading"><span className="reading-icon"><ListChecks size={22}/></span><div><p>가격 비교 <span>선택한 자산 전체 기준 · 예시/입력값</span></p><h2>{compareSummary(comparisons).title}</h2></div></div>{comparisons.filter(a=>hasPriceChart(a)&&a.series.length>1).length>=2&&<div className="compare-chart-panel"><Chart items={comparisons.filter(hasPriceChart)}/></div>}<FinanceComparison items={comparisons} fields={compareFields} store={assetStore}/></>:<div className="comparison-start"><div><h2>비교할 자산 2~4개 선택</h2></div><button className="outline" onClick={()=>setSelected(['p1','p2'])}>아파트 비교 예시 <ArrowRight size={16}/></button></div>}</section>}
 <div className={`browse-layout ${view==='compare'?'wide':''}`}><section className="browse-section"><div className="browse-title"><div><h2>{view==='saved'?'관심 목록':view==='compare'?'비교할 상품':view==='holdings'?'보유 상품':view==='alerts'?'목표가 알림':view==='overview'?'전체 상품':menu.find(m=>m.id===view)?.label} <span>{showing.length}</span></h2></div><div className="view-tools"><button className="icon-button" onClick={()=>void refresh()} disabled={templateMode||refreshing||busy} aria-label="목록 새로고침"><RefreshCw size={17} className={refreshing?'spinning':''}/></button><Picker value={sort} onChange={setSort} label="정렬 기준" options={sortOptions(view)}/></div></div><div className="browse-controls"><Tabs value={market} onValueChange={setMarket}><TabsList className="filter-tabs">{(['stock','etf'].includes(view)?[['all','전체'],['kr','국내'],['us','미국'],['manual','직접 등록']]:['bond','fund'].includes(view)?[['all','전체'],['KRW','원화'],['USD','달러'],['manual','직접 등록']]:view==='property'?[['all','전체 매물'],['manual','직접 등록']]:view==='overview'?[['all','전체'],['KRW','원화'],['USD','달러'],['manual','직접 등록']]:[['all','전체'],['KRW','원화'],['USD','달러'],['stock','주식'],['etf','ETF'],['bond','채권'],['fund','펀드'],...(view==='holdings'?[]:[['property','부동산']])]).map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList></Tabs><label className="search-box"><Search size={16}/><input placeholder="이름 · 코드 · 태그 · 메모" aria-label="자산 검색" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="검색어 지우기"><X size={14}/></button>}</label></div>
 <FinanceFilters key={view} store={assetStore} count={filterCount}/>
 {(filterCount>0||query||market!=='all'||filters.alert!=='all')&&<div className="active-filters"><span>{showing.length}개 결과</span><button onClick={()=>{setFilters(emptyFilters);setQuery('');setMarket('all')}}>조건 초기화 <X size={13}/></button></div>}
 {!ready&&['saved','holdings','alerts'].includes(view)?<div className="loading-state" role="status"><RefreshCw className="spinning" size={20}/> 저장한 자산을 불러오는 중이에요.</div>:showing.length?<FinanceProductList items={showing} store={assetStore}/>:<div className="empty-state"><Star size={30}/><h3>{view==='saved'&&!savedAssets.length?'저장한 자산 없음':view==='alerts'?(targetAssets.length?'해당 조건의 목표 없음':'설정한 목표가 없음'):'검색 결과 없음'}</h3><button className="outline" onClick={()=>{setQuery('');setMarket('all');setFilters(emptyFilters);if(view==='saved'||view==='alerts'&&!targetAssets.length)navigate('overview')}}>{view==='saved'||view==='alerts'&&!targetAssets.length?'상품 둘러보기':'필터 초기화'}</button></div>}
 <div className="list-foot">{templateMode?<span>미리보기 · 저장 및 자동 확인 꺼짐</span>:<><span><Switch aria-label="목록 자동 확인" checked={automatic} onCheckedChange={v=>{setAutomatic(v);try{localStorage.setItem('moa-auto',v?'on':'off')}catch{}}}/> 자동 확인 · 1분</span><span>{checked?`마지막 확인 ${stamp(checked)}`:'목록 확인 중'}</span></>}</div></section>

 </div></div></section></main>
 {selected.length>0&&view!=='compare'&&<div className="compare-dock"><span><Layers3 size={18}/><b>{selected.length} / 4</b> 선택</span><button className="primary" onClick={()=>navigate('compare')} disabled={selected.length<2}>{selected.length<2?'비교 대기':'비교하기'} <ArrowRight size={16}/></button><button className="icon-button" onClick={()=>setSelected([])} aria-label="비교 선택 초기화"><X size={18}/></button></div>}
 {managed&&<ManagementDialog key={managed.asset.id} snapshot={managed} busy={busy} canSave={ready&&signedIn} onClose={()=>setManaged(null)} onSave={saveManagement}/>}<Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>데이터 연결</DialogTitle><DialogDescription>예시 데이터 · 실제 시세 미연결</DialogDescription></DialogHeader><div className="finance-providers">{[['주식·ETF','거래가격'],['채권','단가·금리·만기'],['펀드','기준가·상품 정보'],['부동산','호가·실거래']].map(([name,description])=><div key={name}><span><b>{name}</b><small>{description}</small></span><span className="tag">미연결</span></div>)}<div><span><b>직접 등록</b><small>상품·보유 내역·메모</small></span><span className="connected-tag">{templateMode?'미리보기':'사용 가능'}</span></div></div><p className="management-footnote">{templateMode?'미리보기 · 데이터 연결 및 자동 확인 꺼짐':'1분마다 저장 목록 확인 · 시세 자동 수집 없음'}</p></DialogContent></Dialog>
 <Sheet open={!!detail} onOpenChange={o=>{if(!o)requestDetailClose()}}><SheetContent className="detail-sheet">{detail&&<><SheetHeader><span className="eyebrow">{assetGroup(detail)}</span><SheetTitle>{detail.name}</SheetTitle><SheetDescription>{detail.sub}</SheetDescription></SheetHeader><div className="detail-body"><span className="sample-pill">{detail.sample?'예시 데이터':'직접 입력'}</span><div className="detail-price">{money(detail)}</div><p className="muted">{detail.kind==='property'?'매매 호가 · 실거래가 아님':priceLabel(detail)+' · '+(detail.currency==='USD'?'USD':'KRW')}</p><div className="detail-metrics">{detail.kind==='property'?<><div><span>전용 면적</span><b>{areaLabel(detail)}</b></div><div><span>㎡당 호가</span><b>{Math.round(detail.price/detail.area!/10000).toLocaleString()}만원</b></div>{detail.floor&&<div><span>층수 · 예시</span><b>{detail.floor}</b></div>}{detail.year&&<div><span>준공 · 예시</span><b>{detail.year}년</b></div>}</>:<>{productFacts(detail).map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</>}<div><span>출처</span><b>{detail.source}</b></div><div><span>{detail.sample?'기준 시각':'입력 시각'}</span><b>{detail.sample?'없음 · 체험용':stamp(detail.asOf)}</b></div></div>{detail.url&&<a className="outline source-link" href={detail.url} target="_blank" rel="noreferrer">원본 링크 보기 <ExternalLink size={15}/></a>}{!detail.sample&&<button className="text-button" onClick={()=>startEdit(detail)}>입력 정보 수정 <Settings2 size={15}/></button>}{hasPriceChart(detail)&&<div className="detail-price-chart"><PriceChart key={detail.id} asset={detail} compact/></div>}<button className="outline full-width manage-detail-button" disabled={!ready||!signedIn||busy} onClick={()=>openManagement(detail)}>상태 · 목표가 · {detail.kind==='property'?'방문':'보유'} · 이력</button><label className="field-label" htmlFor="asset-note">내 메모</label><textarea id="asset-note" readOnly={templateMode} value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder={templateMode?'미리보기':'메모 입력'} rows={5}/><div className="note-actions"><span className="subtle">{templateMode?'미리보기':noteDirty?'미저장':'저장됨'} · {note.length}/2,000</span><button className="primary" disabled={busy||!ready||!signedIn||!noteDirty} onClick={async()=>{if(await save(detail.id,watched(detail.id),note,undefined,draftRevision.current))toast.success('메모를 저장했습니다.')}}>{busy?'저장 중…':'메모 저장'}</button></div><button className={`outline full-width ${watched(detail.id)?'is-saved':''}`} disabled={busy||!ready||!signedIn} onClick={()=>void toggleWatch(detail)}><Star size={17} fill={watched(detail.id)?'currentColor':'none'}/>{watched(detail.id)?'관심 자산에서 해제':'관심 자산에 저장'}</button></div></>}</SheetContent></Sheet>
 <Dialog open={closePrompt} onOpenChange={setClosePrompt}><DialogContent className="guide-dialog"><DialogHeader><DialogTitle>작성한 메모를 저장할까요?</DialogTitle><DialogDescription>저장하지 않고 닫으면 방금 작성한 내용이 사라져요.</DialogDescription></DialogHeader><div className="draft-actions"><button className="outline" onClick={()=>setClosePrompt(false)}>계속 작성</button><button className="text-button" onClick={()=>{setClosePrompt(false);setDetail(null)}}>저장 안 하고 닫기</button><button className="primary" disabled={busy||!signedIn} onClick={async()=>{if(detail&&await save(detail.id,watched(detail.id),note,undefined,draftRevision.current)){setClosePrompt(false);setDetail(null);toast.success('메모를 저장했습니다.')}}}>저장하고 닫기</button></div></DialogContent></Dialog>
 <Dialog open={addOpen} onOpenChange={o=>{if(!busy)setAddOpen(o)}}><DialogContent className="add-dialog"><DialogHeader><DialogTitle>{edit?'상품 정보 수정':'관심 상품 등록'}</DialogTitle><DialogDescription>직접 입력 · 시세 자동 연동 없음</DialogDescription></DialogHeader><AssetForm key={edit?.id??'new'} edit={edit} type={addType} setType={setAddType} onSubmit={addAsset} busy={busy} canSave={ready&&signedIn} error={formError}/></DialogContent></Dialog>

</div>
}
