'use client';
import {Bell,Star,PencilLine} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {Asset,money,priceLabel,quantityUnit,hasPriceChart} from './data';
import {assetGroup,areaLabel,plainChange,productFacts} from './asset-content';
import {position,statusLabels,targetMet} from './management';
import type {useAssets} from './use-assets';
type Store=ReturnType<typeof useAssets>;
export function FinanceProductList({items,store}:{items:Asset[];store:Store}){
 const {selected,choose,watched,toggleWatch,openDetail,openManagement,getManagement,savedNote,ready,signedIn,busy,view}=store;
 return <div className="finance-list-panel"><Table className="finance-product-table" aria-label="재테크 상품 목록"><colgroup><col className="product-col"/><col className="price-col"/><col className="facts-col"/><col className="record-col"/><col className="compare-col"/></colgroup><TableHeader><TableRow><TableHead scope="col">상품</TableHead><TableHead scope="col">가격 · 기준</TableHead><TableHead scope="col">주요 정보</TableHead><TableHead scope="col">내 기록</TableHead><TableHead scope="col" className="compare-heading">비교</TableHead></TableRow></TableHeader><TableBody>{items.map(a=>{
 const m=getManagement(a.id),held=position(a,m),note=savedNote(a.id),active=selected.includes(a.id),met=targetMet(a,m);
 return <TableRow key={a.id} data-kind={a.kind} data-state={active?'selected':undefined} className="finance-product-row">
 <TableCell className="product-identity"><div className="product-identity-inner"><button className={`product-watch ${watched(a.id)?'saved':''}`} onClick={()=>void toggleWatch(a)} disabled={!ready||busy||!signedIn} aria-label={`${a.name} 관심 ${watched(a.id)?'해제':'저장'}`} aria-pressed={watched(a.id)}><Star size={16} fill={watched(a.id)?'currentColor':'none'}/></button><div className="product-name-block"><button className="product-name" onClick={()=>openDetail(a)}>{a.name}</button><span>{assetGroup(a)}<i>·</i>{a.kind==='property'?a.sub.replace(' · 가상 매물','')+(a.sample?' · 예시':''):a.sample?'예시':a.sub}</span></div></div></TableCell>
 <TableCell className="product-price-cell"><strong>{money(a)}</strong><div className="product-price-meta"><span>{priceLabel(a)}</span>{hasPriceChart(a)&&a.sample&&<span className={a.change>=0?'profit-up':'profit-down'} title={a.kind==='fund'?'직전 기준가 대비':'전일 대비'}>{a.change>0?'+':''}{a.change.toFixed(2)}%</span>}</div></TableCell>
 <TableCell className="product-facts-cell">{a.kind==='stock'?<><span className={a.sample?(a.change>=0?'profit-up':'profit-down'):''}>{plainChange(a)}</span><small>{a.sub}</small></>:a.kind==='property'?<><span>{areaLabel(a)}</span><small>{[a.floor,a.year?`${a.year}년 준공`:''].filter(Boolean).join(' · ')||'직접 입력'}</small></>:productFacts(a).map(([label,value],i)=><span key={label} className={i?'fact-secondary':''}><small>{label}</small> {value}</span>)}</TableCell>
 <TableCell className="product-record-cell"><div className="product-record-inner"><div className="product-record-data">{(m.status!=='none'||m.tags.length>0)&&<div className="product-record-tags">{m.status!=='none'&&<span>{statusLabels[m.status]}</span>}{m.tags.slice(0,2).map(t=><small key={t}>{t}</small>)}</div>}{held&&<span className={`product-holding ${held.profit>=0?'profit-up':'profit-down'}`}>{m.quantity?.toLocaleString()}{quantityUnit(a)}<i>·</i>{held.profit>=0?'+':''}{money({...a,price:held.profit})}{view==='holdings'&&<small> ({held.percent>=0?'+':''}{held.percent.toFixed(1)}%)</small>}</span>}{m.targetPrice!==null&&<span className={`product-target ${met?'met':''}`}><Bell size={12}/>{money({...a,price:m.targetPrice})} {m.targetDirection==='below'?'이하':'이상'}{met?<b>충족</b>:view==='alerts'&&<b className="pending">대기</b>}</span>}{view==='alerts'&&m.targetPrice!==null&&!met&&<span className="product-target-distance">목표까지 {(m.targetPrice/a.price-1)>=0?'+':''}{((m.targetPrice/a.price-1)*100).toFixed(1)}%</span>}{note&&<span className="product-note" title={note}><PencilLine size={12}/><span>{note}</span></span>}</div><button className="product-manage" onClick={()=>openManagement(a)} disabled={!ready||!signedIn||busy} aria-label={`${a.name} 관리`}>관리</button></div></TableCell>
 <TableCell className="product-compare-cell"><label><Checkbox checked={active} onCheckedChange={()=>choose(a.id)} aria-label={`${a.name} 비교 선택`}/><span className="product-mobile-compare-label">비교</span></label></TableCell>
 </TableRow>;
 })}</TableBody></Table></div>;
}
