/* Active Consult workspace. Existing bridge owns authorization, persistence and calendar refresh. */
(() => {
 'use strict';
 const M=window.AiderConsultModelV167, esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), clone=v=>JSON.parse(JSON.stringify(v));
 const $=(s,r=host)=>r?.querySelector(s), $$=(s,r=host)=>[...(r?.querySelectorAll(s)||[])], uid=()=>bridge()?.identity?.()?.uid||'', bridge=()=>window.AiderConsultBridge;
 const ID=kind=>'consult-'+kind+'-'+crypto.randomUUID(), date=()=>new Date().toLocaleDateString('en-CA'), shortDate=value=>value?String(value).replace('T',' '):'미정';
 const MENUS={today:'오늘',clients:'고객',calendar:'지원 일정',documents:'문서·피드백',closed:'종료·결과'}, TABS={overview:'개요',strategy:'지원 전략',tasks:'과업',sessions:'상담 기록',files:'문서',notes:'내부 메모'};
 const TASK_STATUS={waiting:'대기',active:'진행',done:'완료'}, SESSION_STATUS={scheduled:'예정',completed:'완료',cancelled:'취소'}, FILE_STATUS={pending:'검토 대기',revision:'보완',final:'확정'}, FILE_TYPES={proposal:'연구계획서',statement:'자기소개서',cv:'CV',interview:'면접 준비',other:'기타 자료'};
 const DEGREE={masters:'석사',doctoral:'박사',integrated:'석박사 통합',other:'기타'}, SEMESTER={spring:'전기 · 1학기',fall:'후기 · 2학기',rolling:'수시',other:'기타'};
 let host=null,data=null,owner='',activeDialog=null,dirty=false,saving=false,revisionWarning='';
 let state={menu:'today',clientId:'',tab:'overview',query:'',status:'active',year:'',semester:'',kind:'',from:'',to:'',fileStatus:'',fileType:'',result:'',calendarMode:'list',month:date().slice(0,7),scroll:new Map()};
 const badge=(label,kind='')=>`<span class="c167-badge ${esc(kind)}">${esc(label||'미정')}</span>`;
 const action=(label,op,id='',extra='')=>`<button type="button" data-c167="${op}" data-id="${esc(id)}" ${extra}>${esc(label)}</button>`;
 const field=(name,label,value='',type='text',options=null,required=false)=>`<label><span>${esc(label)}${required?' *':''}</span>${options?`<select name="${name}">${Object.entries(options).map(([v,l])=>`<option value="${esc(v)}" ${String(value)===v?'selected':''}>${esc(l)}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${name}" rows="3" ${required?'required':''}>${esc(Array.isArray(value)?value.join('\n'):value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'step="any"':''}>`}</label>`;
 const dl=fields=>`<dl class="c167-values">${Object.entries(fields).map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(Array.isArray(value)?value.join(' · '):value||'—')}</dd></div>`).join('')}</dl>`;
 const empty=label=>`<p class="c167-empty">${label}</p>`;
 function selected(){return data?.consultingClients.find(c=>c.id===state.clientId)}
 function clientName(id){return data.consultingClients.find(c=>c.id===id)?.name||'고객 확인 필요'}
 function rowsFor(collection,id=state.clientId){return data[collection].filter(r=>r.clientId===id)}
 function nearest(id){return M.calendar(data).find(r=>r.clientId===id&&r.date>=date()&&r.status!=='done'&&r.status!=='cancelled')}
 function rememberScroll(){for(const el of $$('[data-scroll-key]'))state.scroll.set(el.dataset.scrollKey,el.scrollTop)}
 function restoreScroll(){for(const el of $$('[data-scroll-key]'))el.scrollTop=state.scroll.get(el.dataset.scrollKey)||0}
 function notify(message){bridge()?.notify?.(message)}
 function assertOwner(expected=owner){if(!bridge()?.canAccess?.()||!expected||uid()!==expected)throw Error('로그인 계정이 바뀌었습니다. 다시 열어 주세요.')}
 async function commit(collection,row,before=null,requestId=ID('request')){assertOwner();const result=await bridge().commit({collection,id:row.id,expectedRevision:M.rev(before),expectedUpdatedAt:Number(before?.updatedAt||before?.createdAt)||0,row,requestId});assertOwner();if(result?.payload)data=M.normalize(result.payload);else data=M.normalize(bridge().snapshot());return result}
 function render(){
  const stage=document.getElementById('taskPage0');if(!stage||!M)return;const nextOwner=uid();if(owner!==nextOwner){activeDialog?.close();activeDialog?.remove();activeDialog=null;dirty=false;owner=nextOwner;state={...state,menu:'today',clientId:'',tab:'overview',query:'',scroll:new Map()}}
  if(!bridge()?.canAccess?.()){stage.replaceChildren();host=document.createElement('section');host.id='consultV167';host.innerHTML=empty('로그인이 필요합니다.');stage.append(host);host=null;return}
  data=M.normalize(bridge().snapshot());if(!host?.isConnected){stage.replaceChildren();host=document.createElement('section');host.id='consultV167';host.dataset.consultV167='';stage.append(host);host.addEventListener('click',click);host.addEventListener('change',change);host.addEventListener('input',input)}
  rememberScroll();host.innerHTML=`<nav class="c167-nav" aria-label="컨설트 메뉴">${Object.entries(MENUS).map(([key,label])=>action(label,'menu',key,`aria-current="${state.menu===key?'page':'false'}"`)).join('')}<div>${action('고객 작성 링크','intake')}${action('입시요강','admissions')}</div></nav><section class="c167-workspace"><header class="c167-toolbar"><h2>${MENUS[state.menu]}</h2><div>${state.menu==='clients'||state.menu==='today'?action('고객 추가','client-new'):''}${action('새로고침','refresh')}</div></header><div class="c167-content" data-scroll-key="main-${state.menu}">${page()}</div><div class="c167-live" role="status" aria-live="polite">${esc(revisionWarning)}</div></section>`;restoreScroll();
 }
 function page(){if(state.menu==='today')return today();if(state.menu==='clients'||state.menu==='closed')return clients();if(state.menu==='calendar')return calendar();return documentList()}
 function today(){const active=data.consultingClients.filter(c=>c.consult167.status==='active'),pending=data.consultingTasks.filter(r=>r.status!=='done'),due=pending.filter(r=>r.dueDate&&r.dueDate<=date()),files=M.latestDocuments(data).filter(r=>r.status==='pending'),sessions=data.consultingSessions.filter(r=>r.status==='scheduled'&&r.date?.slice(0,10)>=date()).sort((a,b)=>a.date.localeCompare(b.date)),close=M.calendar(data).filter(r=>r.kind==='target'&&r.date>=date()).slice(0,8);
  const queue=[...due.map(r=>({id:r.id,clientId:r.clientId,label:r.title,meta:r.dueDate,tab:'tasks'})),...close.map(r=>({id:r.sourceId,clientId:r.clientId,label:r.title,meta:r.date,tab:'strategy'})),...files.map(r=>({id:r.id,clientId:r.clientId,label:r.name,meta:'검토 대기 · v'+r.version,tab:'files'})),...sessions.filter(r=>r.date.slice(0,10)===date()).map(r=>({id:r.id,clientId:r.clientId,label:r.title||'상담',meta:shortDate(r.date),tab:'sessions'}))];
  return `<div class="c167-counts">${[['진행 고객',active.length],['오늘·기한 경과 과업',due.length],['검토 대기 문서',files.length],['예정 상담',sessions.length]].map(([label,n])=>`<div><small>${label}</small><b>${n}</b></div>`).join('')}</div><section class="c167-section"><h3>먼저 처리할 일</h3>${queue.map(r=>`<button class="c167-list-row" data-c167="jump" data-id="${esc(r.clientId)}" data-tab="${r.tab}" data-record="${esc(r.id)}"><span><b>${esc(r.label)}</b><small>${esc(clientName(r.clientId))}</small></span><span>${esc(r.meta)}</span></button>`).join('')||empty('처리할 항목 없음')}</section><section class="c167-section"><h3>진행 고객</h3>${active.map(c=>{const p=M.progress(data,c.id),n=nearest(c.id),task=pending.find(r=>r.clientId===c.id);return `<button class="c167-list-row" data-c167="select" data-id="${esc(c.id)}"><span><b>${esc(c.name)}</b><small>${esc(M.STAGES[c.consult167.stage]||'단계 확인 필요')} · ${esc(task?.title||'다음 과업 없음')}</small></span><span>${esc(n?.date||'마감 미정')}<small>완료 과업 ${p.done}/${p.total}</small></span></button>`}).join('')||empty('진행 고객 없음')}</section>`;
 }
 function filterBar(extra=''){return `<div class="c167-filters"><label>검색<input type="search" data-filter="query" aria-label="고객·전공·대학원·연구 주제 검색" value="${esc(state.query)}"></label><label>학년도<input data-filter="year" inputmode="numeric" value="${esc(state.year)}"></label><label>지원 시기<select data-filter="semester"><option value="">전체</option>${Object.entries(SEMESTER).map(([k,v])=>`<option value="${k}" ${state.semester===k?'selected':''}>${v}</option>`).join('')}</select></label>${extra}</div>`}
 function visibleClients(){const q=state.query.trim().toLowerCase();return data.consultingClients.filter(c=>{const e=c.consult167;if(state.menu==='closed'?e.status!=='closed':state.status!=='all'&&e.status!==state.status)return false;if(state.year&&String(c.applicationYear)!==state.year)return false;if(state.semester&&c.applicationSemester!==state.semester)return false;if(state.result&&!e.targets.some(t=>t.result===state.result))return false;return !q||[c.name,c.currentMajor,c.targetUniversity,c.targetMajor,c.topic,...e.targets.map(t=>t.university+' '+t.department)].join(' ').toLowerCase().includes(q)})}
 function clients(){return `${filterBar(state.menu==='closed'?`<label>지원 결과<select data-filter="result"><option value="">전체</option>${Object.entries(M.RESULTS).map(([k,v])=>`<option value="${k}" ${state.result===k?'selected':''}>${v}</option>`).join('')}</select></label>`:`<label>상태<select data-filter="status">${Object.entries({...M.STATUS,all:'전체'}).map(([k,v])=>`<option value="${k}" ${state.status===k?'selected':''}>${v}</option>`).join('')}</select></label>`)}<div class="c167-split ${selected()?'has-selection':''}"><aside class="c167-client-list" data-scroll-key="clients-${state.menu}">${clientList()}</aside><article class="c167-detail" data-scroll-key="detail-${state.clientId}">${selected()?detail(selected()):empty('고객을 선택하세요.')}</article></div>`}
 function clientList(){return visibleClients().map(c=>{const n=nearest(c.id),p=M.progress(data,c.id);return `<button class="c167-client-row ${c.id===state.clientId?'selected':''}" data-c167="select" data-id="${esc(c.id)}"><strong>${esc(c.name)}</strong>${badge(M.STAGES[c.consult167.stage]||'단계 확인 필요')}<small>${esc(n?.date||'다음 마감 없음')} · 미완료 ${p.total-p.done}</small></button>`}).join('')||empty('등록된 고객 없음')}
 function detail(c){return `<header class="c167-detail-head">${action('목록','back')}<div><h3>${esc(c.name)}</h3><small>${esc([c.applicationYear&&c.applicationYear+'학년도',SEMESTER[c.applicationSemester],DEGREE[c.degree],c.currentMajor].filter(Boolean).join(' · '))}</small></div>${badge(M.STATUS[c.consult167.status])}<div>${action('정보 수정','client-edit',c.id)}${action('전달본','delivery',c.id)}${action(c.consult167.status==='closed'?'복원':'보관','archive',c.id)}</div></header><div class="c167-stages" aria-label="고객 단계">${Object.entries(M.STAGES).map(([k,v])=>action(v,'stage',k,`aria-pressed="${c.consult167.stage===k}"`)).join('')}</div>${c.consult167.stageNeedsReview?`<p class="c167-warning">이전 단계: ${esc(c.consult167.legacyStage)} · 확인 필요</p>`:''}<nav class="c167-detail-tabs" aria-label="고객 상세">${Object.entries(TABS).map(([k,v])=>action(v,'tab',k,`aria-selected="${state.tab===k}"`)).join('')}</nav><section class="c167-detail-body">${({overview:overview,strategy:strategy,tasks:tasks,sessions:sessions,files:documents,notes:notes}[state.tab]||overview)(c)}</section>`}
 function overview(c){const n=nearest(c.id),t=rowsFor('consultingTasks').filter(r=>r.status!=='done'),s=rowsFor('consultingSessions').filter(r=>r.status==='scheduled').sort((a,b)=>String(a.date).localeCompare(String(b.date)))[0],last=rowsFor('consultingSessions').filter(r=>r.decisions).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))[0];return `<section class="c167-section"><h4>원문 정보</h4>${dl({'연락처':c.phone||c.contact,이메일:c.email,출생연도:c.birthYear,성별:({female:'여성',male:'남성'})[c.gender],학교:c.currentSchool||c.institution,주전공:c.currentMajor||c.program,추가전공:c.additionalMajors,복수전공:c.doubleMajor,부전공:c.minor,대학유형:c.universityYears,군필여부:c.militaryStatus,학점:c.gpa?c.gpa+' / '+c.gpaScale:'',희망과정:DEGREE[c.degree],지원시기:[c.applicationYear,SEMESTER[c.applicationSemester]].filter(Boolean).join(' · '),희망대학원:c.targetUniversity||c.university,희망전공:c.targetMajor||c.major,지도교수:c.advisorNames,연구관심:c.topic,연구경험:c.researchExperience,성과물:c.outputs,어학:c.languageSpec,자격증:c.certifications,활동:c.activities,문의사항:c.inquiry})}</section><section class="c167-section"><h4>현재 과제·결정</h4>${dl({'핵심 과업':t.map(r=>r.title).join('\n'),'다음 상담':s?shortDate(s.date):c.nextSession,'다음 마감':n?.date,'최근 결정':last?.decisions})}</section>${c.note?`<details class="c167-section"><summary>이전 고객 메모 · 원문 보존</summary><p>${esc(c.note)}</p></details>`:''}`}
 function strategy(c){return `<div class="c167-actions">${action('지원 후보 추가','target-new')}${action('기존 지원 분석','analysis',c.id)}</div>${c.consult167.targets.map(r=>`<section class="c167-section"><header><h4>${esc(r.university||'대학원 미입력')} · ${esc(r.department)}</h4>${action('수정','target-edit',r.id)}</header>${dl({과정:DEGREE[r.degree]||r.degree,'교수·연구실':r.advisor,연구방향:r.researchDirection,우선순위:r.priority,지원마감:r.deadline,연락지원상태:r.applicationStatus,결과:M.RESULTS[r.result],출처:r.sourceUrl,확인일:r.checkedAt,판단근거:r.rationale})}<div class="c167-checks">${['eligibility','research','language','advisor'].map(key=>{const check=r.checks?.[key]||{};return `<div><b>${({eligibility:'지원자격',research:'연구 경험 적합성',language:'어학',advisor:'지도교수'})[key]}</b>${badge(check.evidence?({verified:'확인',supplement:'보완',unknown:'미확인'})[check.status]||'미확인':'미확인')}<p>${esc(check.evidence||'근거 없음')}</p></div>`}).join('')}</div></section>`).join('')||empty('지원 후보 없음')}`}
 function tasks(c){return `<div class="c167-actions">${action('과업 추가','task-new')}</div>${rowsFor('consultingTasks').map(r=>`<section class="c167-section" id="c167-row-${esc(r.id)}"><header><h4>${esc(r.title)}</h4>${badge(TASK_STATUS[r.status])}</header>${dl({담당:r.legacyAssignee?r.legacyAssignee+' · 담당 확인 필요':r.assignee==='consultant'?'컨설턴트':'고객',단계:M.STAGES[r.stage],마감:shortDate(r.dueDate),우선순위:r.priority,상세요청:r.description,완료조건:r.acceptanceCriteria,결과:r.result})}<footer>${action('수정','task-edit',r.id)}${action(r.status==='done'?'완료 취소':'완료','task-toggle',r.id)}${r.sessionId?action('관련 상담','source-session',r.sessionId):''}${r.documentId?action('관련 문서','source-file',r.documentId):''}</footer></section>`).join('')||empty('등록된 과업 없음')}`}
 function sessions(c){return `<div class="c167-actions">${action('상담 추가','session-new')}</div>${rowsFor('consultingSessions').slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(r=>`<section class="c167-section" id="c167-row-${esc(r.id)}"><header><h4>${esc(r.title||'상담 기록')}</h4>${badge(SESSION_STATUS[r.status])}</header>${dl({일시:shortDate(r.date),'최초 일시':shortDate(r.originalDate),방식:r.method,관련단계:M.STAGES[r.stage],상담목적:r.purpose,논의내용:r.discussion||r.summary,결정사항:r.decisions,'고객 할 일':r.clientActions,'컨설턴트 할 일':r.consultantActions,다음일정:r.nextDate,고객피드백:r.clientFeedback})}<details><summary>내부 메모</summary><p>${esc(r.internalNote||'없음')}</p></details>${r.history.length?`<details><summary>변경 이력 ${r.history.length}</summary>${r.history.map(h=>dl({변경일:new Date(h.changedAt).toLocaleString('ko-KR'),이전일시:h.date,상태:SESSION_STATUS[h.status]})).join('')}</details>`:''}<footer>${action('수정','session-edit',r.id)}${action('후속 과업','follow-session',r.id)}</footer></section>`).join('')||empty('상담 기록 없음')}`}
 function documents(c){const versions=rowsFor('consultingFiles'),latest=M.latestDocuments({...data,consultingFiles:versions});return `<div class="c167-actions">${action('문서 추가','file-new')}</div>${latest.map(r=>`<section class="c167-section" id="c167-row-${esc(r.documentId)}"><header><h4>${esc(r.name)}</h4>${badge(FILE_TYPES[r.documentType])}${badge(FILE_STATUS[r.status])}</header><p>v${r.version} · ${new Date(r.createdAt).toLocaleDateString('ko-KR')}</p><p>${esc(r.customerFeedback||'고객 피드백 없음')}</p><footer>${action('버전·피드백','file-view',r.id)}${action('새 버전','file-version',r.id)}${action('보완 과업','follow-file',r.id)}</footer><details><summary>이전 버전 ${versions.filter(v=>v.documentId===r.documentId).length}</summary>${versions.filter(v=>v.documentId===r.documentId).sort((a,b)=>b.version-a.version).map(v=>`<div class="c167-list-row"><span>v${v.version} · ${esc(v.name)}</span>${action('열기','file-view',v.id)}${v.fileId?action('다운로드','file-download',v.id):''}</div>`).join('')}</details></section>`).join('')||empty('등록된 문서 없음')}`}
 function notes(c){return `<div class="c167-actions">${action('내부 메모 추가','note-new')}</div>${c.consult167.internalNotes.map(r=>`<section class="c167-section"><header><small>${new Date(r.updatedAt||r.createdAt).toLocaleString('ko-KR')}</small>${action('수정','note-edit',r.id)}</header><p>${esc(r.text)}</p></section>`).join('')||empty('내부 메모 없음')}`}
 function calendar(){let rows=M.calendar(data).filter(r=>(!state.kind||r.kind===state.kind)&&(!state.clientId||r.clientId===state.clientId)&&(!state.from||r.date>=state.from)&&(!state.to||r.date<=state.to));return `<div class="c167-filters"><label>고객<select data-filter="clientId"><option value="">전체</option>${data.consultingClients.map(c=>`<option value="${esc(c.id)}" ${c.id===state.clientId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>종류<select data-filter="kind">${Object.entries({'':'전체',task:'과업 마감',session:'상담',target:'지원 마감'}).map(([k,v])=>`<option value="${k}" ${k===state.kind?'selected':''}>${v}</option>`).join('')}</select></label><label>시작<input type="date" data-filter="from" value="${esc(state.from)}"></label><label>종료<input type="date" data-filter="to" value="${esc(state.to)}"></label>${action(state.calendarMode==='list'?'달력 보기':'목록 보기','calendar-mode')}</div>${state.calendarMode==='grid'?calendarGrid(rows):rows.map(r=>`<button class="c167-list-row" data-c167="jump" data-id="${esc(r.clientId)}" data-tab="${({task:'tasks',session:'sessions',target:'strategy'})[r.kind]}" data-record="${esc(r.sourceId)}"><span>${esc(r.date)} ${esc(r.time)}</span><span><b>${esc(r.title)}</b><small>${esc(r.clientName)} · ${({task:'과업',session:'상담',target:'지원'})[r.kind]}</small></span></button>`).join('')||empty('해당 일정 없음')}`}
 function calendarGrid(rows){const [year,month]=state.month.split('-').map(Number),first=new Date(year,month-1,1),start=new Date(year,month-1,1-first.getDay());return `<label class="c167-month">월<input type="month" data-filter="month" value="${state.month}"></label><div class="c167-calendar">${['일','월','화','수','목','금','토'].map(x=>`<b>${x}</b>`).join('')}${Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const key=d.toLocaleDateString('en-CA');return `<div class="${d.getMonth()!==month-1?'outside':''}"><time>${d.getDate()}</time>${rows.filter(r=>r.date===key).map(r=>action(clientName(r.clientId)+' · '+r.title,'jump',r.clientId,`data-tab="${({task:'tasks',session:'sessions',target:'strategy'})[r.kind]}" data-record="${esc(r.sourceId)}"`)).join('')}</div>`}).join('')}</div>`}
 function documentList(){const list=M.latestDocuments(data).filter(r=>(!state.clientId||r.clientId===state.clientId)&&(!state.fileStatus||r.status===state.fileStatus)&&(!state.fileType||r.documentType===state.fileType)).sort((a,b)=>(b.updatedAt||b.createdAt)-(a.updatedAt||a.createdAt));return `<div class="c167-filters"><label>고객<select data-filter="clientId"><option value="">전체</option>${data.consultingClients.map(c=>`<option value="${esc(c.id)}" ${c.id===state.clientId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>문서 유형<select data-filter="fileType"><option value="">전체</option>${Object.entries(FILE_TYPES).map(([k,v])=>`<option value="${k}" ${k===state.fileType?'selected':''}>${v}</option>`).join('')}</select></label><label>검토 상태<select data-filter="fileStatus"><option value="">전체</option>${Object.entries(FILE_STATUS).map(([k,v])=>`<option value="${k}" ${k===state.fileStatus?'selected':''}>${v}</option>`).join('')}</select></label></div>${list.map(r=>`<section class="c167-list-row"><span><b>${esc(r.name)}</b><small>${esc(clientName(r.clientId))} · ${FILE_TYPES[r.documentType]} · v${r.version} · ${new Date(r.updatedAt||r.createdAt).toLocaleDateString('ko-KR')}</small><small>보완 과업 ${data.consultingTasks.filter(t=>t.documentId===r.documentId&&t.status!=='done').length}</small></span>${badge(FILE_STATUS[r.status])}${action('버전·피드백','file-view',r.id)}</section>`).join('')||empty('해당 문서 없음')}`}
 function modal(title,body,onSave=null,label='저장',options={}){
  if(activeDialog)return;const prior=document.activeElement,dialog=document.createElement('dialog');dialog.className='c167-dialog'+(options.className?' '+options.className:'');dialog.setAttribute('aria-label',title);dialog.innerHTML=`<form><header><h3>${esc(title)}</h3><button type="button" data-close aria-label="닫기">×</button></header><div class="c167-modal-body">${body}</div><footer><output role="status"></output><button type="button" data-close>취소</button>${onSave?`<button type="submit">${esc(label)}</button>`:''}</footer></form>`;document.body.append(dialog);activeDialog=dialog;dirty=false;const close=()=>{if(saving)return;if(dirty&&!confirm('저장하지 않은 변경을 닫을까요?'))return;dialog.close();dialog.remove();activeDialog=null;dirty=false;prior?.isConnected&&prior.focus({preventScroll:true})};dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('input',()=>dirty=true);dialog.addEventListener('submit',async e=>{e.preventDefault();if(saving||!onSave)return;saving=true;dialog.querySelector('[type=submit]').disabled=true;const requestId=dialog.dataset.requestId||(dialog.dataset.requestId=ID('request'));try{assertOwner();await onSave(new FormData(e.target),dialog,requestId);dirty=false;saving=false;close();render();notify('저장했습니다.')}catch(error){dialog.querySelector('output').textContent=error?.message||'저장하지 못했습니다.';saving=false;dialog.querySelector('[type=submit]').disabled=false}});dialog.showModal();const frame=document.getElementById('taskStage')||document.getElementById('taskPage0');const place=()=>{if(!dialog.isConnected)return;const box=frame?.getBoundingClientRect();if(!box?.height)return;dialog.style.width=Math.max(180,Math.min(options.maxWidth||860,box.width-24))+'px';dialog.style.maxHeight=Math.max(180,Math.min(innerHeight-24,box.height-24))+'px';dialog.style.margin='0';const rect=dialog.getBoundingClientRect();dialog.style.left=Math.max(12,box.left+(box.width-rect.width)/2)+'px';dialog.style.top=Math.max(12,box.top+(box.height-rect.height)/2)+'px'};place();const observer=new ResizeObserver(place);observer.observe(dialog);dialog.addEventListener('close',()=>observer.disconnect(),{once:true});dialog.querySelector('[data-close]').focus();return dialog;
 }
 const vals=form=>Object.fromEntries([...form].filter(([,v])=>typeof v==='string'));
 function editClient(id=''){
  const before=data.consultingClients.find(r=>r.id===id),row=before||{id:ID('client'),stage:'inquiry',createdAt:Date.now(),consult167:{}};
  const f=(key,label,type='text',options=null,required=false,cls='')=>field(key,label,row[key],type,options,required).replace('<label>',`<label class="${cls}" data-client-field="${key}">`);
  const extras=!!(row.additionalMajors||row.doubleMajor||row.minor);
  const body=`<div class="c167-client-form">
    <div class="c167-client-column">
      <fieldset class="c167-client-personal"><legend>01 · 개인 정보</legend><div class="c167-client-personal-grid">
        ${f('name','이름','text',null,true,'third')}${f('birthYear','출생년도','number',null,false,'third')}${f('gender','성별','text',{'':'미입력',female:'여성',male:'남성'},false,'third')}
        ${f('phone','연락처','tel',null,false,'half')}${f('email','이메일','email',null,false,'half')}
      </div></fieldset>
      <fieldset class="c167-client-spec"><legend>03 · 보유 및 예정 스펙</legend><div class="c167-client-pairs">
        ${f('languageSpec','어학','textarea')}${f('certifications','관련 자격증','textarea')}
        ${f('activities','관련 활동','textarea',null,false,'wide')}${f('researchExperience','연구 경험','textarea',null,false,'wide')}${f('outputs','논문 · 학회 · 발표 · 포트폴리오','textarea',null,false,'wide')}
      </div></fieldset>
    </div>
    <div class="c167-client-column">
      <fieldset class="c167-client-education"><legend>02 · 학력 및 목표</legend>
        <div class="c167-client-school-row">${f('currentSchool','학교')}${f('currentMajor','주전공')}<button type="button" data-client-major-toggle aria-expanded="${extras}" aria-controls="c167ClientMajorExtras">${extras?'− 전공 접기':'+ 전공 추가'}</button></div>
        <div class="c167-client-major-extras" id="c167ClientMajorExtras" ${extras?'':'hidden'}>${f('additionalMajors','추가 전공')}${f('doubleMajor','복수전공')}${f('minor','부전공')}</div>
        <div class="c167-client-academic-meta"><div class="c167-client-gpa">${f('gpa','학점','number')}${f('gpaScale','만점','number')}</div>${f('universityYears','몇 년제 대학')}${f('militaryStatus','군필 여부')}</div>
        <div class="c167-client-pairs">${f('targetUniversity','희망 대학원 · 여러 곳 가능','textarea')}${f('targetMajor','희망 전공 · 여러 개 가능','textarea')}</div>
        <div class="c167-client-third-row">${f('degree','희망 과정','text',{'':'미입력',...DEGREE})}${f('applicationYear','희망 학년도','number')}${f('applicationSemester','희망 학기','text',{'':'미입력',...SEMESTER})}</div>
        <div class="c167-client-pairs">${f('advisorNames','지원 희망 지도교수 · 여러 명 가능','textarea')}${f('topic','관심 분야 · 연구 주제','textarea')}</div>
      </fieldset>
      <fieldset class="c167-client-inquiry"><legend>04 · 기타 문의</legend>${f('inquiry','기타 문의','textarea')}</fieldset>
    </div>
  </div><details class="c167-client-legacy"><summary>진행 상태 · 기존 상담 메모</summary><div class="c167-form-grid">${field('status','진행 상태',before?.consult167.status||'active','text',M.STATUS)}${f('nextSession','기존 다음 상담','datetime-local')}${f('note','이전 고객 메모 · 내부 원문','textarea')}</div></details>`;
  const dialog=modal(before?'고객 정보 수정':'고객 추가',body,async(form,d,requestId)=>{
    const v=vals(form),gpa=Number(v.gpa)||0,scale=Number(v.gpaScale)||0;if(gpa&&scale&&gpa>scale)throw Error('학점은 만점보다 클 수 없습니다.');
    const next=M.client({...row,...v,birthYear:Number(v.birthYear)||0,gpa,gpaScale:scale,applicationYear:Number(v.applicationYear)||0,advisorNames:v.advisorNames.split(/\n/).map(x=>x.trim()).filter(Boolean),updatedAt:Date.now()});
    next.consult167.status=v.status;next.contact=[v.phone,v.email].filter(Boolean).join(' · ');next.university=v.targetUniversity;next.major=v.targetMajor;next.institution=v.currentSchool;next.program=v.currentMajor;
    await commit('consultingClients',next,before,requestId);state.clientId=next.id;state.menu='clients';state.status=v.status;
  },'저장',{maxWidth:1320,className:'c167-client-dialog'});
  dialog?.querySelector('[data-client-major-toggle]')?.addEventListener('click',event=>{const panel=dialog.querySelector('#c167ClientMajorExtras');panel.hidden=!panel.hidden;event.currentTarget.setAttribute('aria-expanded',String(!panel.hidden));event.currentTarget.textContent=panel.hidden?'+ 전공 추가':'− 전공 접기'});
 }
 function editTarget(id=''){const c=selected(),before=clone(c),row=c.consult167.targets.find(r=>r.id===id)||{id:ID('target'),createdAt:Date.now()},checks=['eligibility','research','language','advisor'];modal(id?'지원 후보 수정':'지원 후보 추가',`<div class="c167-form-grid">${[['university','대학원'],['department','학과'],['degree','학위 과정'],['advisor','지도교수·연구실'],['researchDirection','연구 방향','textarea'],['priority','우선순위'],['deadline','지원 마감','date'],['applicationStatus','연락·지원 상태'],['sourceUrl','출처 URL','url'],['checkedAt','확인일','date'],['rationale','판단 근거','textarea']].map(([k,l,t])=>field(k,l,row[k],t)).join('')}${field('result','결과',row.result||'pending','text',M.RESULTS)}</div><fieldset><legend>근거 확인</legend>${checks.map(k=>field(k+'Status',({eligibility:'지원자격',research:'연구 경험 적합성',language:'어학',advisor:'지도교수'})[k],row.checks?.[k]?.status||'unknown','text',{unknown:'미확인',verified:'확인',supplement:'보완'})+field(k+'Evidence','판단 근거',row.checks?.[k]?.evidence||'','textarea')).join('')}</fieldset>`,async(form,d,req)=>{const v=vals(form),next={...row,...v,checks:{...row.checks},updatedAt:Date.now()};for(const k of checks){next.checks[k]={status:v[k+'Evidence'].trim()?v[k+'Status']:'unknown',evidence:v[k+'Evidence']};delete next[k+'Status'];delete next[k+'Evidence']}const copy=clone(before),i=copy.consult167.targets.findIndex(r=>r.id===next.id);i<0?copy.consult167.targets.push(next):copy.consult167.targets[i]=next;await commit('consultingClients',copy,before,req)})}
 function editTask(id='',seed={}){const before=data.consultingTasks.find(r=>r.id===id),row=before||{id:ID('task'),clientId:state.clientId,createdAt:Date.now(),status:'waiting',assignee:'client',...seed};modal(before?'과업 수정':'과업 추가',`<div class="c167-form-grid">${field('title','과업 제목',row.title,'text',null,true)}${field('stage','관련 단계',row.stage||'intake','text',M.STAGES)}${field('assignee','담당',row.assignee,'text',{client:'고객',consultant:'컨설턴트'})}${field('dueDate','마감',row.dueDate,'date')}${field('priority','우선순위',row.priority||'보통','text',{낮음:'낮음',보통:'보통',높음:'높음'})}${field('status','상태',row.status,'text',TASK_STATUS)}${field('description','상세 요청',row.description,'textarea')}${field('acceptanceCriteria','완료 조건',row.acceptanceCriteria,'textarea')}${field('result','결과',row.result,'textarea')}</div>`,async(form,d,req)=>{const v=vals(form),next={...row,...v,done:v.status==='done',legacyAssignee:'',legacyStatus:'',updatedAt:Date.now()};if(seed.sessionId||seed.documentId){next.sourceKey=[seed.sessionId?'session:'+seed.sessionId:'document:'+seed.documentId,v.assignee,v.title.trim().toLowerCase()].join('|');const duplicate=data.consultingTasks.find(t=>t.clientId===next.clientId&&t.sourceKey===next.sourceKey);if(duplicate)throw Error('이 원문에서 같은 담당·제목의 과업이 이미 생성되었습니다. 기존 과업을 수정하세요.')}await commit('consultingTasks',next,before,req);state.tab='tasks'})}
 function editSession(id=''){const before=data.consultingSessions.find(r=>r.id===id),row=before||{id:ID('session'),clientId:state.clientId,createdAt:Date.now(),date:'',status:'scheduled'};modal(before?'상담 기록 수정':'상담 추가',`<div class="c167-form-grid">${field('title','상담 제목',row.title,'text',null,true)}${field('date','상담 일시',row.date,'datetime-local',null,true)}${field('status','상태',row.status,'text',SESSION_STATUS)}${field('method','방식',row.method||'')}${field('stage','관련 단계',row.stage||'intake','text',M.STAGES)}${[['purpose','상담 목적'],['discussion','논의 내용'],['decisions','결정 사항'],['clientActions','고객 할 일'],['consultantActions','컨설턴트 할 일'],['clientFeedback','고객에게 전달할 피드백'],['internalNote','내부 메모']].map(([k,l])=>field(k,l,row[k]||(k==='discussion'?row.summary:''),'textarea')).join('')}${field('nextDate','다음 일정',row.nextDate,'datetime-local')}</div>`,async(form,d,req)=>{const v=vals(form),next={...row,...v,summary:v.discussion,originalDate:row.originalDate||row.date||v.date,history:[...(row.history||[])],updatedAt:Date.now()};if(before)next.history.push({changedAt:Date.now(),date:row.date,status:row.status,revision:M.rev(row),snapshot:{title:row.title,purpose:row.purpose,discussion:row.discussion||row.summary,decisions:row.decisions,clientActions:row.clientActions,consultantActions:row.consultantActions,clientFeedback:row.clientFeedback,internalNote:row.internalNote,nextDate:row.nextDate}});await commit('consultingSessions',next,before,req)})}
 function editNote(id=''){const c=selected(),before=clone(c),row=c.consult167.internalNotes.find(n=>n.id===id)||{id:ID('note'),createdAt:Date.now()};modal('내부 메모',field('text','메모',row.text,'textarea',null,true),async(form,d,req)=>{const copy=clone(before),next={...row,text:form.get('text'),updatedAt:Date.now()},i=copy.consult167.internalNotes.findIndex(n=>n.id===row.id);i<0?copy.consult167.internalNotes.push(next):copy.consult167.internalNotes[i]=next;await commit('consultingClients',copy,before,req)})}
 function editFile(id='',newVersion=false){const previous=data.consultingFiles.find(r=>r.id===id),before=newVersion?null:previous,base=before||{id:ID('file'),clientId:previous?.clientId||state.clientId,documentId:previous?.documentId||ID('document'),version:previous?Math.max(...data.consultingFiles.filter(r=>r.documentId===previous.documentId).map(r=>r.version))+1:1,createdAt:Date.now(),name:previous?.name||'',documentType:previous?.documentType||'proposal',status:'pending'},startingOwner=owner;let upload=null;const dialog=modal(newVersion?'문서 새 버전':before?'문서·피드백':'문서 추가',`<div class="c167-form-grid">${field('name','문서명',base.name,'text',null,true)}${field('documentType','유형',base.documentType,'text',FILE_TYPES)}${field('status','검토 상태',base.status,'text',FILE_STATUS)}${field('textContent','문서 텍스트',base.textContent,'textarea')}${field('customerFeedback','고객용 피드백',base.customerFeedback,'textarea')}${field('internalNote','내부 메모',base.internalNote,'textarea')}${!before?'<label>실제 첨부 · 최대25MB<input name="attachment" type="file"></label>':''}</div>${base.fileId?`<button type="button" data-download>첨부 다운로드</button><p>${esc(base.name)} · ${Math.ceil((base.size||0)/1024)}KB</p>`:''}<p>버전 v${base.version}</p>${base.feedbackHistory?.length?`<details><summary>버전별 피드백 변경 이력</summary>${base.feedbackHistory.map(h=>dl({일시:new Date(h.createdAt).toLocaleString('ko-KR'),고객피드백:h.customerFeedback,내부메모:h.internalNote})).join('')}</details>`:''}`,async(form,d,req)=>{const v=vals(form),file=form.get('attachment');if(!before&&!v.textContent.trim()&&!file?.size)throw Error('문서 텍스트 또는 실제 파일을 추가하세요.');assertOwner(startingOwner);if(file?.size&&!upload){if(file.size>25*1024*1024)throw Error('첨부는25MB 이하여야 합니다.');upload=await window.AiderDearFirebase.uploadPrivateMedia(file,'consult-document-v167');assertOwner(startingOwner)}const next={...base,...v,updatedAt:Date.now(),feedbackHistory:[...(base.feedbackHistory||[])]};if(upload)Object.assign(next,{fileId:upload.id,storageScope:'private',ownerEmail:bridge().identity().email,type:upload.mimeType,size:upload.size,originalFileName:upload.name});if(before&&(v.customerFeedback!==base.customerFeedback||v.internalNote!==base.internalNote||v.status!==base.status))next.feedbackHistory.push({createdAt:Date.now(),customerFeedback:base.customerFeedback,internalNote:base.internalNote,status:base.status});await commit('consultingFiles',next,before,req)});if(before){const original=dialog?.querySelector("[name=textContent]");if(original)original.readOnly=true}dialog?.querySelector('[data-download]')?.addEventListener('click',()=>downloadFile(base));}
 async function downloadFile(row){try{assertOwner();const before=owner,blob=row.storageScope==='paper-task'?await window.AiderDearFirebase.readPaperTaskMedia(row.fileId):await window.AiderDearFirebase.readPrivateMedia(row.fileId);assertOwner(before);download(blob,row.originalFileName||row.name||'document')}catch(e){notify(e.message||'파일을 열지 못했습니다.')}}
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
 function deliveryMarkup(row){return `<article class="c167-delivery"><header><h2>${esc(row.clientName)} · 컨설팅 전달본</h2><time>${new Date(row.createdAt).toLocaleString('ko-KR')}</time></header>${row.sections.map(s=>`<section><h3>${esc(s.title)}</h3>${dl(s.fields)}</section>`).join('')}</article>`}
 function delivery(c){const before=clone(c),options=M.selectionRows(data,c),meta={id:ID('delivery'),createdAt:Date.now(),createdBy:owner};let preview=M.delivery(data,c.id,['goals'],meta);const dialog=modal('고객 전달본',`<fieldset class="c167-delivery-options"><legend>포함할 항목</legend>${options.map(o=>`<label><input type="checkbox" name="include" value="${esc(o.key)}" ${o.key==='goals'?'checked':''}><span>${esc(o.label)}</span></label>`).join('')}</fieldset><div data-delivery-preview>${deliveryMarkup(preview)}</div><details><summary>저장된 전달본 ${c.consult167.deliveries.length}</summary>${c.consult167.deliveries.map(r=>`<button type="button" data-delivery-old="${esc(r.id)}">${new Date(r.createdAt).toLocaleString('ko-KR')} · ${esc(r.id.slice(-6))}</button>`).join('')}</details>`,async(form,d,req)=>{const chosen=form.getAll('include');if(!chosen.length)throw Error('포함할 항목을 선택하세요.');const snapshot=clone(preview),copy=clone(before);if(!copy.consult167.deliveries.some(r=>r.id===snapshot.id))copy.consult167.deliveries.push(snapshot);await commit('consultingClients',copy,before,req);setTimeout(()=>showDelivery(snapshot),0)},'전달본 저장');dialog?.addEventListener('change',()=>{preview=M.delivery(data,c.id,[...dialog.querySelectorAll('[name=include]:checked')].map(e=>e.value),meta);dialog.querySelector('[data-delivery-preview]').innerHTML=deliveryMarkup(preview)});dialog?.querySelectorAll('[data-delivery-old]').forEach(b=>b.onclick=()=>{const saved=c.consult167.deliveries.find(r=>r.id===b.dataset.deliveryOld);showDelivery(saved,true)})}
 function showDelivery(row,replace=false){if(replace&&activeDialog){if(dirty&&!confirm('저장하지 않은 전달본 선택을 닫을까요?'))return;activeDialog.close();activeDialog.remove();activeDialog=null;dirty=false}const dialog=modal('저장된 전달본',deliveryMarkup(row)+`<div class="c167-actions"><button type="button" data-txt>TXT 다운로드</button><button type="button" data-print>인쇄·PDF</button></div>`);dialog?.querySelector('[data-txt]').addEventListener('click',()=>download(new Blob(['\uFEFF'+M.deliveryText(row)],{type:'text/plain;charset=utf-8'}),row.clientName+'-전달본.txt'));dialog?.querySelector('[data-print]').addEventListener('click',()=>{const popup=window.open('','_blank');if(!popup){notify('인쇄 창을 허용해 주세요.');return}popup.opener=null;popup.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${esc(row.clientName)} 전달본</title><style>@page{size:A4;margin:18mm}body{font:14px/1.7 Arial,"Malgun Gothic",sans-serif;color:#222}h2{font-size:22px}section{break-inside:auto;margin:20px 0}dl>div{margin:10px 0}dt{font-weight:bold}dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}button{display:none}</style></head><body>${deliveryMarkup(row)}</body></html>`);popup.document.close();popup.addEventListener('load',()=>popup.print(),{once:true})})}
 function input(event){const key=event.target.dataset.filter;if(!key)return;state[key]=event.target.value;if(['query','year'].includes(key)&&['clients','closed'].includes(state.menu)){const list=$('.c167-client-list');if(list)list.innerHTML=clientList()}}
 function change(event){const key=event.target.dataset.filter;if(key){state[key]=event.target.value;render()}}
 async function click(event){const b=event.target.closest('[data-c167]');if(!b||saving)return;const op=b.dataset.c167,id=b.dataset.id;try{assertOwner();if(op==='menu'){rememberScroll();state.menu=id;state.clientId='';state.result='';render()}else if(op==='refresh'){await bridge().refresh?.();render()}else if(op==='intake')bridge().openIntake();else if(op==='admissions')bridge().openAdmissions();else if(op==='analysis')bridge().legacyAnalysis(id);else if(op==='select'||op==='jump'){rememberScroll();state.clientId=id;state.menu='clients';state.tab=b.dataset.tab||'overview';render();if(b.dataset.record)document.getElementById('c167-row-'+b.dataset.record)?.scrollIntoView({block:'start'})}else if(op==='back'){state.clientId='';render()}else if(op==='tab'){rememberScroll();state.tab=id;render()}else if(op==='client-new')editClient();else if(op==='client-edit')editClient(id);else if(op==='target-new')editTarget();else if(op==='target-edit')editTarget(id);else if(op==='task-new')editTask();else if(op==='task-edit')editTask(id);else if(op==='session-new')editSession();else if(op==='session-edit')editSession(id);else if(op==='note-new')editNote();else if(op==='note-edit')editNote(id);else if(op==='file-new')editFile();else if(op==='file-view')editFile(id);else if(op==='file-version')editFile(id,true);else if(op==='file-download')downloadFile(data.consultingFiles.find(r=>r.id===id));else if(op==='delivery')delivery(selected());else if(op==='calendar-mode'){state.calendarMode=state.calendarMode==='list'?'grid':'list';render()}else if(op==='archive'||op==='stage'){const before=selected(),next=clone(before);if(op==='archive'){if(!confirm(next.consult167.status==='closed'?'고객을 진행 상태로 복원할까요?':'기존 기록을 보존하고 고객을 보관할까요?'))return;next.consult167.status=next.consult167.status==='closed'?'active':'closed'}else{next.consult167.stage=id;next.consult167.stageNeedsReview=false}await commit('consultingClients',next,before);render()}else if(op==='task-toggle'){const before=data.consultingTasks.find(r=>r.id===id),next={...before,status:before.status==='done'?'waiting':'done',done:before.status!=='done',updatedAt:Date.now()};await commit('consultingTasks',next,before);render()}else if(op==='follow-session'){const row=data.consultingSessions.find(r=>r.id===id);editTask('',{title:row.clientActions||'',description:row.clientFeedback||'',sessionId:row.id,sourceRevision:M.rev(row),stage:row.stage})}else if(op==='follow-file'){const row=data.consultingFiles.find(r=>r.id===id);state.clientId=row.clientId;editTask('',{title:row.name+' 보완',description:row.customerFeedback,documentId:row.documentId,documentVersionId:row.id,sourceRevision:M.rev(row)})}else if(op==='source-session'||op==='source-file'){state.tab=op==='source-session'?'sessions':'files';render();document.getElementById('c167-row-'+id)?.scrollIntoView({block:'start'})}}catch(error){notify(error?.message||'처리하지 못했습니다.')}}
 window.AiderConsultV167=Object.freeze({render,calendar:()=>M.calendar(M.normalize(bridge()?.snapshot?.()||{}))});
})();
