function eventAuthorNameV113(row){
  const raw=row?.authorName||row?.authorEmail||'';
  return String(raw).trim()||'작성자 정보 없음';
}
function recordTypeLabelV113(type){return({daily:'일상',moment:'순간',people:'사람',place:'장소',idea:'아이디어',celebration:'기념'})[type]||'기록'}

const RECORD_COLORS_V125=['#43240F','#F8F6DF','#E1AD01','#B83700','#3D4C1C'];
let recordPageV125=1;
const RECORD_PAGE_SIZE_V125=6;

recordHTML=function(){
  let rows=recordsV111(),albums=albumsV111(),album=albums.find(x=>String(x.id)===String(selectedAlbum));
  if(recordSortV111==='color')rows=rows.slice().sort((a,b)=>RECORD_COLORS_V125.indexOf(RECORD_COLORS_V125.includes(a.color)?a.color:'#F8F6DF')-RECORD_COLORS_V125.indexOf(RECORD_COLORS_V125.includes(b.color)?b.color:'#F8F6DF')||String(b.date||'').localeCompare(String(a.date||'')));
  const totalPages=Math.max(1,Math.ceil(rows.length/RECORD_PAGE_SIZE_V125));recordPageV125=Math.min(Math.max(1,recordPageV125),totalPages);const pageRows=rows.slice((recordPageV125-1)*RECORD_PAGE_SIZE_V125,recordPageV125*RECORD_PAGE_SIZE_V125);
  return `<section class="record-head record-head-v113"><div><span class="section-label">YOUR MOMENTS</span><h2>Record${album?` · ${esc(album.name||album.title||'Album')}`:''}</h2></div><div class="event-title-tools-v113"><button class="album-btn" type="button" data-open-albums>▧ <span>Album</span></button><input id="recordDateV111" type="date" value="${recordDateV111}" aria-label="날짜 검색"><select id="recordSortV111" aria-label="기록 정렬"><option value="recent" ${recordSortV111==='recent'?'selected':''}>최근순</option><option value="oldest" ${recordSortV111==='oldest'?'selected':''}>오래된순</option><option value="color" ${recordSortV111==='color'?'selected':''}>색상별</option></select><button class="primary" type="button" data-event-create="record">＋ 기록</button></div></section><div class="record-grid event-record-grid-v111">${pageRows.length?pageRows.map((r,i)=>`<article class="record-card record-card-v125" style="--record-color:${esc(RECORD_COLORS_V125.includes(r.color)?r.color:'#F8F6DF')}"><button type="button" class="record-card-open-v125" data-record-edit="${esc(r.id)}"><div class="record-visual tone${i%6}">${eventMediaMarkupV111(r,esc(r.emoji||'✎'))}<small>${esc(r.date||today())}${r.time?` · ${esc(r.time)}`:''}</small></div><div class="record-copy"><b>${esc(r.title||'Record')}</b><p>${esc(r.body||r.memo||r.note||'기억하고 싶은 순간을 기록하세요.')}</p><div class="record-meta"><span>${esc(albums.find(a=>String(a.id)===String(r.albumId||r.folderId))?.name||'Daily')}</span><span>${esc(recordTypeLabelV113(r.recordType))}${r.location?` · ${esc(r.location)}`:''}</span></div></div></button>${r.favorite?'<span class="record-favorite-v125" aria-label="즐겨찾기">♡</span>':''}</article>`).join(''):'<div class="event-empty-v111">＋ 기록을 눌러 첫 순간을 남겨보세요.</div>'}</div>${rows.length>RECORD_PAGE_SIZE_V125?`<nav class="record-pagination-v125" aria-label="기록 페이지"><button type="button" data-record-page-v125="${recordPageV125-1}" ${recordPageV125<=1?'disabled':''}>이전</button><b>${recordPageV125} / ${totalPages}</b><button type="button" data-record-page-v125="${recordPageV125+1}" ${recordPageV125>=totalPages?'disabled':''}>다음</button></nav>`:''}`;
};

archiveHTMLV111=function(){
  let rows=eventReviewsV111().filter(x=>x.category!=='travel');
  if(archiveCategoryV111!=='all')rows=rows.filter(x=>x.category===archiveCategoryV111);
  if(archiveWishlistV111)rows=rows.filter(x=>x.experienceStatus==='want');
  rows.sort((a,b)=>archiveSortV111==='rating'?(Number(b.rating)||0)-(Number(a.rating)||0):String(b.date||'').localeCompare(String(a.date||'')));
  return `<section class="archive archive-v111"><div class="event-titleline-v113"><div><span class="section-label">MY CULTURE</span><h2>Archive</h2></div><div class="event-title-tools-v113"><select id="archiveCategoryV113" aria-label="아카이브 분류">${[['all','ALL'],['movie','MOVIE'],['performance','PERFORMANCE'],['book','BOOK'],['music','MUSIC'],['place','PLACE']].map(([k,l])=>`<option value="${k}" ${archiveCategoryV111===k?'selected':''}>${l}</option>`).join('')}</select><button type="button" data-archive-wishlist class="${archiveWishlistV111?'primary':''}">♡ WISH</button><select id="archiveSortV111" aria-label="아카이브 정렬"><option value="date" ${archiveSortV111==='date'?'selected':''}>최신순</option><option value="rating" ${archiveSortV111==='rating'?'selected':''}>별점순</option></select><button class="primary" type="button" data-event-create="archive">＋ 기록</button></div></div><div class="archive-grid-v111">${rows.length?rows.map(r=>`<button type="button" class="event-archive-card-v111" data-review-edit="${esc(r.id)}"><div class="event-archive-media-v111">${eventMediaMarkupV111(r,eventCategoryEmojiV111(r.category))}</div><div class="event-archive-copy-v111"><small>${eventCategoryLabelV111(r.category)} · ${esc(String(r.date||'').replaceAll('-','.'))}</small><b>${esc(r.title||'제목 없음')}</b><span>${eventStarsV111(r.rating)}</span>${r.experienceStatus==='want'?'<em>♡ WANT LIST</em>':''}<p>${esc(r.oneLine||r.review||r.place||r.creator||'')}</p></div></button>`).join(''):'<div class="event-empty-v111">좋아한 작품이나 가고 싶은 장소를 기록해보세요.</div>'}</div></section>`;
};

function eventPhotoFieldV113(row,preview){
  return `<div class="event-form-section-title-v113"><b>사진과 기록</b><span>기억을 더 선명하게 남겨보세요.</span></div><label class="wide event-photo-pick-v113">사진<input id="eventPhotoV111" type="file" accept="image/*"></label><div class="event-editor-preview-v111" id="eventPreviewV111">${preview?`<img src="${preview}" alt="">`:eventMediaMarkupV111(row,'사진을 선택하면 여기에 표시됩니다.')}</div>`;
}
function recordEditorHTMLV113(row,id,editing,preview){
  const author=editing?` · 작성 ${eventAuthorNameV113(row)}`:' · 새로운 순간';
  const icons=[['✎','일상 메모'],['◎','기억할 순간'],['▧','사진 기록'],['♡','사람'],['⌖','장소'],['☆','기념'],['☕','카페'],['✦','아이디어']];
  const selectedColor=RECORD_COLORS_V125.includes(row?.color)?row.color:'#F8F6DF';
  return `<div class="event-editor-overlay-v111" data-event-editor-overlay><section class="event-editor-sheet-v111 event-editor-sheet-v113"><header class="event-editor-head-v111"><div><small>RECORD${esc(author)}</small><h2>${editing?'기록 수정':'새 기록'}</h2></div><button type="button" data-event-editor-close>×</button></header><form id="eventEditorFormV111" class="event-editor-form-v111 event-purpose-form-v113" data-kind="record" data-id="${esc(id||'')}"><div class="event-form-intro-v113"><i>${esc(row?.emoji||'✎')}</i><div><b>오늘의 장면을 남겨보세요</b><p>언제, 어디서, 누구와 함께했는지 기록할 수 있어요.</p></div></div><div class="event-form-section-title-v113"><b>기본 정보</b><span>기록을 다시 찾기 위한 정보예요.</span></div><label>제목<input name="title" maxlength="80" value="${esc(row?.title||'')}" placeholder="기억할 장면의 제목" required></label><label>날짜<input name="date" type="date" value="${esc(row?.date||today())}"></label><label>시간<input name="time" type="time" value="${esc(row?.time||'')}"></label><label>기록 종류<select name="recordType">${[['daily','일상'],['moment','순간'],['people','사람'],['place','장소'],['idea','아이디어'],['celebration','기념']].map(([k,l])=>`<option value="${k}" ${k===(row?.recordType||'daily')?'selected':''}>${l}</option>`).join('')}</select></label><label>앨범<select name="albumId"><option value="">Daily</option>${albumsV111().map(a=>`<option value="${esc(a.id)}" ${String(a.id)===String(row?.albumId||row?.folderId||'')?'selected':''}>${esc(a.name||a.title||'Album')}</option>`).join('')}</select></label><label>아이콘<select name="emoji">${icons.map(([icon,label])=>`<option value="${icon}" ${icon===(row?.emoji||'✎')?'selected':''}>${icon} ${label}</option>`).join('')}</select></label><label>장소<input name="location" maxlength="100" value="${esc(row?.location||'')}" placeholder="카페, 공원, 집"></label><label>함께한 사람<input name="people" maxlength="120" value="${esc(row?.people||'')}" placeholder="이름 또는 관계"></label><label class="wide">그때의 기분<input name="mood" maxlength="100" value="${esc(row?.mood||'')}" placeholder="편안함, 설렘, 뿌듯함"></label><fieldset class="wide record-options-v125"><legend>기록 색상</legend><div class="record-color-picker-v125">${RECORD_COLORS_V125.map((color,index)=>`<label style="--record-swatch:${color}"><input type="radio" name="color" value="${color}" ${selectedColor===color?'checked':''}><span>${String(index+1).padStart(2,'0')}</span></label>`).join('')}</div><label class="record-favorite-toggle-v125"><input type="checkbox" name="favorite" ${row?.favorite?'checked':''}><span>즐겨찾기 앨범에도 표시</span></label></fieldset>${eventPhotoFieldV113(row,preview)}<label class="wide">기억할 내용<textarea name="body" maxlength="1600" placeholder="무슨 일이 있었고 무엇이 기억에 남았나요?">${esc(row?.body||row?.memo||row?.note||'')}</textarea></label><div class="event-editor-actions-v111">${editing?'<button type="button" class="delete" data-event-delete>삭제</button>':''}<button type="button" data-event-editor-close>취소</button><button type="submit" class="save">저장</button></div></form></section></div>`;
}
const ARCHIVE_FIELD_CONFIG_V125={
  movie:{title:'영화 제목',creator:['감독','감독 이름'],place:['관람 방법','극장, OTT, 함께 본 사람 등'],genre:['출연·배우','기억하고 싶은 배우나 배역'],highlight:['기억할 장면·대사','인상 깊은 장면이나 대사']},
  performance:{title:'공연·전시 이름',creator:['아티스트·출연진','연출, 작가, 출연진'],place:['공연장·전시장','공간 이름과 지역'],genre:['좌석·관람 위치','좌석, 전시장 구역'],highlight:['프로그램·작품','인상 깊었던 순서나 작품']},
  book:{title:'책 제목',creator:['저자','저자 이름'],place:['읽은 장소·방식','종이책, 전자책, 오디오북'],genre:['출판사·번역가','출판사 또는 번역가'],highlight:['기억할 문장·범위','문장, 페이지, 읽은 기간']},
  music:{title:'곡·앨범·공연 제목',creator:['아티스트','가수, 연주자, 작곡가'],place:['들은 장소','공연장 또는 들었던 공간'],genre:['트랙·세트리스트','가장 좋았던 곡'],highlight:['함께한 순간','상황, 사람, 플레이리스트']},
  place:{title:'장소 이름',creator:['추천한 사람·출처','친구, 매거진, SNS 등'],place:['주소·위치','지역, 주소 또는 지도 메모'],genre:['방문 정보','운영시간, 예약, 이동 방법'],highlight:['기억할 포인트','좋았던 점, 다시 갈 이유']}
};
function archiveFieldConfigV125(category){return ARCHIVE_FIELD_CONFIG_V125[category]||ARCHIVE_FIELD_CONFIG_V125.movie}
function archivePurposeFieldsV113(row){
  const category=row?.category||eventEditorV111?.category||'movie',cfg=archiveFieldConfigV125(category);
  return `<label>분류<select name="category">${[['movie','영화'],['performance','공연·전시'],['book','책'],['music','음악'],['place','장소']].map(([k,l])=>`<option value="${k}" ${category===k?'selected':''}>${l}</option>`).join('')}</select></label><label>상태<select name="experienceStatus"><option value="done" ${row?.experienceStatus!=='want'?'selected':''}>감상·방문 완료</option><option value="want" ${row?.experienceStatus==='want'?'selected':''}>♡ 보고 싶음</option></select></label><label data-archive-field-v125="title"><span>제목</span><input name="title" maxlength="100" value="${esc(row?.title||'')}" placeholder="${esc(cfg.title)}" required></label><label>감상 날짜<input name="date" type="date" value="${esc(row?.date||today())}"></label><label data-archive-field-v125="creator"><span>${esc(cfg.creator[0])}</span><input name="creator" maxlength="100" value="${esc(row?.creator||'')}" placeholder="${esc(cfg.creator[1])}"></label><label data-archive-field-v125="place"><span>${esc(cfg.place[0])}</span><input name="place" maxlength="120" value="${esc(row?.place||'')}" placeholder="${esc(cfg.place[1])}"></label><label data-archive-field-v125="genre"><span>${esc(cfg.genre[0])}</span><input name="genre" maxlength="100" value="${esc(row?.genre||row?.detailA||'')}" placeholder="${esc(cfg.genre[1])}"></label><label>함께한 사람<input name="companions" maxlength="120" value="${esc(row?.companions||'')}" placeholder="혼자 또는 함께한 사람"></label><label>별점<select name="rating">${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${Number(row?.rating||0)===n?'selected':''}>${n?eventStarsV111(n):'미평가'}</option>`).join('')}</select></label><label data-archive-field-v125="highlight"><span>${esc(cfg.highlight[0])}</span><input name="highlight" maxlength="180" value="${esc(row?.highlight||row?.detailB||'')}" placeholder="${esc(cfg.highlight[1])}"></label>`;
}
function configureArchiveFieldsV125(category){const form=$('#eventEditorFormV111'),cfg=archiveFieldConfigV125(category);if(!form||form.dataset.kind!=='review'||category==='travel')return;for(const [name,value] of Object.entries({title:['제목',cfg.title],creator:cfg.creator,place:cfg.place,genre:cfg.genre,highlight:cfg.highlight})){const label=$(`[data-archive-field-v125="${name}"]`,form);if(!label)continue;const span=$('span',label),input=$(`[name="${name}"]`,label);if(span)span.textContent=value[0];if(input)input.placeholder=value[1]}}
function travelPurposeFieldsV113(row,type){
  const plan=type==='plan',food=type==='food',place=type==='place',activity=type==='activity';
  return `<input type="hidden" name="category" value="travel"><label>기록 종류<select name="travelType">${[['plan','여행 계획'],['place','장소'],['food','음식'],['activity','놀거리']].map(([k,l])=>`<option value="${k}" ${type===k?'selected':''}>${l}</option>`).join('')}</select></label><label>여행지 폴더<select name="folderId">${travelFoldersV111().map(f=>`<option value="${esc(f.id)}" ${String(f.id)===String(row?.folderId||travelFolderV111||'trip-default')?'selected':''}>${esc(f.name)}</option>`).join('')}</select></label><label>제목<input name="title" maxlength="100" value="${esc(row?.title||'')}" placeholder="${plan?'여행 계획 이름':food?'식당 또는 메뉴':activity?'체험 또는 활동':'방문할 장소'}" required></label><label>${plan?'출발일':'날짜'}<input name="date" type="date" value="${esc(row?.date||today())}"></label><label>${plan?'도착일':'시간'}${plan?`<input name="endDate" type="date" value="${esc(row?.endDate||'')}">`:`<input name="time" type="time" value="${esc(row?.time||'')}">`}</label><label>${food?'식당·지역':activity?'활동 장소':'장소'}<input name="place" maxlength="120" value="${esc(row?.place||'')}" placeholder="장소 이름"></label><label>주소·위치<input name="address" maxlength="180" value="${esc(row?.address||'')}" placeholder="주소 또는 찾아가는 방법"></label>${plan?`<label>이동 수단<input name="transport" maxlength="120" value="${esc(row?.transport||row?.detailA||'')}" placeholder="항공, 기차, 렌터카"></label><label>숙소<input name="lodging" maxlength="120" value="${esc(row?.lodging||row?.detailB||'')}" placeholder="숙소 또는 지역"></label>`:food?`<label>먹고 싶은 메뉴<input name="menu" maxlength="160" value="${esc(row?.menu||row?.detailA||'')}" placeholder="대표 메뉴, 주문할 음식"></label><label>예약 정보<input name="reservation" maxlength="160" value="${esc(row?.reservation||'')}" placeholder="예약 시간 또는 번호"></label>`:place?`<label>운영 시간<input name="openHours" maxlength="120" value="${esc(row?.openHours||row?.detailA||'')}" placeholder="운영·입장 시간"></label><label>놓치지 않을 것<input name="highlight" maxlength="180" value="${esc(row?.highlight||row?.detailB||'')}" placeholder="볼거리, 포토 스팟"></label>`:`<label>예약 정보<input name="reservation" maxlength="160" value="${esc(row?.reservation||row?.detailA||'')}" placeholder="티켓, 예약 시간"></label><label>준비물<input name="preparation" maxlength="180" value="${esc(row?.preparation||row?.detailB||'')}" placeholder="복장, 준비물, 주의 사항"></label>`}<label>동행<input name="companions" maxlength="120" value="${esc(row?.companions||'')}" placeholder="혼자 또는 함께할 사람"></label><label>예상·사용 비용<input name="cost" inputmode="numeric" maxlength="40" value="${esc(row?.cost||'')}" placeholder="금액"></label><label>별점<select name="rating">${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${Number(row?.rating||0)===n?'selected':''}>${n?eventStarsV111(n):'미평가'}</option>`).join('')}</select></label><label>상태<select name="experienceStatus"><option value="want" ${row?.experienceStatus==='want'||!row?'selected':''}>계획·하고 싶음</option><option value="done" ${row?.experienceStatus==='done'?'selected':''}>다녀옴·완료</option></select></label>`;
}
function reviewEditorHTMLV113(row,id,editing,preview){
  const cat=row?.category||eventEditorV111?.category||'movie',travel=cat==='travel',type=row?.travelType||eventEditorV111?.travelType||'plan',author=editing?` · 작성 ${eventAuthorNameV113(row)}`:'';
  return `<div class="event-editor-overlay-v111" data-event-editor-overlay><section class="event-editor-sheet-v111 event-editor-sheet-v113"><header class="event-editor-head-v111"><div><small>${travel?'TRAVEL':'ARCHIVE'}${esc(author)}</small><h2>${editing?(travel?'여행 기록 수정':'아카이브 수정'):(travel?'여행 기록 추가':'감상 기록 추가')}</h2></div><button type="button" data-event-editor-close>×</button></header><form id="eventEditorFormV111" class="event-editor-form-v111 event-purpose-form-v113" data-kind="review" data-id="${esc(id||'')}"><div class="event-form-intro-v113 ${travel?'travel':''}"><i>${travel?({plan:'✈',place:'⌖',food:'♨',activity:'✦'})[type]:eventCategoryEmojiV111(cat)}</i><div><b>${travel?({plan:'여정을 미리 설계해보세요',place:'가고 싶은 장소를 저장하세요',food:'먹고 싶은 것을 기록하세요',activity:'하고 싶은 경험을 준비하세요'})[type]:'작품과 경험을 오래 기억하세요'}</b><p>${travel?'필요한 일정과 예약 정보를 한곳에 모을 수 있어요.':'창작자, 장소, 인상 깊은 포인트와 감상을 남길 수 있어요.'}</p></div></div><div class="event-form-section-title-v113"><b>${travel?'여행 정보':'작품·경험 정보'}</b><span>${travel?'계획에 필요한 항목을 채워보세요.':'다시 찾기 쉬운 정보부터 기록해보세요.'}</span></div>${travel?travelPurposeFieldsV113(row,type):archivePurposeFieldsV113(row)}${eventPhotoFieldV113(row,preview)}<label class="wide">한 줄 기록<input name="oneLine" maxlength="180" value="${esc(row?.oneLine||'')}" placeholder="한 문장으로 남긴다면"></label><label class="wide">상세 기록<textarea name="review" maxlength="2000" placeholder="느낀 점, 기억할 정보, 다음에 참고할 내용을 적어보세요.">${esc(row?.review||'')}</textarea></label><div class="event-editor-actions-v111">${editing?'<button type="button" class="delete" data-event-delete>삭제</button>':''}<button type="button" data-event-editor-close>취소</button><button type="submit" class="save">저장</button></div></form></section></div>`;
}

eventEditorHTMLV111=function(){
  if(!eventEditorV111)return'';
  const {kind,id}=eventEditorV111;
  const row=kind==='record'?(A.records||[]).find(x=>String(x.id)===String(id)):eventReviewsV111().find(x=>String(x.id)===String(id));
  const preview=eventDraftDataV111||row?.localImage||'';
  return kind==='record'?recordEditorHTMLV113(row,id,!!row,preview):reviewEditorHTMLV113(row,id,!!row,preview);
};

saveEventEditorV111=async function(form){
  const fd=new FormData(form),kind=form.dataset.kind,id=form.dataset.id||'',now=Date.now();
  if(kind==='record'){
    const rows=Array.isArray(A.records)?A.records:[],existing=rows.find(x=>String(x.id)===String(id)),savedMedia=await eventMediaSaveV111(existing),title=String(fd.get('title')||'').trim();
    if(!title){alert('기록 제목을 입력해주세요.');return}
    const color=String(fd.get('color')||'#F8F6DF');
    const row={...existing,id:existing?.id||'rec-'+now,title:title.slice(0,80),body:String(fd.get('body')||'').trim().slice(0,1600),date:String(fd.get('date')||today()),time:String(fd.get('time')||''),recordType:String(fd.get('recordType')||'daily'),albumId:String(fd.get('albumId')||''),emoji:String(fd.get('emoji')||'✎'),location:String(fd.get('location')||'').trim().slice(0,100),people:String(fd.get('people')||'').trim().slice(0,120),mood:String(fd.get('mood')||'').trim().slice(0,100),color:RECORD_COLORS_V125.includes(color)?color:'#F8F6DF',favorite:!!fd.get('favorite'),...savedMedia,authorEmail:existing?.authorEmail||authState?.user?.email||'',authorName:existing?.authorName||authState?.user?.displayName||authState?.user?.name||String(authState?.user?.email||'').split('@')[0],createdAt:existing?.createdAt||now,updatedAt:now};
    if(existing)rows[rows.indexOf(existing)]=row;else rows.push(row);A.records=rows;
  }else{
    const rows=eventReviewsV111(),existing=rows.find(x=>String(x.id)===String(id)),savedMedia=await eventMediaSaveV111(existing),category=String(fd.get('category')||eventEditorV111?.category||'movie'),travel=category==='travel',travelType=travel?String(fd.get('travelType')||eventEditorV111?.travelType||'plan'):'',title=String(fd.get('title')||'').trim();
    if(!title){alert('제목을 입력해주세요.');return}
    const detailA=travel?(String(fd.get('transport')||fd.get('menu')||fd.get('openHours')||fd.get('reservation')||'').trim()):String(fd.get('genre')||'').trim(),detailB=travel?(String(fd.get('lodging')||fd.get('highlight')||fd.get('preparation')||'').trim()):String(fd.get('highlight')||'').trim();
    const row={...existing,id:existing?.id||'ev-'+now,category,experienceStatus:String(fd.get('experienceStatus')||'done'),travelType,folderId:travel?String(fd.get('folderId')||'trip-default'):'',title:title.slice(0,100),creator:travel?'':String(fd.get('creator')||'').trim().slice(0,100),place:String(fd.get('place')||'').trim().slice(0,120),date:String(fd.get('date')||today()),endDate:travel?String(fd.get('endDate')||''):'',time:travel?String(fd.get('time')||''):'',rating:Number(fd.get('rating'))||0,genre:String(fd.get('genre')||'').trim().slice(0,100),companions:String(fd.get('companions')||'').trim().slice(0,120),highlight:String(fd.get('highlight')||'').trim().slice(0,180),address:String(fd.get('address')||'').trim().slice(0,180),transport:String(fd.get('transport')||'').trim().slice(0,120),lodging:String(fd.get('lodging')||'').trim().slice(0,120),menu:String(fd.get('menu')||'').trim().slice(0,160),reservation:String(fd.get('reservation')||'').trim().slice(0,160),openHours:String(fd.get('openHours')||'').trim().slice(0,120),preparation:String(fd.get('preparation')||'').trim().slice(0,180),cost:String(fd.get('cost')||'').trim().slice(0,40),detailA:detailA.slice(0,240),detailB:detailB.slice(0,240),oneLine:String(fd.get('oneLine')||'').trim().slice(0,180),review:String(fd.get('review')||'').trim().slice(0,2000),...savedMedia,authorEmail:existing?.authorEmail||authState?.user?.email||'',authorName:existing?.authorName||authState?.user?.displayName||authState?.user?.name||String(authState?.user?.email||'').split('@')[0],createdAt:existing?.createdAt||now,updatedAt:now};
    if(existing)rows[rows.indexOf(existing)]=row;else rows.push(row);A.eventReviews=rows;
  }
  eventEditorV111=null;eventDraftFileV111=null;eventDraftDataV111='';await saveApp();renderEvent();
};

const bindEventBeforeV113=bindEventV111;
bindEventV111=function(){
  bindEventBeforeV113();
  const root=$('#event'),previousClick=root?.onclick;
  if(root&&previousClick)root.onclick=async event=>{const page=event.target.closest('[data-record-page-v125]');if(page&&!page.disabled){recordPageV125=Number(page.dataset.recordPageV125)||1;renderEvent();return}if(event.target.closest('[data-record-owner]')||event.target.closest('[data-event-mode]'))recordPageV125=1;await previousClick.call(root,event)};
  $('#archiveCategoryV113')?.addEventListener('change',e=>{archiveCategoryV111=e.target.value;renderEvent()});
  $('#eventEditorFormV111 select[name="category"]')?.addEventListener('change',e=>configureArchiveFieldsV125(e.target.value));
  const travelType=$('#eventEditorFormV111 select[name="travelType"]');
  if(travelType){travelType.disabled=true;travelType.setAttribute('aria-disabled','true');const hidden=document.createElement('input');hidden.type='hidden';hidden.name='travelType';hidden.value=travelType.value;travelType.after(hidden)}
};

function readingHTMLV113(){
  const rows=pRows('reading'),read=rows.filter(x=>x.details?.readingStatus!=='want'),quotes=read.filter(x=>x.details?.quote).slice(0,3),featured=read.find(x=>(+x.details?.currentPage||0)<(+x.details?.totalPages||0))||read[0]||rows[0],fd=featured?.details||{},pct=featured&&fd.totalPages?Math.min(100,Math.round((+fd.currentPage||0)/(+fd.totalPages||1)*100)):0;
  const demo=rows.length?[]:[{title:'아주 작은 습관의 힘',author:'제임스 클리어',details:{currentPage:195,totalPages:300,readingStatus:'read'}},{title:'기억하고 싶은 책',author:'AiderLog',details:{currentPage:75,totalPages:240,readingStatus:'read'}},{title:'다음에 읽을 책',author:'Wishlist',details:{readingStatus:'want'}}];
  const shelf=[...rows,...demo].slice(0,6).map(r=>{const d=r.details||{},p=d.totalPages?Math.min(100,Math.round((+d.currentPage||0)/(+d.totalPages||1)*100)):0;return `<article class="reading-book-v113">${itemPhoto(r,'reading-cover-v113')}<div><b>${esc(r.title||'Book')}</b><span>${esc(d.author||r.author||'')}</span>${d.readingStatus==='want'?'<small>읽고 싶은 책</small>':`<i><em style="width:${p}%"></em></i><small>${p}% · ${d.currentPage||0}/${d.totalPages||0}p</small>`}</div>${r.id?`<button data-pdelete="${esc(r.id)}">×</button>`:''}</article>`}).join('');
  const quoteCards=(quotes.length?quotes:[{title:'기억할 문장',details:{quote:'좋은 문장은 다시 시작할 용기를 남긴다.',quotePage:75}}]).map(r=>`<blockquote><small>${esc(r.title||'')}</small><p>“${esc(r.details?.quote||'')}”</p>${r.details?.quotePage?`<em>p.${r.details.quotePage}</em>`:''}</blockquote>`).join('');
  return `<div class="reading-v113"><section class="reading-hero-v113"><div><small>READING</small><h2>나의 독서 기록</h2><p>읽는 중인 책과 기억할 문장을 한눈에 정리해요.</p></div><button data-padd="reading">＋ 책 기록</button></section><section class="reading-metrics-v113">${[['기록한 책',read.length||3],['완독',read.filter(x=>(+x.details?.currentPage||0)>=(+x.details?.totalPages||Infinity)).length],['문장',quotes.length||1],['읽은 페이지',read.reduce((a,r)=>a+(+r.details?.currentPage||0),0)||270]].map(([label,value])=>`<article><span>${label}</span><b>${value}</b></article>`).join('')}</section><section class="personal-panel reading-current-v113"><header><div><small>NOW READING</small><h3>읽고 있는 책</h3></div></header><div class="reading-featured-v113">${featured?itemPhoto(featured,'reading-featured-cover-v113'):'<div class="reading-featured-cover-v113"><span>▤</span></div>'}<div><b>${esc(featured?.title||'아주 작은 습관의 힘')}</b><p>${esc(fd.author||featured?.author||'제임스 클리어')}</p><i><em style="width:${featured?pct:65}%"></em></i><small>${featured?`${fd.currentPage||0} / ${fd.totalPages||0}p · ${pct}%`:'195 / 300p · 65%'}</small></div></div></section><section class="personal-panel reading-library-v113"><header><div><small>MY LIBRARY</small><h3>나의 서재</h3></div><button data-padd="reading">＋</button></header><div class="reading-books-v113">${shelf}</div></section><section class="personal-panel reading-quotes-v113"><header><div><small>MEMORY</small><h3>기억할 문장</h3></div></header><div class="reading-quote-list-v113">${quoteCards}</div></section></div>`;
}

function overviewHTMLV113(){
  const cutoff=new Date();cutoff.setDate(cutoff.getDate()-personalOverviewDays+1);const ck=cutoff.toISOString().slice(0,10),items=personalItems().filter(x=>(x.date||'')>=ck),sessions=(P.pomodoroSessions||[]).filter(x=>(x.date||'')>=ck),exercise=items.filter(x=>x.category==='health'&&x.details?.healthType==='exercise'),photos=exercise.filter(x=>x.localImage||x.media?.fileId).slice(0,2),quotes=items.filter(x=>x.category==='reading'&&x.details?.quote).slice(0,3),activity=[...items.map(x=>({date:x.date,title:x.title,type:({health:'건강',reading:'독서',workflow:'업무',finance:'금융'})[x.category]||'기록'})),...sessions.map(x=>({date:x.date,title:x.task||'집중 세션',type:`집중 ${x.minutes||0}분`,time:x.completedAt||0}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))+(b.time||0)-(a.time||0)).slice(0,5),total=items.length+sessions.length;
  return `<div class="overview-dialog-v113" role="dialog" aria-label="Personal Overview"><header><div><small>PERSONAL OVERVIEW</small><h2>나의 ${personalOverviewDays}일</h2><p>${total?`${total}개의 기록에서 최근 흐름을 모았어요.`:'첫 기록을 남기면 이곳에 흐름이 나타나요.'}</p></div><div class="overview-controls-v113"><span><button data-odays="7" class="${personalOverviewDays===7?'active':''}">7일</button><button data-odays="30" class="${personalOverviewDays===30?'active':''}">30일</button></span><button type="button" data-personal-overview-close aria-label="Overview 닫기">×</button></div></header><div class="overview-metrics-v113">${[['♡','건강',items.filter(x=>x.category==='health').length],['▤','독서',items.filter(x=>x.category==='reading').length],['✓','업무',items.filter(x=>x.category==='workflow').length],['₩','금융',items.filter(x=>x.category==='finance').length],['◷','집중',sessions.length]].map(x=>`<article><i>${x[0]}</i><span>${x[1]}</span><b>${x[2]}</b></article>`).join('')}</div><div class="overview-grid-v113"><section class="personal-panel overview-activity-v113"><header><div><small>RECENT</small><h3>최근 활동</h3></div></header><div>${activity.length?activity.map(x=>`<article><time>${esc(String(x.date||'').slice(5).replace('-','.'))}</time><span>${esc(x.type)}</span><b>${esc(x.title||'기록')}</b></article>`).join(''):'<p class="personal-empty">최근 활동이 없습니다.</p>'}</div></section><section class="personal-panel"><header><div><small>BODY</small><h3>운동일 변화</h3></div></header><div class="body-compare">${photos.length?photos.map(r=>`${itemPhoto(r,'body-photo')}<small>${esc(r.date)}</small>`).join(''):'<p class="personal-empty">운동 사진을 추가하면 두 날짜를 비교합니다.</p>'}</div></section><section class="personal-panel"><header><div><small>QUOTES</small><h3>문장 기록</h3></div></header><div class="quote-list">${quotes.length?quotes.map(r=>`<blockquote><b>${esc(r.title)}</b><p>“${esc(r.details?.quote)}”</p></blockquote>`).join(''):'<p class="personal-empty">독서 문장이 없습니다.</p>'}</div></section></div></div>`;
}

function pomodoroHTMLV113(){
  const mm=String(Math.floor(pomoRemaining/60)).padStart(2,'0'),ss=String(pomoRemaining%60).padStart(2,'0'),all=(P.pomodoroSessions||[]).slice().sort((a,b)=>(b.completedAt||0)-(a.completedAt||0)),todayRows=all.filter(x=>x.date===today()),total=todayRows.reduce((n,x)=>n+(Number(x.minutes)||0),0);
  return `<div class="pomo-workspace-v113"><section class="pomo-timer-v113"><div class="pomo-clock-v113"><small>${pomoMode==='focus'?'FOCUS':pomoMode==='short'?'SHORT BREAK':'LONG BREAK'}</small><strong id="pomoClock">${mm}:${ss}</strong><span>오늘 ${todayRows.length} SESSION · ${total}분</span></div><label>집중할 작업<input id="pomoTask" maxlength="80" placeholder="지금 집중할 작업" value="${esc(P.pomodoroTask||'')}"></label><div class="pomo-presets-v113"><button data-pomo="25,focus" class="${pomoInitial===1500?'active':''}">25분 집중</button><button data-pomo="5,short" class="${pomoInitial===300?'active':''}">5분 휴식</button><button data-pomo="15,long" class="${pomoInitial===900?'active':''}">15분 휴식</button></div><div class="pomo-actions-v113"><button id="pomoStart">${pomoRunning?'PAUSE':'START'}</button><button id="pomoReset">↺ RESET</button></div></section><section class="pomo-history-v113"><header><div><small>PROGRESS</small><h3>진행 기록</h3></div><span>${todayRows.length}회 · ${total}분</span></header><div>${all.length?all.slice(0,10).map(x=>`<article><i>◷</i><div><b>${esc(x.task||'집중 세션')}</b><span>${esc(x.date||'')}${x.completedAt?` · ${new Date(x.completedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`:''}</span></div><strong>${Number(x.minutes)||0}분</strong></article>`).join(''):'<p class="personal-empty">타이머를 완료하면 진행 기록이 여기에 쌓입니다.</p>'}</div></section></div>`;
}

readingHTML=readingHTMLV113;
overviewHTML=overviewHTMLV113;
pomodoroHTML=pomodoroHTMLV113;
const bindPersonalBeforeV113=bindPersonal;
bindPersonal=function(){
  bindPersonalBeforeV113();
  $('[data-personal-overview-close]')?.addEventListener('click',()=>{personalOverview=false;renderPersonal()});
};

renderEvent();
renderPersonal();
