const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const box={module:{exports:{}}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../consult-model-v167.js'),'utf8'),box);const M=box.module.exports,copy=v=>JSON.parse(JSON.stringify(v));let count=0;function test(name,fn){fn();count++;console.log('PASS',name)}
const old={unknownRoot:{keep:true},consultingClients:[{id:'c1',name:'테스트 고객',stage:'proposal',additionalMajors:'복수전공 원문',gpa:3.8,gpaScale:4.5,note:'PRIVATE_CLIENT_SECRET',nextSession:'2026-09-30T11:00',unknownExtra:{keep:true},consult167:{internalNotes:[{id:'n1',text:'PRIVATE_NOTE_SECRET'}],targets:[{id:'target1',university:'테스트 대학원',department:'뇌공학',deadline:'2026-10-01',rationale:'원문 근거',internalNote:'PRIVATE_TARGET_SECRET',result:'waitlisted'}]}}],consultingTasks:[{id:'t1',clientId:'c1',title:'고객 과업',dueDate:'2026-09-29',done:true,unknownState:'keep'}],consultingSessions:[{id:'s1',clientId:'c1',date:'2026-09-01T12:00',summary:'LEGACY_PRIVATE_SUMMARY',clientFeedback:'고객용 공개 내용',internalNote:'PRIVATE_SESSION_SECRET'}],consultingFiles:[{id:'f1',clientId:'c1',fileId:'physical1',storageScope:'private',ownerEmail:'legacy@example.com',name:'문서1',type:'application/pdf',size:1200,customerFeedback:'고객용 문서피드백',internalNote:'PRIVATE_FILE_SECRET'}]};const normalized=M.normalize(old);
test('normalization does not mutate original',()=>assert.equal(old.consultingTasks[0].status,undefined));
test('unknown fields and profile details preserved',()=>{assert.deepEqual(copy(normalized.unknownRoot),old.unknownRoot);assert.deepEqual(copy(normalized.consultingClients[0].unknownExtra),old.consultingClients[0].unknownExtra);assert.equal(normalized.consultingClients[0].additionalMajors,old.consultingClients[0].additionalMajors)});
test('ambiguous legacy stage requires explicit review',()=>{assert.equal(normalized.consultingClients[0].consult167.stage,'');assert.equal(normalized.consultingClients[0].consult167.stageNeedsReview,true);assert.equal(normalized.consultingClients[0].stage,'proposal')});
test('normalization idempotent',()=>assert.deepEqual(copy(M.normalize(normalized)),copy(normalized)));
test('more than prior caps retained',()=>{const rows=Array.from({length:1601},(_,i)=>({id:'t'+i,clientId:'c1',title:'기록'+i}));assert.equal(M.normalize({...old,consultingTasks:rows}).consultingTasks.length,1601)});
test('orphan records and file refs retained',()=>{const n=M.normalize({...old,consultingFiles:[...old.consultingFiles,{id:'orphan',clientId:'missing',fileId:'keep'}]});assert.equal(n.consultingFiles.length,2);assert.equal(n.consultingFiles[0].fileId,'physical1');assert.equal(n.consultingFiles[0].ownerEmail,'legacy@example.com');assert.equal(n.consultingFiles[0].storageScope,'private')});
test('progress based only on tasks including 0/0',()=>{assert.deepEqual(copy(M.progress(normalized,'c1')),{done:1,total:1});assert.deepEqual(copy(M.progress(normalized,'none')),{done:0,total:0})});
test('unknown states preserved in legacy fields',()=>{const t=M.task({status:'original',done:true,assignee:'old-name'});assert.equal(t.legacyStatus,'original');assert.equal(t.done,true);assert.equal(t.legacyAssignee,'old-name')});
test('calendar stable source IDs and legacy next session',()=>{const rows=M.calendar(normalized);assert.ok(rows.some(r=>r.id==='consulting:t1'));assert.ok(rows.some(r=>r.id==='consulting-session:s1'));assert.ok(rows.some(r=>r.id==='consulting-target:target1'));assert.ok(rows.some(r=>r.id==='consulting-next:c1'));assert.equal(new Set(rows.map(r=>r.id)).size,rows.length)});
test('legacy next session not duplicated when real session exists',()=>{const n=M.normalize({...old,consultingSessions:[...old.consultingSessions,{id:'same',clientId:'c1',date:'2026-09-30T11:00'}]});assert.equal(M.calendar(n).some(r=>r.id==='consulting-next:c1'),false)});
test('document versions are grouped without losing old physical ref',()=>{const n=M.normalize({...old,consultingFiles:[{...old.consultingFiles[0],documentId:'d1',version:1},{...old.consultingFiles[0],id:'f2',documentId:'d1',fileId:'physical2',version:2}]});assert.equal(M.latestDocuments(n)[0].id,'f2');assert.equal(n.consultingFiles[0].fileId,'physical1')});
test('delivery allowlist excludes every private field and legacy summary',()=>{const chosen=M.selectionRows(normalized,normalized.consultingClients[0]).map(x=>x.key),r=M.delivery(normalized,'c1',chosen,{id:'delivery',createdAt:1,createdBy:'test-owner'}),j=JSON.stringify(r);assert.equal(/PRIVATE_|LEGACY_PRIVATE|internalNote|unknownExtra/.test(j),false);assert.ok(j.includes('고객용 공개 내용'));assert.ok(j.includes('고객용 문서피드백'))});
test('individual delivery selection excludes other source rows',()=>{const r=M.delivery(normalized,'c1',['target:target1'],{id:'x',createdAt:1,createdBy:'a'});assert.equal(r.sections.length,1);assert.equal(r.sections[0].kind,'target');assert.equal(r.sourceRefs[0].id,'target1')});
test('delivery snapshot unaffected by later original mutations',()=>{const n=M.normalize(old),r=M.delivery(n,'c1',['target:target1'],{id:'x',createdAt:1,createdBy:'a'}),before=JSON.stringify(r);n.consultingClients[0].consult167.targets[0].university='수정';assert.equal(JSON.stringify(r),before)});
test('TXT derived from same exact snapshot fields',()=>{const r=M.delivery(normalized,'c1',['target:target1'],{id:'x',createdAt:1,createdBy:'a'}),txt=M.deliveryText(r);for(const v of Object.values(r.sections[0].fields))assert.ok(txt.includes(String(v)));assert.equal(txt.includes('PRIVATE_'),false)});
console.log(`${count} model tests passed`);
