import test from 'node:test';import assert from 'node:assert/strict';import {createBioAdminClient} from '../bio-admin-client-v192.js';
const state=revision=>({revision,projects:[],entries:[],orders:[],programs:[]});
function fixture(fetchImpl){let user={uid:'a'},notify;const firebase={getState:()=>({user}),getFirebaseIdToken:async()=> 'test-token',subscribe(fn){notify=fn;fn();return()=>{}}};const client=createBioAdminClient({getFirebase:()=>firebase,fetchImpl,events:new EventTarget()});return{client,firebase,change(next){user=next;notify()}}}
const response=(s,owner='a')=>({ok:true,status:200,json:async()=>({state:s,ownerKey:owner})});
const defer=()=>{let resolve;return{promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}};
test('creating transport/auth subscription makes zero database requests; repeated opens share cached owner data',async()=>{let calls=0;const fx=fixture(async()=>{calls++;return response(state(0))});assert.equal(calls,0);await fx.client.read();await fx.client.read();assert.equal(calls,1);await fx.client.read({force:true});assert.equal(calls,2)});
test('simultaneous read requests coalesce into one request',async()=>{let calls=0;const d=defer(),fx=fixture(()=>{calls++;return d.promise}),a=fx.client.read(),b=fx.client.read({force:true});await new Promise(r=>setImmediate(r));d.resolve(response(state(0)));await Promise.all([a,b]);assert.equal(calls,1)});
test('read-only response cannot replace a save that completed after read began',async()=>{const pending=[];const fx=fixture((u,o)=>new Promise(resolve=>pending.push({body:JSON.parse(o.body),resolve})));const read=fx.client.read();await new Promise(r=>setImmediate(r));const save=fx.client.save({collection:'programs',expectedRevision:0,row:{id:'p',name:'one',price:1}});await new Promise(r=>setImmediate(r));pending[1].resolve(response({...state(1),programs:[{id:'p',name:'one'}]}));await save;pending[0].resolve(response(state(0)));assert.equal((await read).state.programs[0].id,'p')});
test('network retry reuses idempotency ID and captured owner while successful save uses returned state',async()=>{const bodies=[];let fail=true;const fx=fixture(async(url,opt)=>{const body=JSON.parse(opt.body);bodies.push(body);assert.equal(body.expectedOwnerKey,'a');assert.equal(opt.headers.Authorization,'Bearer test-token');if(fail){fail=false;throw TypeError('network')}return response({...state(1),programs:[{id:'p'}]})});const draft={collection:'programs',expectedRevision:0,row:{id:'p',name:'one',price:1}};await assert.rejects(fx.client.save(draft),/입력/);assert.equal((await fx.client.save(draft)).state.programs[0].id,'p');assert.equal(bodies[0].requestId,bodies[1].requestId)});
test('stale revision errors are returned without changing the submitted draft',async()=>{const input={collection:'projects',expectedRevision:3,row:{id:'p',title:'draft'}};const fx=fixture(async()=>({ok:false,status:409,json:async()=>({error:'다른 화면에서 변경되었습니다.'})}));await assert.rejects(fx.client.save(input),e=>e.status===409);assert.equal(input.row.title,'draft');assert.equal(input.expectedRevision,3)});
test('quota pause blocks repeated reads and saves without discarding a draft',async()=>{let count=0;const fx=fixture(async()=>{count++;return{ok:false,status:503,headers:{get:()=> '1800'},json:async()=>({error:'사용량 한도',code:'resource-exhausted'})}});await assert.rejects(fx.client.read());await assert.rejects(fx.client.read({force:true}));await assert.rejects(fx.client.save({row:{id:'kept'},expectedRevision:0}));assert.equal(count,1)});
test('identity generation cancels stale responses even after same account signs in again',async()=>{const d=defer(),fx=fixture(()=>d.promise),pending=fx.client.read();await new Promise(r=>setImmediate(r));fx.change(null);fx.change({uid:'a'});d.resolve(response({...state(1),programs:[{id:'private'}]}));await assert.rejects(pending,e=>e.status===401);assert.equal(fx.client.snapshot(),null)});
test('token resolution after account switch never issues a request and wrong-owner response is rejected',async()=>{let calls=0;const fx=fixture(async()=>{calls++;return response(state(1),'wrong')});await assert.rejects(fx.client.read(),e=>e.status===401);assert.equal(calls,1);const d=defer();fx.firebase.getFirebaseIdToken=()=>d.promise;const pending=fx.client.read({force:true});fx.change({uid:'b'});d.resolve('old');await assert.rejects(pending,e=>e.status===401);assert.equal(calls,1)});
