import test from 'node:test';
import assert from 'node:assert/strict';
import '../bio-admin-domain-v192.js';
import {bioAdminDispatch} from '../server/bio-admin-store-v192.mjs';
import {createHandler} from '../api/bio-admin.mjs';
const M=globalThis.AiderBioAdminDomainV192,clone=value=>structuredClone(value);
const owner={uid:'owner-a',email:'qhals5060@gmail.com',email_verified:true};
const other={uid:'owner-b',email:'aidway55@gmail.com',email_verified:true};
const path='users/owner-a/bioAdmin/main';
function memory(){
 const docs=new Map([['users/owner-a/private/main',{payload:{consultingClients:[{id:'client-a',name:'고객 가'}],personalItems:[{id:'keep',title:'개인 금융'}]}}]]),reads=[],writes=[];
 const snap=key=>({exists:docs.has(key),data:()=>clone(docs.get(key))});
 const db={docs,reads,writes,doc(key){return{path:key,get:async()=>{reads.push(key);return snap(key);}};},async runTransaction(run){const queued=[];const output=await run({get:ref=>ref.get(),set(ref,value){queued.push([ref.path,clone(value)]);}});for(const [key,value]of queued){docs.set(key,value);writes.push(key);}return output;}};return db;
}
const read=(uid=owner.uid)=>({action:'read',expectedOwnerKey:uid});
let nonce=0;
const save=(collection,row,revision=0)=>({action:'save',expectedOwnerKey:owner.uid,expectedRevision:revision,requestId:'bio-request-'+String(++nonce).padStart(6,'0'),collection,row});
const program=(extra={})=>({id:'program-a',name:'맞춤 프로그램',price:1000000,notes:'',active:true,...extra});
const order=(extra={})=>({id:'order-a',clientId:'client-a',programId:'program-a',amount:1000000,date:'2026-09-20',dueDate:'2026-10-01',status:'active',...extra});
const project=(extra={})=>({id:'project-a',title:'바이오 국가과제',code:'RND-2026',agency:'전문기관',startDate:'2026-01-01',endDate:'2026-12-31',governmentAmount:1000000,ownCashAmount:200000,inKindAmount:300000,budgets:[{id:'materials',name:'재료비',fundingSource:'government',amount:800000},{id:'own',name:'연구활동',fundingSource:'ownCash',amount:200000},{id:'labor',name:'현물 인건비',fundingSource:'inKind',amount:300000}],...extra});
const entry=(extra={})=>({id:'entry-a',business:'consult',kind:'receipt',title:'입금',date:'2026-09-20',amount:110000,taxAmount:10000,orderId:'order-a',...extra});
async function seeded(){const db=memory();await bioAdminDispatch(db,owner,save('programs',program()));await bioAdminDispatch(db,owner,save('orders',order(),1));return db;}
async function edit(db,collection,row){const state=(await bioAdminDispatch(db,owner,read())).state;return bioAdminDispatch(db,owner,save(collection,row,state.revision));}
async function remove(db,collection,id,extra={}){return bioAdminDispatch(db,owner,{action:'delete',expectedOwnerKey:owner.uid,expectedRevision:db.docs.get(path).state.revision,requestId:'delete-'+(++nonce),collection,id,confirmed:true,...extra});}
test('empty owner space stays empty with no seeded programs and only two on-demand reads',async()=>{const db=memory();const output=await bioAdminDispatch(db,owner,read());assert.deepEqual(output.state,M.empty());assert.deepEqual(db.reads,['workIdentities/owner-a',path]);assert.equal(db.writes.length,0);assert.equal(output.summary.consulting.netCash,0);});
test('verified CONSULT owner and token owner checks happen before any database read',async()=>{const db=memory();for(const user of [{...owner,email:'unknown@example.com'},{...owner,email_verified:false},{uid:'owner-a'}])await assert.rejects(bioAdminDispatch(db,user,read()),e=>e.status===403);await assert.rejects(bioAdminDispatch(db,owner,read('different')),e=>e.status===401);assert.equal(db.reads.length,0);});
test('employee marker denies reads and mutations; owner data cannot be accessed by another owner',async()=>{const db=await seeded();const first=clone(db.docs);assert.equal((await bioAdminDispatch(db,other,read(other.uid))).state.orders.length,0);db.docs.set('workIdentities/owner-a',{kind:'employee'});await assert.rejects(bioAdminDispatch(db,owner,read()),e=>e.status===403);await assert.rejects(bioAdminDispatch(db,owner,save('programs',program({name:'bad'}),2)),e=>e.status===403);assert.deepEqual(db.docs.get(path),first.get(path));});
test('program saves write one dedicated document and never rewrite existing private records',async()=>{const db=memory(),before=clone(db.docs.get('users/owner-a/private/main'));await bioAdminDispatch(db,owner,save('programs',program()));assert.deepEqual(db.writes,[path]);assert.equal(db.reads.length,2);assert.deepEqual(db.docs.get('users/owner-a/private/main'),before);});
test('orders bind only existing owner customers and custom programs, snapshot names',async()=>{const db=memory();await assert.rejects(bioAdminDispatch(db,owner,save('orders',order())),e=>e.status===400);await bioAdminDispatch(db,owner,save('programs',program()));await assert.rejects(bioAdminDispatch(db,owner,save('orders',order({clientId:'outside'}),1)),e=>e.status===400);const output=await bioAdminDispatch(db,owner,save('orders',order(),1));assert.equal(output.row.clientName,'고객 가');assert.equal(output.row.programName,'맞춤 프로그램');assert.equal(db.writes.length,2);});
test('stale revisions and duplicate request IDs cannot overwrite another device',async()=>{const db=memory(),command=save('programs',program());await bioAdminDispatch(db,owner,command);const retried=await bioAdminDispatch(db,owner,clone(command));assert.equal(retried.replayed,true);assert.equal(db.writes.length,1);await assert.rejects(bioAdminDispatch(db,owner,{...command,row:program({name:'different'})}),e=>e.status===409);await assert.rejects(bioAdminDispatch(db,owner,save('programs',program({name:'stale'}))),e=>e.status===409);});
test('late response-loss retry returns current state without rolling back a subsequent save',async()=>{const db=memory(),command=save('programs',program());await bioAdminDispatch(db,owner,command);await bioAdminDispatch(db,owner,save('programs',program({name:'최신 이름'}),1));const output=await bioAdminDispatch(db,owner,command);assert.equal(output.state.programs[0].name,'최신 이름');assert.equal(output.state.revision,2);assert.equal(db.writes.length,2);});
test('malformed KRW, unsafe integers, fractions, negative values and strings are rejected',()=>{for(const amount of [-1,1.2,'1000',NaN,Infinity,1000000000001,Number.MAX_SAFE_INTEGER])assert.throws(()=>M.normalizeRow('entries',entry({amount})),e=>e.status===400);assert.equal(M.money(0),0);});
test('invalid calendar dates and reversed project dates produce input errors',()=>{for(const day of ['2026-02-30','2026-99-99','26-01-01','2026-2-01'])assert.throws(()=>M.date(day),e=>e.status===400);assert.throws(()=>M.normalizeRow('projects',project({endDate:'2025-01-01'})),e=>e.status===400);});
test('manual included tax and partial payment never exceed gross total',()=>{assert.throws(()=>M.normalizeRow('entries',entry({taxAmount:110001})));assert.throws(()=>M.normalizeRow('entries',entry({paidAmount:110001})));assert.throws(()=>M.normalizeRow('entries',entry({paidAmount:1})));assert.throws(()=>M.normalizeRow('entries',entry({kind:'tax',orderId:'',taxAmount:10000})));assert.equal(M.normalizeRow('entries',entry({kind:'expense',orderId:'',amount:110000,taxAmount:10000,paidAmount:50000})).paidAmount,50000);});
test('customer cumulative income distinguishes contract, cash received, refunds and unpaid balances',async()=>{const db=await seeded();await edit(db,'entries',entry({amount:550000,taxAmount:50000}));await edit(db,'entries',entry({id:'refund-a',kind:'refund',amount:110000,taxAmount:10000}));const output=await edit(db,'entries',entry({id:'cost-a',kind:'expense',amount:110000,taxAmount:10000,paidAmount:50000,orderId:''}));const t=output.summary.consulting;assert.equal(t.contract,1000000);assert.equal(t.received,550000);assert.equal(t.refunded,110000);assert.equal(t.netReceived,440000);assert.equal(t.outstanding,560000);assert.equal(t.expense,50000);assert.equal(t.unpaid,60000);assert.equal(t.netCash,390000);assert.equal(t.includedSalesTax,40000);assert.equal(t.includedCostTax,10000);});
test('settlement payout and actual tax payment are cash costs; included tax is not charged twice',async()=>{const db=await seeded();await edit(db,'entries',entry({amount:550000,taxAmount:50000}));await edit(db,'entries',entry({id:'settlement-a',kind:'settlement',amount:110000,taxAmount:10000,paidAmount:60000}));const output=await edit(db,'entries',entry({id:'tax-a',kind:'tax',amount:40000,taxAmount:0,paidAmount:20000,orderId:''}));assert.equal(output.summary.consulting.netCash,470000);assert.equal(output.summary.consulting.settlement,60000);assert.equal(output.summary.consulting.taxPaid,20000);assert.equal(output.summary.consulting.unpaid,70000);});
test('refunds cannot exceed either collected money or included collected tax',async()=>{const db=await seeded();await edit(db,'entries',entry());await assert.rejects(edit(db,'entries',entry({id:'refund-a',kind:'refund',amount:110001,taxAmount:0})),e=>e.status===400);await assert.rejects(edit(db,'entries',entry({id:'refund-a',kind:'refund',amount:110000,taxAmount:10001})),e=>e.status===400);assert.equal(db.docs.get(path).state.entries.length,1);});
test('deleted receipts cannot orphan refunds and deleting an order with transactions is rejected atomically',async()=>{const db=await seeded();await edit(db,'entries',entry());await edit(db,'entries',entry({id:'refund-a',kind:'refund',amount:50000,taxAmount:0}));const before=clone(db.docs.get(path));await assert.rejects(remove(db,'entries','entry-a'),e=>e.status===400);await assert.rejects(remove(db,'orders','order-a'),e=>e.status===400);assert.deepEqual(db.docs.get(path),before);});
test('explicit deletion keeps a tombstone and original values without any expiry',async()=>{const db=await seeded();await assert.rejects(remove(db,'orders','order-a',{confirmed:false}),e=>e.status===400);const output=await remove(db,'orders','order-a');const row=output.state.orders[0];assert.equal(row.deleted,true);assert.equal(row.clientName,'고객 가');assert.equal(row.amount,1000000);assert.equal(M.active(output.state.orders).length,0);assert.equal(output.summary.consulting.contract,0);assert(!JSON.stringify(db.docs.get(path)).includes('expiresAt'));await assert.rejects(edit(db,'orders',order()),e=>e.status===409);});
test('program names can change without altering historic order program snapshots',async()=>{const db=await seeded();const output=await edit(db,'programs',program({name:'새 이름',price:2000000}));assert.equal(output.state.orders[0].programName,'맞춤 프로그램');assert.equal(output.state.orders[0].amount,1000000);});
test('custom project budget lines cannot exceed their own funding source or repeat IDs',()=>{assert.throws(()=>M.normalizeRow('projects',project({governmentAmount:500000})));assert.throws(()=>M.normalizeRow('projects',project({budgets:[project().budgets[0],project().budgets[0]]})));assert.deepEqual(M.normalizeRow('projects',project({budgets:[]})).budgets,[]);});
test('national projects separate funding, cash commitments, execution, in-kind and supporting evidence',async()=>{const db=memory();await edit(db,'projects',project());await edit(db,'entries',entry({id:'grant',business:'bio',kind:'funding',title:'정부 입금',projectId:'project-a',orderId:'',fundingSource:'government',amount:500000,taxAmount:0}));await edit(db,'entries',entry({id:'materials-cost',business:'bio',kind:'expense',projectId:'project-a',budgetId:'materials',orderId:'',fundingSource:'government',amount:220000,paidAmount:110000,taxAmount:20000,evidenceStatus:'missing',settlementStatus:'pending'}));const output=await edit(db,'entries',entry({id:'inkind',business:'bio',kind:'expense',projectId:'project-a',budgetId:'labor',orderId:'',fundingSource:'inKind',amount:300000,paidAmount:150000,taxAmount:0,evidenceStatus:'ready',settlementStatus:'settled'}));const p=output.summary.projects[0];assert.equal(p.totalBudget,1500000);assert.equal(p.cashBudget,1200000);assert.equal(p.cashCommitted,220000);assert.equal(p.cashPaid,110000);assert.equal(p.cashUnpaid,110000);assert.equal(p.cashRemaining,980000);assert.equal(p.inKindCommitted,300000);assert.equal(p.inKindExecuted,150000);assert.equal(p.cashBalance,390000);assert.equal(p.missingEvidence,1);assert.equal(p.unsettled,1);assert.equal(p.budgets[0].remaining,580000);assert.equal(p.includedCostTax,20000);assert.equal(output.summary.consulting.received,0);assert.equal(output.summary.bio.paid,110000);});
test('changing R&D settlement status updates approval counts without another cash deduction',async()=>{const db=memory();await edit(db,'projects',project());const cost=entry({business:'bio',kind:'expense',projectId:'project-a',budgetId:'materials',orderId:'',fundingSource:'government',amount:220000,paidAmount:110000,taxAmount:20000});await edit(db,'entries',cost);const before=(await bioAdminDispatch(db,owner,read())).summary;const after=(await edit(db,'entries',{...cost,settlementStatus:'settled'})).summary;assert.equal(before.bio.paid,after.bio.paid);assert.equal(after.bio.unsettled,0);assert.equal(after.projects[0].settledAmount,220000);});
test('used project budget and funding source cannot disappear or be silently relabelled',async()=>{const db=memory();await edit(db,'projects',project());await edit(db,'entries',entry({business:'bio',kind:'expense',projectId:'project-a',budgetId:'materials',orderId:'',fundingSource:'government'}));await assert.rejects(edit(db,'projects',project({budgets:[]})),e=>e.status===400);await assert.rejects(remove(db,'projects','project-a'),e=>e.status===400);await assert.rejects(edit(db,'entries',entry({business:'bio',kind:'expense',projectId:'project-a',budgetId:'materials',orderId:'',fundingSource:'ownCash'})),e=>e.status===400);});
test('general bio business expense needs no project and in-kind is never a funding receipt',()=>{const value=M.normalizeRow('entries',entry({business:'bio',kind:'expense',orderId:'',fundingSource:'ownCash'}));assert.equal(value.projectId,'');assert.throws(()=>M.normalizeRow('entries',entry({business:'bio',kind:'funding',projectId:'project-a',orderId:'',fundingSource:'inKind',taxAmount:0})));assert.throws(()=>M.normalizeRow('entries',entry({business:'bio',kind:'settlement',projectId:'project-a',orderId:''})));});
test('over-budget spending remains recorded and visible as negative remaining instead of deleting facts',async()=>{const db=memory();await edit(db,'projects',project());const output=await edit(db,'entries',entry({business:'bio',kind:'expense',projectId:'project-a',budgetId:'materials',orderId:'',fundingSource:'government',amount:1500000,taxAmount:0}));assert.equal(output.summary.projects[0].cashRemaining,-300000);assert.equal(output.summary.projects[0].budgets[0].remaining,-700000);});
test('oversize recent save preserves the entire previous document instead of trimming old records',async()=>{const db=memory();await bioAdminDispatch(db,owner,save('programs',program()));const prior=db.docs.get(path);prior.state.programs.push(...Array.from({length:400},(_,i)=>({...program({id:'large-'+i,notes:'한'.repeat(2000)}),createdAt:Date.now(),updatedAt:Date.now(),revision:1})));const before=clone(prior);await assert.rejects(bioAdminDispatch(db,owner,save('programs',program({name:'changed'}),1)),e=>e.status===413);assert.deepEqual(db.docs.get(path),before);});
test('older records compress losslessly past raw document capacity and every row survives reading and edits',async()=>{const db=memory();await bioAdminDispatch(db,owner,save('programs',program()));const prior=db.docs.get(path),oldDate=Date.UTC(2020,0,1);prior.state.entries=Array.from({length:3000},(_,i)=>({...M.normalizeRow('entries',entry({id:'historic-'+i,business:'bio',kind:'expense',orderId:'',date:'2020-01-01',amount:i+1,taxAmount:0,notes:'원본 비용 기록 '.repeat(20)})),createdAt:oldDate,updatedAt:oldDate,revision:1}));const original=clone(prior.state.entries);assert(Buffer.byteLength(JSON.stringify(prior))>700000);const saved=await bioAdminDispatch(db,owner,save('programs',program({name:'changed'}),1));assert.deepEqual(saved.state.entries,original);assert(Buffer.byteLength(JSON.stringify(db.docs.get(path)))<700000);assert(JSON.stringify(db.docs.get(path)).includes('__aiderlogQuarterArchive168'));const loaded=await bioAdminDispatch(db,owner,read());assert.deepEqual(loaded.state.entries,original);const changed={...original[1500],title:'과거 기록 정정'};const final=await bioAdminDispatch(db,owner,save('entries',changed,loaded.state.revision));assert.equal(final.state.entries.length,3000);assert.equal(final.state.entries[1500].title,'과거 기록 정정');assert.deepEqual(final.state.entries[1499],original[1499]);assert.deepEqual(final.state.entries[1501],original[1501]);});
test('corrupted compressed records fail closed instead of being overwritten',async()=>{const db=memory();db.docs.set(path,{ownerUid:owner.uid,version:192,state:{revision:1,programs:[{__aiderlogQuarterArchive168:{codec:'gzip-json',version:1,kind:'rows',rawBytes:10,count:1,data:'broken'}}],orders:[],projects:[],entries:[]}});const before=clone(db.docs.get(path));await assert.rejects(bioAdminDispatch(db,owner,read()),e=>e.status===409);await assert.rejects(bioAdminDispatch(db,owner,save('programs',program(),1)),e=>e.status===409);assert.deepEqual(db.docs.get(path),before);});
function response(){const headers={};return{headers,statusCode:0,setHeader(k,v){headers[k]=v;},end(body){this.body=JSON.parse(body);}};}
test('API health and unauthenticated calls never load Admin services',async()=>{let count=0;const handler=createHandler({getServices:async()=>{count++;throw Error('should not run');}});const health=response();await handler({method:'GET',url:'/api/bio-admin?action=health',headers:{}},health);assert.equal(health.statusCode,200);assert.equal(health.body.automaticRefresh,false);const unauth=response();await handler({method:'POST',headers:{}},unauth);assert.equal(unauth.statusCode,401);assert.equal(count,0);});
test('API verifies Firebase revocation, enforces origin and reports quota with no retry loop',async()=>{const prior=process.env.PUBLIC_APP_URL;process.env.PUBLIC_APP_URL='https://aiderdear1.vercel.app';let tokens=0;try{const handler=createHandler({getServices:async()=>({db:{},auth:{async verifyIdToken(token,revoked){assert.equal(token,'test');assert.equal(revoked,true);tokens++;return owner;}}}),dispatch:async()=>{throw Object.assign(Error('quota exceeded'),{code:8});}});const denied=response();await handler({method:'POST',headers:{origin:'https://evil.invalid',authorization:'Bearer test'},body:read()},denied);assert.equal(denied.statusCode,403);assert.equal(tokens,0);const blocked=response();await handler({method:'POST',headers:{origin:process.env.PUBLIC_APP_URL,authorization:'Bearer test'},body:read()},blocked);assert.equal(blocked.statusCode,503);assert.equal(blocked.body.code,'resource-exhausted');assert.equal(blocked.headers['Retry-After'],'1800');assert.equal(tokens,1);}finally{if(prior===undefined)delete process.env.PUBLIC_APP_URL;else process.env.PUBLIC_APP_URL=prior;}});
