const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=name=>fs.readFileSync(path.join(root,name),'utf8');
function harness(){
  class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.isConnected=true;this.classList={add(){},remove:()=>{this.closed=true;}};this.value='';this.className='';}
    append(...items){this.children.push(...items);items.forEach(x=>{if(x&&typeof x==='object')x.parentElement=this;});}replaceChildren(...items){this.children=[];this.append(...items);}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}
    querySelector(s){if(s==='[type=submit]'||s==='button[type=submit]')return this.submit;if(s==='.photo-upload-error-v176')return this.children.find(x=>x.className==='photo-upload-error-v176');return null;}querySelectorAll(s){return s==='button'?[this.submit].filter(Boolean):[];}closest(s){return s==='form'?this.form:null;}remove(){this.isConnected=false;}}
  const elements=Object.fromEntries(['personalForm','personalPhotoPreview','personalPhoto','personalModal','eventPreviewV111','eventPhotoV111'].map(k=>[k,new Element()]));elements.personalForm.submit=new Element('button');elements.personalPhoto.form=elements.personalForm;
  const events={},writes=[],uploads=[],storage=new Map();let failUpload='',failWrite=false;
  const context={console,URL:{createObjectURL:()=> 'blob:fixture',revokeObjectURL(){}},File:class{},FileReader:class{},Image:class{},MutationObserver:class{observe(){}},setTimeout,clearTimeout,addEventListener(){},
    document:{body:new Element(),getElementById:id=>elements[id]||null,createElement:tag=>new Element(tag),addEventListener:(type,fn)=>{events[type]=fn;},querySelectorAll:()=>[]},
    localStorage:{setItem:(k,v)=>storage.set(k,v)},authState:{user:{uid:'a',email:'a@example.test'}},P:{personalItems:[]},A:{records:[],eventReviews:[]},eventDraftFileV111:null,eventDraftDataV111:'',
    esc:String,alert(){},confirm:()=>true,today:()=> '2026-09-12',renderPersonal(){},renderEvent(){},personalItems(){return context.P.personalItems;},eventReviewsV111(){return context.A.eventReviews;},
    openEventEditorV111(kind,id='',category='movie',travelType=''){context.eventEditorV111={kind,id,category,travelType};},eventMediaSaveV111(){},
    FormData:class{constructor(form){this.values=form.values;}get(key){return this.values?.[key]??null;}},
    fb:{async uploadPrivateMedia(file){uploads.push(file.name);if(file.name===failUpload)throw Error('연결 실패');return {id:'private-'+file.name,name:file.name,mimeType:file.type};},async uploadMedia(file){uploads.push(file.name);if(file.name===failUpload)throw Error('연결 실패');return {id:'event-'+file.name,name:file.name,mimeType:file.type};},async writePrivateData(value){if(failWrite)throw Error('저장 실패');writes.push(JSON.parse(JSON.stringify(value)));},async writeAppData(value){if(failWrite)throw Error('저장 실패');writes.push(JSON.parse(JSON.stringify(value)));},async deletePrivateMedia(){},async deleteMedia(){}}
  };context.window=context;vm.createContext(context);vm.runInContext(read('photo-attachments-v176.js'),context);context.AiderLogPhotosV176.compressPhoto=async f=>f;
  const source=read('android-src/assets/app-feature-v152b.js'),start=source.indexOf('window.saveEventEditorV111 = async function (form) {'),end=source.indexOf('\n  };',start);vm.runInContext(source.slice(start,end+5),context);
  vm.runInContext(read('android-src/assets/app-photo-attachments-v176.js'),context);
  function select(id,names){const input=elements[id];input.id=id;input.files=names.map(name=>({name,size:100,lastModified:1,type:'image/jpeg'}));events.change({target:input,stopImmediatePropagation(){}});}
  function eventForm(kind='record',values={}){const form=new Element('form');form.submit=new Element('button');form.dataset={kind,id:''};form.values=values;elements.eventPhotoV111.form=form;return form;}
  return {context,elements,uploads,writes,select,eventForm,setUploadFailure:name=>failUpload=name,setWriteFailure:value=>failWrite=value};
}
test('actual mobile change handler processes every selected photo; per-file error prevents record commit',async()=>{const h=harness();h.context.AiderLogAppPhotosV176.resetPersonal();h.select('personalPhoto',['one.jpg','bad.jpg','three.jpg']);h.setUploadFailure('bad.jpg');await h.context.AiderLogAppPhotosV176.savePersonal({id:'p1',title:'식사',category:'health',details:{mealType:'lunch'}});assert.equal(h.writes.length,0);assert.equal(h.context.P.personalItems.length,0);assert.deepEqual(h.uploads,['one.jpg','bad.jpg','three.jpg']);assert.equal(h.elements.personalModal.closed,undefined);assert.equal(h.elements.personalForm.submit.disabled,false);h.setUploadFailure('');await h.context.AiderLogAppPhotosV176.savePersonal({id:'p1',title:'식사',category:'health',details:{mealType:'lunch'}});assert.equal(h.writes.length,1);assert.equal(h.writes[0].personalItems[0].mediaItems.length,3);assert.deepEqual(h.uploads,['one.jpg','bad.jpg','three.jpg','bad.jpg']);assert.equal(h.elements.personalModal.closed,true);});
test('actual mobile persistence failure keeps upload results and retries without duplicated media',async()=>{const h=harness();h.context.AiderLogAppPhotosV176.resetPersonal();h.select('personalPhoto',['a.jpg','b.jpg']);h.setWriteFailure(true);await h.context.AiderLogAppPhotosV176.savePersonal({id:'p1'});assert.equal(h.context.P.personalItems.length,0);assert.equal(h.uploads.length,2);h.setWriteFailure(false);await h.context.AiderLogAppPhotosV176.savePersonal({id:'p1'});assert.equal(h.context.P.personalItems.length,1);assert.equal(h.uploads.length,2);});
test('actual Event writer preserves form and prior rows on Firebase failure, then saves full gallery',async()=>{const h=harness();h.context.openEventEditorV111('record');const form=h.eventForm('record',{title:'여행 사진',body:'본문',date:'2026-09-12'});h.select('eventPhotoV111',['a.jpg','b.jpg']);h.setWriteFailure(true);await h.context.saveEventEditorV111(form);assert.equal(h.context.A.records.length,0);assert.ok(h.context.eventEditorV111);assert.equal(form.values.body,'본문');h.setWriteFailure(false);await h.context.saveEventEditorV111(form);assert.equal(h.context.A.records.length,1);assert.equal(h.context.A.records[0].mediaItems.length,2);assert.equal(h.context.A.records[0].title,'여행 사진');assert.equal(h.uploads.length,2);assert.equal(h.context.eventEditorV111,null);});
test('actual Travel/Archive writer retains purpose fields with multi photos',async()=>{const h=harness();h.context.openEventEditorV111('review','','travel','food');const form=h.eventForm('review',{category:'travel',travelType:'food',title:'식당',menu:'메뉴',favoriteMenu:'기억할 메뉴',place:'장소',review:'기록'});h.select('eventPhotoV111',['a.jpg','b.jpg']);await h.context.saveEventEditorV111(form);assert.equal(h.context.A.eventReviews[0].menu,'메뉴');assert.equal(h.context.A.eventReviews[0].favoriteMenu,'기억할 메뉴');assert.equal(h.context.A.eventReviews[0].mediaItems.length,2);});
test('account changes during photo compression never upload old photos to the new account',async()=>{const h=harness();let resolve;h.context.AiderLogPhotosV176.compressPhoto=()=>new Promise(r=>resolve=r);h.context.AiderLogAppPhotosV176.resetPersonal();h.select('personalPhoto',['a.jpg']);const pending=h.context.AiderLogAppPhotosV176.savePersonal({id:'a-record'});h.context.authState={user:{uid:'b',email:'b@example.test'}};resolve({name:'a.jpg',type:'image/jpeg'});await pending;assert.equal(h.uploads.length,0);assert.equal(h.writes.length,0);assert.equal(h.context.P.personalItems.length,0);});
test('failed mobile record deletion preserves every photo and record',async()=>{const h=harness();let deletes=0;h.context.fb.deletePrivateMedia=async()=>deletes++;h.context.P.personalItems=[{id:'p',media:{fileId:'a'},mediaItems:[{fileId:'a'},{fileId:'b'}]}];h.setWriteFailure(true);await h.context.AiderLogAppPhotosV176.deletePersonal('p');assert.equal(h.context.P.personalItems.length,1);assert.equal(deletes,0);h.setWriteFailure(false);await h.context.AiderLogAppPhotosV176.deletePersonal('p');assert.equal(h.context.P.personalItems.length,0);assert.equal(deletes,2);});
test('malformed upload success without a photo identifier preserves the form and retries',async()=>{for(const response of [undefined,null,{localFixture:true},{id:''},{id:'   '},{id:123}]){const h=harness();h.context.AiderLogAppPhotosV176.resetPersonal();h.select('personalPhoto',['a.jpg']);h.context.fb.uploadPrivateMedia=async()=>response;await h.context.AiderLogAppPhotosV176.savePersonal({id:'p'});assert.equal(h.writes.length,0);assert.equal(h.context.P.personalItems.length,0);assert.equal(h.elements.personalModal.closed,undefined);h.context.fb.uploadPrivateMedia=async()=>({id:'valid-photo'});await h.context.AiderLogAppPhotosV176.savePersonal({id:'p'});assert.equal(h.writes[0].personalItems[0].media.fileId,'valid-photo');}});
test('Event malformed upload success cannot commit an empty gallery',async()=>{const h=harness();h.context.openEventEditorV111('record');const form=h.eventForm('record',{title:'사진',body:'본문'});h.select('eventPhotoV111',['a.jpg']);h.context.fb.uploadMedia=async()=>({localFixture:true});await h.context.saveEventEditorV111(form);assert.equal(h.writes.length,0);assert.equal(h.context.A.records.length,0);assert.ok(h.context.eventEditorV111);assert.equal(form.values.body,'본문');});
