const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),holder={exports:{}};new Function('module','window',fs.readFileSync(path.join(root,'photo-attachments-v176.js'),'utf8'))(holder,{});const photos=holder.exports;
function file(name='one.jpg',type='image/jpeg',size=100){return {name,type,size,lastModified:1};}
test('batch accepts multiple distinct images and does not duplicate re-selection',()=>{const b=photos.createBatch();b.add([file(),file('two.png')]);b.add([file()]);assert.equal(b.count,2);assert.equal(b.add([file('bad.pdf','application/pdf')]).length,1);assert.equal(b.add([file('large.jpg','image/jpeg',26*1024*1024)]).length,1);assert.equal(b.count,2);});
test('maximum is explicit and does not silently replace existing attachments',()=>{const b=photos.createBatch({limit:3});assert.equal(b.add([1,2,3,4].map(x=>file(x+'.jpg'))).length,1);assert.equal(b.count,3);});
test('successful uploads are retained and only failures retry',async()=>{let calls=[];const b=photos.createBatch({owner:()=> 'a'});b.add([file(),file('two.jpg'),file('three.jpg')]);let fail=true;const upload=async f=>{calls.push(f.name);if(f.name==='two.jpg'&&fail)throw Error('offline');return {fileId:f.name};};await assert.rejects(b.upload(upload),/1장 업로드 실패/);assert.deepEqual(calls,['one.jpg','two.jpg','three.jpg']);assert.equal(b.entries[1].error,'offline');fail=false;const rows=await b.upload(upload);assert.equal(rows.length,3);assert.deepEqual(calls,['one.jpg','two.jpg','three.jpg','two.jpg']);});
test('removing a failed item keeps other uploads without resubmission',async()=>{const b=photos.createBatch();b.add([file(),file('bad.jpg')]);let calls=0;await assert.rejects(b.upload(async f=>{calls++;if(f.name==='bad.jpg')throw Error('failed');return {fileId:'ok'};}));b.remove(b.entries[1].key);assert.deepEqual(await b.upload(()=>{throw Error('must not retry');}),[{fileId:'ok'}]);assert.equal(calls,2);});
test('account switch rejects late completion and cannot enter next account records',async()=>{let actor='a',resolve;const b=photos.createBatch({owner:()=>actor});b.add([file()]);const pending=b.upload(()=>new Promise(r=>resolve=r));actor='b';resolve({fileId:'private-a'});await assert.rejects(pending,/계정/);assert.equal(b.entries[0].uploaded,undefined);});
test('new draft reset cleans a late upload from same account without touching saved files',async()=>{const removed=[];let resolve;const b=photos.createBatch({owner:()=> 'a',remove:async id=>removed.push(id)});b.reset([{fileId:'saved'}]);b.add([file()]);const pending=b.upload(()=>new Promise(r=>resolve=r));b.reset();resolve({fileId:'orphan'});await assert.rejects(pending);await new Promise(r=>setImmediate(r));assert.deepEqual(removed,['orphan']);});
test('deferred deletion only happens after record commit; cancelling preserves original media',async()=>{const removed=[],b=photos.createBatch({owner:()=> 'a',remove:async id=>removed.push(id)});b.reset([{fileId:'old1'},{fileId:'old2'}]);b.remove('saved-0');assert.deepEqual(removed,[]);b.reset([{fileId:'old1'},{fileId:'old2'}]);b.remove('saved-0');b.committed();await new Promise(r=>setImmediate(r));assert.deepEqual(removed,['old1']);b.reset();assert.deepEqual(removed,['old1']);});
test('fields preserve primary media for existing widgets and arrays for galleries',()=>{const items=[{fileId:'a'},{fileId:'b'}],row=photos.fields(items);assert.deepEqual(row.media,items[0]);assert.deepEqual(photos.mediaItems(row),items);assert.deepEqual(photos.mediaItems({media:items}),items);assert.deepEqual(photos.fields([]),{media:null,mediaItems:[],localImage:''});});
test('gallery download rejects executable URLs and accepts only image data/blob/http sources',()=>{for(const url of ['javascript:alert(1)','data:text/html;base64,QQ==','file:///secret','vbscript:test'])assert.equal(photos.safeSource(url),'');for(const url of ['blob:local','data:image/jpeg;base64,QQ==','https://example.test/photo.jpg'])assert.equal(photos.safeSource(url),url);});
test('site record arrays take priority over stale legacy gallery metadata',()=>{assert.deepEqual(photos.mediaItems({media:[{fileId:'current'}],mediaItems:[{fileId:'old'}]}),[{fileId:'current'}]);assert.equal(photos.mediaItems({localImage:'data:image/jpeg;base64,QQ=='})[0].localImage,'data:image/jpeg;base64,QQ==');});
test('Android chooser requests multi selection and reads every ClipData URI',()=>{const chrome=fs.readFileSync(path.join(root,'android-src/smali/MainActivity$AiderLogChromeClient.smali'),'utf8'),activity=fs.readFileSync(path.join(root,'android-src/smali/MainActivity.smali'),'utf8');assert.match(chrome,/ALLOW_MULTIPLE/);assert.match(chrome,/getMode/);assert.match(activity,/getClipData/);assert.match(activity,/getItemCount/);assert.match(activity,/getItemAt/);});
test('site and app use batch save paths while retaining original entry fields',()=>{const site=fs.readFileSync(path.join(root,'index.html'),'utf8'),app=fs.readFileSync(path.join(root,'android-src/assets/index.html'),'utf8'),adapter=fs.readFileSync(path.join(root,'android-src/assets/app-photo-attachments-v176.js'),'utf8');assert.match(site,/id="personalPhotoInput"[^>]*multiple/);assert.match(site,/id="eventPhotoInput"[^>]*multiple/);assert.match(site,/personalPhotosV176\.upload/);assert.match(site,/eventPhotosV176\.upload/);assert.match(site,/media,mediaItems,createdAt/);assert.match(app,/AiderLogAppPhotosV176\.savePersonal\(row\)/);assert.match(adapter,/writePrivateData/);assert.match(adapter,/writeAppData/);assert.match(adapter,/event\.stopImmediatePropagation/);assert.match(adapter,/eventBatch\.committed\(\)/);});
