import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {mergeProviderRows} from '../server/calendar-rows-v184.mjs';
import {encodeStoredPayload,decodeArchive} from '../archive-codec-v168.js';
const read=file=>fs.readFileSync(new URL('../'+file,import.meta.url),'utf8').replace(/\r\n/g,'\n'),site=read('index.html'),firebase=read('firebase-app.js');
function section(source,start,end){const a=source.indexOf(start),b=source.indexOf(end,a+start.length);assert(a>=0&&b>a,start);return source.slice(a,b);}
function normalize(){const context={PRIVATE_VERSION:190,normalizeEmail:value=>String(value||'').trim().toLowerCase(),normalizeName:value=>String(value||''),window:{AiderLogPhotosV176:{mediaItems:row=>row.mediaItems||[]},AiderLogRetiredFeaturesV178:{cleanPrivate:data=>data}}};vm.createContext(context);vm.runInContext(section(site,'  function blankPrivateData(','  function privateFolderName(')+'\nglobalThis.normalize=normalizePrivateData;',context);return context.normalize;}
const dated=(i,prefix)=>({id:prefix+i,title:'오래된 기록 '+i,date:'2010-01-01',createdAt:1262304000000,extra:{attachment:'original-'+i}});
test('site normalization preserves old and large collections, full text and nested attachment metadata',()=>{
 const long='원본 내용\n'.repeat(3000),checks=Object.fromEntries(Array.from({length:701},(_,i)=>[new Date(Date.UTC(2010,0,i+1)).toISOString().slice(0,10),1]));
 const source={personalItems:Array.from({length:1201},(_,i)=>({...dated(i,'personal'),category:'health',note:long,details:{healthType:'exercise',customDetail:{keep:true},paymentChecks:checks,steps:Array(45).fill('긴 단계'),exercises:Array.from({length:40},(_,n)=>({name:'운동'+n,sets:Array(40).fill({weight:20,reps:10})}))}})),paperItems:Array.from({length:601},(_,i)=>({...dated(i,'paper'),summary:long,neuroProfile:{customNeuro:'keep'}})),researchInsights:Array.from({length:1601},(_,i)=>({...dated(i,'insight'),content:long,locator:{printedPage:'2',customLocation:'keep'},scope:{customScope:'keep'}})),researchNotes:Array.from({length:601},(_,i)=>({...dated(i,'note'),content:long})),researchDesigns:Array.from({length:401},(_,i)=>dated(i,'design')),researchComparisons:Array.from({length:301},(_,i)=>dated(i,'comparison')),researchConnections:Array.from({length:3101},(_,i)=>({...dated(i,'connection'),sourceId:'a',targetId:'b'})),paperConceptFolders:Array.from({length:61},(_,i)=>({id:'folder'+i,name:'폴더'+i,conceptKeys:Array.from({length:601},(_,n)=>'concept'+n)})),pomodoroSessions:Array.from({length:601},(_,i)=>({...dated(i,'pomo'),task:long})),languageStudy:{history:['preserve retired data']}};
 const actual=normalize()(source,'owner@example.test','Owner');for(const key of Object.keys(source))if(Array.isArray(source[key]))assert.equal(actual[key].length,source[key].length,key);
 assert.equal(actual.personalItems[0].note,long);assert.equal(actual.personalItems[0].details.exercises.length,40);assert.equal(actual.personalItems[0].details.exercises[0].sets.length,40);assert.equal(actual.personalItems[0].details.steps.length,45);assert.equal(Object.keys(actual.personalItems[0].details.paymentChecks).length,701);assert.equal(actual.personalItems[0].extra.attachment,'original-0');assert(actual.personalItems[0].details.customDetail.keep);assert.equal(actual.paperItems[0].summary,long);assert.equal(actual.paperItems[0].neuroProfile.customNeuro,'keep');assert.equal(actual.researchInsights[0].locator.customLocation,'keep');assert.equal(actual.researchInsights[0].scope.customScope,'keep');assert.equal(actual.paperConceptFolders[0].conceptKeys.length,601);assert.equal(actual.pomodoroSessions[0].task,long);assert.equal(actual.languageStudy.history[0],'preserve retired data');
});
test('old direct mail and formerly ephemeral photos stay visible without deletion callbacks',()=>{
 const old=Date.UTC(2001,0,1),docRow={id:'old-mail',data:()=>({createdAt:old,body:'preserve',memberUids:['owner','friend']})};let recomputed=0;
 const context={db:{},user:{uid:'owner'},collection:()=>({}),where:()=>({}),query:()=>({}),plainDoc:d=>({id:d.id,...d.data()}),timestampValue:Number,recomputeState:()=>recomputed++,directLetterRows:[],unsubscribeDirectLetters:null,onSnapshot:(q,fn)=>{fn({docs:[docRow]});return()=>{};}};
 vm.createContext(context);vm.runInContext(section(firebase,'  unsubscribeDirectLetters = onSnapshot(','\n}\n\nfunction requireUser'),context);assert.equal(context.directLetterRows.length,1);assert.equal(context.directLetterRows[0].body,'preserve');assert.equal(recomputed,1);
 let received;context.requireUser=()=>({uid:'owner'});context.onSnapshot=(q,fn)=>fn({docs:[{id:'old-photo',data:()=>({createdAt:old,expiresAt:old+86400000,ready:true,createdByUid:'owner'})}]});context.console=console;vm.runInContext(section(firebase,'function watchEphemeralMedia(','\nfunction privateMediaRef(')+'\nglobalThis.watch=watchEphemeralMedia;',context);context.watch(rows=>received=rows);assert.equal(received.length,1);assert.equal(received[0].id,'old-photo');
 assert.doesNotMatch(firebase,/cleanupExpiredDirectLetters|DIRECT_LETTER_RETENTION_MS|expiredOwned|EPHEMERAL_MEDIA_TTL_MS/);assert.doesNotMatch(site,/cleanupExpiredLegacyLetters|MAIL_RETENTION_MS|row\.expiresAt>now/);
});
test('new shared photo metadata has no expiry and existing old photos remain readable',async()=>{
 const writes=[],context={db:{},Blob,Uint8Array,crypto:{randomUUID:()=> 'test-id'},requireUser:()=>({uid:'owner',email:'o@test',name:'Owner'}),connectedRecipientUids:()=>new Set(['friend']),compressImage:async x=>x,videoDurationSeconds:async()=>0,ephemeralMediaRef:id=>({id}),setDoc:async(ref,value)=>writes.push({ref,value}),updateDoc:async(ref,value)=>writes.push({ref,value}),serverTimestamp:()=>123,collection:()=>({}),doc:(c,id)=>({id}),Bytes:{fromUint8Array:x=>x},writeBatch:()=>({set(){},async commit(){}}),deleteEphemeralMedia:()=>assert.fail('successful file cannot be deleted'),Date,Math,Error};
 vm.createContext(context);vm.runInContext(section(firebase,'async function uploadEphemeralMedia(','\nasync function readEphemeralMedia(')+'\nglobalThis.upload=uploadEphemeralMedia;',context);const file=new Blob(['photo'],{type:'image/jpeg'});file.name='original.jpg';const result=await context.upload(file,['friend']);assert.equal(writes[0].value.name,'original.jpg');assert.equal(Object.hasOwn(writes[0].value,'expiresAt'),false);assert.equal(result.permanent,true);assert.equal(writes.at(-1).value.ready,true);
 const rules=read('firestore.rules'),media=section(rules,'    match /ephemeralMedia/','    match /clientIntakeLinks/');assert.match(media,/!\('expiresAt' in request\.resource\.data\)/);assert.doesNotMatch(media,/expiresAt > request\.time|expiresAt ==/);assert.doesNotMatch(section(firebase,'async function readEphemeralMedia(','\nasync function deleteEphemeralMedia('),/expiresAt|Date\.now/);
});
test('shared albums retain all 260 records and nine attachments; failed copies cannot replace old snapshot',async()=>{
 let failCopy=false;const writes=[],prunes=[],context={requireUser:()=>({uid:'owner',email:'owner@test',name:'Owner'}),connectedRecipientUids:()=>new Set(['friend']),TextEncoder,Map,Set,Array,String,Error,copyMediaToSharedAlbum:async id=>{if(failCopy)throw Error('network');return id;},setDoc:async(ref,data)=>writes.push(data),doc:()=>({}),db:{},serverTimestamp:()=>1,pruneSharedAlbumMedia:async(...args)=>prunes.push(args)};vm.createContext(context);vm.runInContext(section(firebase,'async function publishSharedAlbums(','\nfunction watchSharedAlbums(')+'\nglobalThis.publish=publishSharedAlbums;',context);
 const payload={albums:Array.from({length:41},(_,i)=>({id:'album'+i,name:'보관함',sharedWithFriends:true})),records:Array.from({length:260},(_,i)=>({id:'row'+i,folderId:'album'+i%41,title:'제목'.repeat(70),body:i===0?'본문'.repeat(400):'기록',date:'2000-01-01',media:Array.from({length:9},(_,n)=>({fileId:`m${i}-${n}`,name:'원본'+n,type:'image/jpeg'}))}))};
 await context.publish(payload);assert.equal(writes[0].albums.length,41);assert.equal(writes[0].records.length,260);assert.equal(writes[0].records[0].media.length,9);assert.equal(writes[0].records[0].body,payload.records[0].body);assert.equal(writes[0].records[0].title,payload.records[0].title);assert.equal(prunes.length,1);
 failCopy=true;await assert.rejects(context.publish(payload),/기존 공유 기록은 유지/);assert.equal(writes.length,1);assert.equal(prunes.length,1);
});
test('private saves preserve fields omitted by older clients and retain explicit empty-array edits',async()=>{
 const current={profile:{name:'Old'},unknownRecords:[{id:'keep',text:'private record'}],languageStudy:{history:['keep']},memos:[{id:'delete-me'}]},updates=[];
 const context={doc:()=>({}),db:{},auth:{currentUser:{uid:'owner'}},runTransaction:async(db,fn)=>fn({get:async()=>({exists:()=>true,data:()=>({payload:current})}),update:(ref,...fields)=>updates.push(fields)}),decodeArchive:x=>x,encodeArchive:x=>x,CONSULT_KEYS:[],mergePrivateNotesV179:(old,next)=>({memos:next.memos||old.memos}),FieldPath:class{constructor(...parts){this.parts=parts}},serverTimestamp:()=>123,JSON,Object,Error};vm.createContext(context);
 const code=section(firebase,'  writeRemaining:async(','\n  }\n});').replace('  writeRemaining:','globalThis.writeRemaining=')+'\n  };';vm.runInContext(code,context);const result=await context.writeRemaining('owner',{profile:{name:'New'},memos:[]});assert.equal(result.unknownRecords[0].id,'keep');assert.equal(result.languageStudy.history[0],'keep');assert.equal(result.memos.length,0);assert.equal(result.profile.name,'New');assert.equal(updates.length,1);
});
test('Google refresh preserves out-of-window records and all 700 incoming rows, while covered source deletions are reflected',()=>{
 const old=[{id:'ancient',externalSource:'google',calendarId:'google:one',date:'2000-01-01'},{id:'future',externalSource:'google',calendarId:'google:one',date:'2099-01-01'},{id:'other-calendar',externalSource:'google',calendarId:'google:two',date:'2026-01-01'},{id:'source-deleted',externalSource:'google',calendarId:'google:one',date:'2026-01-02'},{id:'mine',date:'2026-01-02'}],incoming=Array.from({length:700},(_,i)=>({id:'incoming'+i,externalSource:'google',calendarId:'google:one',date:'2026-01-01'}));const result=mergeProviderRows(old,'google',incoming,'owner','o@test',{from:'2025-01-01',to:'2028-01-01',calendarIds:['google:one']});assert.equal(result.length,704);for(const id of ['ancient','future','other-calendar','mine'])assert(result.some(r=>r.id===id));assert(!result.some(r=>r.id==='source-deleted'));assert.doesNotMatch(read('api/calendar-sync.mjs'),/\.slice\(0, 600\)|\.slice\(-600\)/);
});
test('app quota errors reject saving, preserve the local draft and cannot report a false success',async()=>{
 const cache=new Map(),messages=[],context={authState:{user:{uid:'owner'}},toast:message=>messages.push(message),localStorage:{setItem:(key,value)=>cache.set(key,value)},JSON};vm.createContext(context);vm.runInContext(section(read('android-src/assets/index.html'),'async function persistRecordV190(','async function saveApp(')+'globalThis.persist=persistRecordV190;',context);const original={records:[{id:'old',body:'keep'}]},draft={records:[...original.records,{id:'new',body:'unsaved full input'}]};cache.set('records',JSON.stringify(original));await assert.rejects(context.persist('records',draft,async()=>{throw Error('resource-exhausted');}),/resource-exhausted/);assert.deepEqual(JSON.parse(cache.get('records')),draft);assert.equal(messages.length,1);context.localStorage.setItem=()=>{throw Error('QuotaExceededError')};let remote;await context.persist('records',draft,async value=>{remote=value});assert.equal(remote,draft);context.authState.user=null;await assert.rejects(context.persist('records',draft,null),/QuotaExceededError/);
});
test('partial-day Google query boundaries cannot remove unfetched events',()=>{
 const old=[{id:'before-start',date:'2025-09-20',time:'08:00'},{id:'boundary-start',date:'2025-09-20',time:'11:00'},{id:'inside-deleted',date:'2026-06-01'},{id:'boundary-end',date:'2028-09-20',time:'11:00'}].map(row=>({...row,calendarId:'google:one',externalSource:'google'}));
 const actual=mergeProviderRows(old,'google',[],'owner','o@test',{from:'2025-09-20T09:00:00Z',to:'2028-09-20T09:00:00Z',calendarIds:['google:one']});
 assert.deepEqual(actual.map(row=>row.id),['before-start','boundary-start','boundary-end']);
 assert.match(site,/String\(row\.endDate\|\|row\.date\|\|''\)<=timeMin\.slice\(0,10\)/);
 assert.match(site,/String\(row\.date\|\|''\)>=timeMax\.slice\(0,10\)/);
});
test('Notion pagination imports every page and incomplete imports cannot replace stored records',async()=>{
 const source=read('api/calendar-sync.mjs');let count=0,writes=[];
 const context={integrationRef:()=>({get:async()=>({data:()=>({accessToken:'token',sourceId:'db'})}),set:async()=>{}}),notionJson:async()=>{count++;return {results:[{id:'p'+count,properties:{title:{type:'title',title:[{plain_text:'A title'}]},date:{type:'date',date:{start:'2000-01-01'}}}}],has_more:count<1002,next_cursor:'next'+count}},notionValue:property=>property?.title?.map(x=>x.plain_text).join('')||'',cleanText:String,replaceProviderRows:async(...args)=>writes.push(args),FieldValue:{serverTimestamp:()=>1}};vm.createContext(context);vm.runInContext(section(source,'async function syncNotion(','\nasync function startConnection(')+'globalThis.sync=syncNotion;',context);
 await context.sync('owner');assert.equal(count,1002);assert.equal(writes[0][2].length,1002);assert.deepEqual(Array.from(writes[0][3].calendarIds),['notion:db']);
 context.notionJson=async()=>({results:[],has_more:true,next_cursor:null});await assert.rejects(context.sync('owner'),/기존 일정은 유지/);assert.equal(writes.length,1);
 const old=[{id:'different-source',calendarId:'notion:other',externalSource:'notion',date:'2000-01-01'},{id:'deleted',calendarId:'notion:db',externalSource:'notion',date:'2000-01-01'}];assert.deepEqual(mergeProviderRows(old,'notion',[],'owner','o@test',{calendarIds:['notion:db']}).map(row=>row.id),['different-source']);
});
test('lossless quarterly archives still round-trip every old record and attachment reference',()=>{
 const records={personalItems:Array.from({length:1201},(_,i)=>({...dated(i,'old'),note:'preserve complete original '.repeat(30),mediaItems:[{fileId:'photo'+i,type:'image/jpeg'}]})),routineHistory:Object.fromEntries(Array.from({length:500},(_,i)=>[new Date(Date.UTC(2010,0,i+1)).toISOString().slice(0,10),{level:'MINI',note:'record'+i}]))};const packed=encodeStoredPayload(records,{now:Date.UTC(2030,0,1)});assert.deepEqual(decodeArchive(packed),records);assert(JSON.stringify(packed).length<JSON.stringify(records).length);
});
test('app queues and retired-tool records no longer get silently discarded; shipped JavaScript compiles',()=>{
 assert.doesNotMatch(read('android-src/assets/mobile-paper-v159.js'),/slice\(-200\)|slice\(-500\)/);assert.doesNotMatch(read('android-src/assets/study-card-v1.js'),/slice\(-5000\)/);const speech=read('android-src/assets/my-suite-v145.js');assert.doesNotMatch(speech,/name="autoDeleteDays"|name="keepTranscript"|autoDeleteDays:30/);assert.match(speech,/autoDeleteDays:0,keepTranscript:true/);assert.match(speech,/function storeTrainingRecord[\s\S]*throw new Error/);
 for(const file of ['firebase-app.js','retired-features-v178.js'])assert.equal(read(file),read('android-src/assets/'+file));
 for(const file of ['my-suite-v145.js','mobile-paper-v159.js','study-card-v1.js','app-feature-v152b.js','feature-system-v125.js','routine-v111.js','my-workspaces-v128.js','retired-features-v178.js'])assert.doesNotThrow(()=>new vm.Script(read('android-src/assets/'+file)));
 for(const html of [site,read('android-src/assets/index.html')])for(const script of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g))if(!/\bsrc=|type=["'](?:module|application\/)/i.test(script[1]))assert.doesNotThrow(()=>new vm.Script(script[2]));
});
