const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright')}catch{playwright=require(process.env.PLAYWRIGHT_MODULE_PATH||path.join(process.env.USERPROFILE||require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
const root=path.resolve(process.env.AIDERLOG_APP_ASSETS||path.join(__dirname,'../android-src/assets')),out=path.resolve(process.env.AIDERLOG_QA_OUT||path.join(__dirname,'../work/qa-routine-steps-v195'));fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.gif':'image/gif','.jpg':'image/jpeg','.webp':'image/webp','.json':'application/json','.webmanifest':'application/manifest+json'};
(async()=>{const browser=await playwright.chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'msedge'}),context=await browser.newContext({viewport:{width:384,height:900},isMobile:true,hasTouch:true,timezoneId:'Asia/Seoul',serviceWorkers:'block'}),page=await context.newPage(),errors=[],missing=[],checks=[];
 const pass=name=>{checks.push(name);console.log('PASS',name)};
 async function fixture(){await page.waitForFunction(()=>window.AiderRoutineStepsV195);await page.evaluate(()=>{window.__writes=0;window.__fail=false;authState={user:{uid:'routine-qa',email:'routine@example.invalid'},ready:true,pair:null};privateDataOwnerV179='routine-qa';privateDataValueV179=P;fb={getState:()=>authState,writePrivateData:async value=>{window.__writes++;if(window.__fail)throw Error('검증 저장 실패');return value}};window.AiderDearFirebase=fb;go('routine',false);window.AiderRoutineStepsV195.refresh()})}
 try{
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!=='http://routine-steps.invalid'||route.request().method()!=='GET')return route.abort();const rel=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname).slice(1),file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){missing.push(rel);return route.fulfill({status:404,body:''})}return route.fulfill({status:200,contentType:mime[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)})});
  await page.addInitScript(()=>{window.__now=Date.parse('2026-09-27T23:59:00+09:00');const D=Date;window.Date=class extends D{constructor(...args){super(...(args.length?args:[window.__now]))}static now(){return window.__now}};sessionStorage.setItem('aiderlog-splash-shown-session-v150','1');if(!localStorage.getItem('aiderlog-private-v20'))localStorage.setItem('aiderlog-private-v20',JSON.stringify({routines:[{id:'legacy',text:'기존 루틴',icon:'✨',goalDays:20,doneDates:['2026-09-26'],dailyLevels:{'2026-09-26':'MAX'},unknown:{keep:'yes'},goalTracking:{0:{old:'preserve'}}}],personalItems:[{id:'historical',category:'health',title:'옛 기록'}]}));});
  await page.goto('http://routine-steps.invalid/',{waitUntil:'networkidle'});await fixture();
  await page.locator('[data-r195-edit="legacy"]').click();assert.equal(await page.locator('[data-r195-step]').count(),0);await page.locator('#routineEditorFormV111 [name="text"]').fill('기존 루틴 수정');await page.locator('button[form="routineEditorFormV111"][type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('#routineEditorFormV111'));assert.deepEqual(await page.evaluate(()=>P.routines.find(r=>r.id==='legacy').unknown),{keep:'yes'});assert.equal(await page.evaluate(()=>P.routines.find(r=>r.id==='legacy').dailyLevels['2026-09-26']),'MAX');pass('Legacy editor preserves unknown fields, goals and old completion');
  await page.locator('[data-routine-create-open]:visible').click();const form=page.locator('#routineEditorFormV111');await form.locator('[name="text"]').fill('아침 세 단계');
  for(const title of ['물 마시기','스트레칭','책 읽기']){await page.locator('[data-r195-add]').click();await page.locator('[data-r195-step]').last().locator('[data-r195-title]').fill(title)}
  await page.locator('[data-r195-step]').last().locator('[data-r195-move="-1"]').click();assert.deepEqual(await page.locator('[data-r195-title]').evaluateAll(es=>es.map(e=>e.value)),['물 마시기','책 읽기','스트레칭']);
  await page.locator('[data-r195-add]').click();await page.locator('[data-r195-step]').last().locator('[data-r195-title]').fill('삭제할 단계');await page.locator('[data-r195-step]').last().locator('[data-r195-delete]').click();assert.equal(await page.locator('[data-r195-step]').count(),3);
  await page.evaluate(()=>__fail=true);await page.locator('button[form="routineEditorFormV111"][type="submit"]').click();await page.waitForFunction(()=>document.querySelector('[data-r195-save-error]')?.textContent.includes('실패'));assert.equal(await page.locator('[data-r195-step]').count(),3);assert(!(await page.evaluate(()=>P.routines.some(r=>r.text==='아침 세 단계'))));assert(!(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiderlog-private-v20')).routines.some(r=>r.text==='아침 세 단계'))));pass('Failed editor save retains step draft and rolls back record/cache');
  await page.evaluate(()=>__fail=false);await page.locator('button[form="routineEditorFormV111"][type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('#routineEditorFormV111'));
  const id=await page.evaluate(()=>P.routines.find(r=>r.text==='아침 세 단계').id);assert.deepEqual(await page.evaluate(id=>P.routines.find(r=>r.id===id).steps.map(s=>s.title),id),['물 마시기','책 읽기','스트레칭']);pass('Create, reorder and delete steps save in the existing routine record');
  await page.evaluate(id=>{routineEditorIdV111=id;renderRoutine()},id);await page.locator('button[form="routineEditorFormV111"][type="submit"]').waitFor();
  const editorGeometry=await page.locator('button[form="routineEditorFormV111"][type="submit"]').evaluate(button=>({width:button.getBoundingClientRect().width,whiteSpace:getComputedStyle(button).whiteSpace,footerHeight:document.querySelector('#routineEditorFormV111>.routine-detail-actions').getBoundingClientRect().height}));assert(editorGeometry.width>=76);assert.equal(editorGeometry.whiteSpace,'nowrap');assert.equal(editorGeometry.footerHeight,0);
  await page.locator('.r195-step-editor').evaluate(section=>section.parentElement.scrollTop=section.offsetTop-section.parentElement.offsetTop);await page.screenshot({path:path.join(out,'step-editor-384.png'),fullPage:true});const lastDelete=page.locator('[data-r195-delete]').last();await lastDelete.scrollIntoViewIfNeeded();assert(await lastDelete.evaluate(button=>{const b=button.getBoundingClientRect();return document.elementFromPoint(b.x+b.width/2,b.y+b.height/2)?.closest('[data-r195-delete]')===button}));assert(!(await page.locator('#wheel').isVisible()));await page.locator('[data-routine-editor-close]:visible').click();assert(await page.locator('#wheel').isVisible());pass('Step editor has readable save action, no empty footer and unobstructed bottom controls');
  await page.screenshot({path:path.join(out,'practice-384.png'),fullPage:true});await page.locator('[data-r195-run="'+id+'"]').click();const runner=page.locator('#routineRunnerV195');await runner.locator('[data-r195-action="toggle"]').click();const writes=await page.evaluate(()=>__writes);await page.evaluate(()=>__now+=12000);await page.evaluate(()=>AiderRoutineStepsV195.refresh());assert.equal(await runner.locator('[data-r195-clock]').textContent(),'0:48');await runner.locator('[data-r195-action="toggle"]').click();await page.evaluate(()=>__now+=30000);await page.evaluate(()=>AiderRoutineStepsV195.refresh());assert.equal(await runner.locator('[data-r195-clock]').textContent(),'0:48');assert.equal(await page.evaluate(()=>__writes),writes);pass('Wall-clock countdown and pause/resume perform no cloud writes');
  await page.reload({waitUntil:'networkidle'});await fixture();await page.locator('[data-r195-run="'+id+'"]').click();assert.equal(await runner.locator('[data-r195-clock]').textContent(),'0:48');await runner.locator('[data-r195-action="toggle"]').click();await page.evaluate(()=>__now+=120000);await page.evaluate(()=>AiderRoutineStepsV195.refresh());assert.equal(await runner.locator('[data-r195-clock]').textContent(),'0:00');assert.equal(await page.evaluate(()=>AiderRoutineStepsV195.getRun().index),0);assert.equal(await page.evaluate(()=>AiderRoutineStepsV195.getRun().date),'2026-09-27');assert.equal(await page.evaluate(()=>__writes),0);pass('Reload and midnight resume retain start day; expiration never silently completes a step');
  await page.screenshot({path:path.join(out,'runner-384.png'),fullPage:true});await runner.locator('[data-r195-action="done"]').click();await runner.locator('[data-r195-action="skip"]').click();await runner.locator('[data-r195-action="done"]').click();await page.evaluate(()=>__fail=true);await runner.locator('[data-r195-action="save"]').click();await page.waitForFunction(()=>document.querySelector('#routineRunnerV195 .r195-error').textContent.includes('실패'));assert(await runner.isVisible());assert.equal(await page.evaluate(()=>AiderRoutineStepsV195.getRun().state),'review');assert.equal(await page.evaluate(id=>P.routines.find(r=>r.id===id).dailyLevels['2026-09-27'],id),undefined);assert.equal(await page.evaluate(id=>JSON.parse(localStorage.getItem('aiderlog-private-v20')).routines.find(r=>r.id===id).dailyLevels['2026-09-27'],id),undefined);pass('Failed finish keeps retryable run and never claims completion');
  await page.evaluate(()=>__fail=false);await runner.locator('[data-r195-action="save"]').click();await page.waitForFunction(()=>!document.querySelector('#routineRunnerV195').open);const result=await page.evaluate(id=>P.routines.find(r=>r.id===id),id);assert.equal(result.dailyLevels['2026-09-27'],'MORE');assert.equal(result.stepHistory['2026-09-27'].completed,2);assert.equal(result.stepHistory['2026-09-27'].skipped,1);assert(result.doneDates.includes('2026-09-27'));assert.equal(await page.evaluate(()=>AiderRoutineStepsV195.getRun()),null);pass('Successful partial run updates existing completion/statistics only after save');
  await page.locator('[data-r195-run="'+id+'"]').click();await runner.locator('[data-r195-action="toggle"]').click();await page.evaluate(()=>{window.__alice=P;authState={user:{uid:'other-qa'},ready:true};appDataSyncV191.observe();P={routines:[]};privateDataOwnerV179='other-qa';privateDataValueV179=P;AiderRoutineStepsV195.refresh()});assert(!(await runner.isVisible()));assert.equal(await page.evaluate(()=>AiderRoutineStepsV195.getRun()),null);await page.evaluate(()=>{authState={user:{uid:'routine-qa'},ready:true};appDataSyncV191.observe();P=window.__alice;privateDataOwnerV179='routine-qa';privateDataValueV179=P;renderRoutine();AiderRoutineStepsV195.refresh()});assert.equal(await page.evaluate(()=>AiderRoutineStepsV195.getRun().routineId),id);pass('Account switch closes old runner and restores only the matching account session');
  await page.locator('[data-r195-run="'+id+'"]').click();await page.setViewportSize({width:360,height:800});await page.screenshot({path:path.join(out,'runner-360.png'),fullPage:true});assert.equal(await runner.evaluate(e=>e.scrollWidth>e.clientWidth+1),false);await page.setViewportSize({width:720,height:900});await page.screenshot({path:path.join(out,'runner-fold.png'),fullPage:true});assert.equal(await runner.evaluate(e=>e.scrollWidth>e.clientWidth+1),false);pass('Runner fits compact phone and expanded Fold widths');
  await runner.locator('[data-r195-action="done"]').click();await runner.locator('[data-r195-action="end"]').click();await page.evaluate(()=>{document.getElementById('routineStepsToastV195')?.remove();window.__heldOwner='';fb.writePrivateData=value=>new Promise(resolve=>{window.__heldOwner=authState.user.uid;window.__finishHeldSave=()=>resolve(JSON.parse(JSON.stringify(value)))})});await runner.locator('[data-r195-action="save"]').click();await page.waitForFunction(()=>typeof __finishHeldSave==='function');assert.equal(await page.evaluate(()=>__heldOwner),'routine-qa');
  await page.evaluate(()=>{authState={user:{uid:'other-qa'},ready:true};appDataSyncV191.observe();P={routines:[],ownerMarker:'other-qa'};privateDataOwnerV179='other-qa';privateDataValueV179=P;AiderRoutineStepsV195.refresh();__finishHeldSave()});await page.waitForFunction(()=>!document.getElementById('routineRunnerV195').open);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>P.ownerMarker),'other-qa');assert.equal(await page.evaluate(()=>P.routines.length),0);assert.equal(await page.evaluate(()=>AiderRoutineStepsV195.getRun()),null);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiderlog-routine-run-v195:routine-qa')).state),'review');assert.equal(await page.locator('#routineStepsToastV195').count(),0);pass('In-flight save cannot complete, overwrite or clear progress for another account');
  assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,missing},null,2));
  for(const stale of ['failure.json','failure.png'])fs.rmSync(path.join(out,stale),{force:true});
 }catch(error){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(error),errors,missing,checks,body:await page.locator('body').innerText()},null,2));throw error}finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
