const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),holder={exports:{}};new Function('module','exports',fs.readFileSync(path.join(__dirname,'../android-src/assets/routine-steps-model-v195.js'),'utf8'))(holder,holder.exports);const model=holder.exports;
const routine={id:'routine',text:'아침 준비',foreign:{preserve:true},goalTracking:{0:{a:'old'}},steps:[{id:'water',title:'물 마시기',durationSeconds:60,unknown:'keep'},{id:'stretch',title:'스트레칭',durationSeconds:90},{id:'read',title:'읽기',durationSeconds:120}],dailyLevels:{'2026-09-26':'MAX'},doneDates:['2026-09-26']};
const create=()=>model.create(routine,'alice','2026-09-27',1000,'run-1');
test('step validation bounds titles/count/duration without mutating or dropping unknown fields',()=>{
 assert.deepEqual(model.steps(undefined),[]);const normalized=model.steps(routine.steps);assert.equal(normalized[0].unknown,'keep');normalized[0].title='changed';assert.equal(routine.steps[0].title,'물 마시기');
 for(const values of [[{id:'s',title:'',durationSeconds:1}],[{id:'s',title:'x'.repeat(81),durationSeconds:1}],[{id:'s',title:'s',durationSeconds:0}],[{id:'s',title:'s',durationSeconds:86401}],[{id:'s',title:'s',durationSeconds:1.5}],Array.from({length:31},(_,i)=>({id:String(i),title:'s',durationSeconds:1})),[routine.steps[0],routine.steps[0]]])assert.throws(()=>model.steps(values));
});
test('wall-clock countdown survives background gaps and pausing excludes paused time',()=>{let run=model.resume(create(),1000);assert.equal(model.remaining(run,16000),45000);run=model.pause(run,16000);assert.equal(model.remaining(run,100000),45000);assert.equal(run.elapsedMs,15000);run=model.resume(run,100000);assert.equal(model.remaining(run,110000),35000);assert.equal(model.remaining(run,200000),0);assert.equal(run.index,0);assert.equal(run.statuses[0],'');assert.equal(model.remaining(run,90000),45000)});
test('serialized resume binds to owner and keeps the original day across midnight',()=>{const run=model.resume(create(),1000),restored=model.restore(JSON.parse(JSON.stringify(run)),'alice');assert.equal(restored.date,'2026-09-27');assert.equal(model.remaining(restored,86401000),0);assert.equal(model.restore(run,'bob'),null);assert.equal(model.restore({...run,remainingMs:Infinity},'alice'),null);assert.equal(model.restore({...run,index:30},'alice'),null)});
test('elapsed time includes active overtime but never paused time',()=>{let run=model.resume(create(),1000);run=model.pause(run,121000);assert.equal(run.remainingMs,0);assert.equal(model.summary(run,301000).elapsedSeconds,120);run=model.resume(run,401000);run=model.pause(run,431000);assert.equal(model.summary(run,999999).elapsedSeconds,150)});
test('explicit completion and skip differ; elapsed timer alone never records completion',()=>{let run=model.resume(create(),1000);run=model.advance(run,'done',16000);assert.deepEqual(run.statuses,['done','','']);assert.equal(run.index,1);assert.equal(run.state,'running');run=model.advance(run,'skipped',20000);assert.deepEqual(run.statuses,['done','skipped','']);run=model.advance(run,'done',25000);assert.equal(run.state,'review');assert.equal(model.summary(run,25000).completed,2);assert.equal(model.summary(run,25000).skipped,1)});
test('full finish upgrades MAX while preserving existing history/fields and steps',()=>{let run=create();for(let i=0;i<3;i++)run=model.advance(run,'done',1000+i);const result=model.finish(routine,run,2000);assert.equal(result.dailyLevels['2026-09-27'],'MAX');assert.deepEqual(result.doneDates,['2026-09-26','2026-09-27']);assert.deepEqual(result.foreign,routine.foreign);assert.deepEqual(result.steps,routine.steps);assert.deepEqual(result.goalTracking,routine.goalTracking);assert.equal(result.stepHistory['2026-09-27'].completed,3);assert.equal(routine.stepHistory,undefined)});
test('partial completion never downgrades an existing higher daily level',()=>{let run=model.advance(create(),'done',1000);run=model.end(run,2000);const source={...routine,dailyLevels:{...routine.dailyLevels,'2026-09-27':'MAX'},doneDates:[...routine.doneDates,'2026-09-27']};const result=model.finish(source,run,2000);assert.equal(result.dailyLevels['2026-09-27'],'MAX');assert.equal(result.doneDates.filter(x=>x==='2026-09-27').length,1);assert.equal(result.stepHistory['2026-09-27'].remaining,2);assert.equal(model.finish(routine,run,2000).dailyLevels['2026-09-27'],'MINI')});
test('all skipped or early-ended runs do not claim practice completion',()=>{const result=model.finish(routine,model.end(create(),5000),5000);assert.deepEqual(result.dailyLevels,routine.dailyLevels);assert.deepEqual(result.doneDates,routine.doneDates);assert.equal(result.stepHistory['2026-09-27'].completed,0);assert.throws(()=>model.finish(routine,create(),5000))});
test('completion summaries are bounded and retrying the same run cannot duplicate done dates',()=>{const history=Object.fromEntries(Array.from({length:30},(_,i)=>['2026-08-'+String(i+1).padStart(2,'0'),{runId:'old'+i}]));let run=create();for(let i=0;i<3;i++)run=model.advance(run,'done',1000+i);const first=model.finish({...routine,stepHistory:history},run,3000),second=model.finish(first,run,3000);assert.equal(Object.keys(second.stepHistory).length,30);assert.equal(second.doneDates.filter(d=>d===run.date).length,1);assert.equal(second.stepHistory[run.date].runId,run.id)});
