const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright')}catch{playwright=require(process.env.PLAYWRIGHT_MODULE_PATH||path.join(process.env.USERPROFILE||require('node:os').homedir(),'.cache','codex-runtimes','codex-primary-runtime','dependencies','node','node_modules','playwright'))}
const root=path.resolve(process.env.AIDERLOG_SITE_ROOT||path.join(__dirname,'..')),out=path.resolve(process.env.AIDERLOG_QA_OUT||path.join(root,'work','qa-site-colors-v198'));fs.mkdirSync(out,{recursive:true});
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
const seed=`window.__qa198={calls:[],auth(){
 currentUser='mine';currentUserEmail='qa@example.invalid';currentUserName='검증';firebaseState={ready:true,user:{uid:'localqa',email:currentUserEmail,name:'검증'},pair:null,partner:null,friends:[],incoming:[],outgoing:[],friendIncoming:[],friendOutgoing:[],directLetters:[]};
 privateOwner=currentUserEmail;privateData[currentUserEmail]=blankPrivateData(currentUserEmail,'검증');privateRefs[currentUserEmail]={writable:true};googleToken='fixture';
 savePrivateData=async()=>{throw Error('Unexpected private write')};saveCloudData=async()=>{throw Error('Unexpected cloud write')};loadCalendarEvents=async()=>renderCalendar();loadGoogleCalendarTargets=async()=>[];
 const q=window.__qa198;q.sources=[{id:'work@example.test',summary:'업무 캘린더',backgroundColor:'#4285F4',primary:true},{id:'home@example.test',summary:'생활 캘린더',backgroundColor:'#4285F4'},{id:'study@example.test',summary:'공부 캘린더',backgroundColor:'#4285F4'}];q.prefs={calendarColorOverrides:{},calendarAutoColors:{}};q.server=[];
 window.AiderDearFirebase={readScheduleData:async()=>({own:structuredClone(q.server),shared:[]}),requestGoogleCalendarAccess:async()=>{},listGoogleCalendars:async()=>structuredClone(q.sources),listGoogleCalendarEvents:async id=>[{id:'fresh-'+id,summary:'새 가져오기',start:{date:'2026-09-29'},end:{date:'2026-09-30'}}],writeScheduleData:async rows=>{q.calls.push({action:'localWrite'});q.server=structuredClone(rows)}};
 calendarSyncRequest=async(action,payload={})=>{q.calls.push({action,payload:structuredClone(payload)});const helper=window.AiderCalendarColorsV198;if(action==='calendars')return {calendars:structuredClone(q.sources),selectedCalendarIds:q.sources.map(row=>row.id),...q.prefs};if(action==='configure'){if(q.fail)throw Error('색 저장 실패 검증');for(const[id,value]of Object.entries(payload.calendarColorOverrides||{})){if(value)q.prefs.calendarColorOverrides[id]=value;else delete q.prefs.calendarColorOverrides[id]}const allocation=helper.allocate(q.sources.map(row=>row.id),{overrides:q.prefs.calendarColorOverrides,automatic:q.prefs.calendarAutoColors});q.prefs.calendarAutoColors=allocation.automatic;q.server=q.server.map(row=>helper.googleId(row)?{...row,sourceColor:allocation.colors[helper.googleId(row)],sourceColorVersion:198}:row);return{itemCount:q.server.length}}if(action==='status')return {google:{connected:true,serverMode:true,selectedCalendarIds:q.sources.map(row=>row.id)}};throw Error('Unexpected request '+action)};
 applyLoginUI();
 },load(){const q=window.__qa198,base={externalSource:'google',sourceColor:'#4285F4',date:'2026-09-27',endDate:'2026-09-27',allDay:true,owner:'mine',authorEmail:currentUserEmail,authorUid:'localqa',readOnly:true};
 q.server=[{...base,id:'work1',calendarId:'google:work@example.test',sourceTitle:'업무 캘린더',title:'업무 일정'},{...base,id:'home1',calendarId:'google:home@example.test',sourceTitle:'생활 캘린더',title:'생활 일정'},{...base,id:'study1',calendarId:'study@example.test',googleEventId:'legacy-study',sourceTitle:'공부 캘린더',title:'공부 일정'},{...base,id:'work2',date:'2026-09-28',endDate:'2026-09-28',calendarId:'google:work@example.test',sourceTitle:'업무 캘린더',title:'업무 반복'},{...base,id:'received',calendarId:'google:friend@example.test',sourceTitle:'친구 캘린더',title:'받은 공유 일정',authorUid:'friend',authorEmail:'friend@example.test',owner:'shared',shareWithCouple:true},{id:'local',calendarId:'firebase-main',googleEventId:'local',date:'2026-09-27',endDate:'2026-09-27',title:'직접 쓴 일정',owner:'mine',authorUid:'localqa'}];applyScheduleDataSnapshot({own:structuredClone(q.server),shared:[]});return JSON.stringify(ownScheduleEvents)},rows(){return structuredClone(ownScheduleEvents)},async picker(mode='server'){calendarImportMode=mode;externalCalendarStatus.google={connected:mode==='server',clientMode:mode!=='server',serverMode:mode==='server'};openModal('calendarImportModal');await connectGoogleCalendarImport()},close(){closeModal('calendarImportModal')},async legacyImport(){ownScheduleEvents=[{id:'ancient',externalSource:'google',calendarId:'google:work@example.test',sourceColor:'#4285F4',date:'2000-01-01',endDate:'2000-01-01',owner:'shared',shareWithCouple:true,unknown:{keep:1}}];return syncGoogleCalendarSources([{id:'work@example.test',summary:'업무 캘린더',displayColor:'#966B4B'}])}};
window.__qa198.accountRace=async()=>{const oldRequest=calendarSyncRequest,oldUser=firebaseState.user;let release;calendarImportSources=[];calendarSyncRequest=()=>new Promise(resolve=>release=resolve);const pending=connectGoogleCalendarImport();await Promise.resolve();const oldKey=googleColorStorageKeyV198();firebaseState.user={uid:'another-owner',email:'other@example.invalid'};const newKey=googleColorStorageKeyV198();release({calendars:[{id:'private-old@example.test',summary:'이전 계정 캘린더'}],calendarColorOverrides:{'private-old@example.test':'#966B4B'}});await pending;const count=calendarImportSources.length;calendarSyncRequest=oldRequest;firebaseState.user=oldUser;return {count,oldKey,newKey}};
`;
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.json':'application/json'};
async function setup(browser,width){const context=await browser.newContext({viewport:{width,height:900},locale:'ko-KR',timezoneId:'Asia/Seoul',serviceWorkers:'block'}),page=await context.newPage(),errors=[],missing=[],externalWrites=[];
 page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const D=Date,n=new D('2026-09-27T12:00:00+09:00').valueOf();window.Date=class extends D{constructor(...args){super(...(args.length?args:[n]))}static now(){return n}}});
 await page.route('**/*',route=>{const request=route.request(),url=new URL(request.url());if(request.method()!=='GET'){externalWrites.push(request.url());return route.abort()}if(url.origin!=='http://site-colors.invalid')return route.abort();const rel=decodeURIComponent(url.pathname).slice(1)||'index.html',file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){missing.push(rel);return route.fulfill({status:404,body:'missing'})}if(rel==='firebase-app.js')return route.fulfill({status:200,contentType:'text/javascript',body:'/* isolated fixture */'});let body=fs.readFileSync(file);if(rel==='index.html')body=String(body).replace('  function applyLoginUI(){',seed+'  function applyLoginUI(){');return route.fulfill({status:200,contentType:mime[path.extname(file)]||'application/octet-stream',body})});
 await page.goto('http://site-colors.invalid/',{waitUntil:'networkidle'});await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;caret-color:transparent!important}'});await page.evaluate(()=>__qa198.auth());return{context,page,errors,missing,externalWrites};}
const hexRgb=hex=>'rgb('+hex.slice(1).match(/../g).map(v=>parseInt(v,16)).join(', ')+')';
async function computed(locator){return locator.evaluate(e=>({color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor,border:getComputedStyle(e).borderLeftColor,source:e.style.getPropertyValue('--source-color'),marked:e.hasAttribute('data-google-color-v198')}))}
(async()=>{const browser=await playwright.chromium.launch({headless:true,...((process.env.PLAYWRIGHT_CHANNEL||process.platform==='win32')?{channel:process.env.PLAYWRIGHT_CHANNEL||'msedge'}:{})}),results=[];
 try{for(const width of [1280,384]){const{context,page,errors,missing,externalWrites}=await setup(browser,width),before=await page.evaluate(()=>__qa198.load());
 const expected=await page.evaluate(()=>AiderCalendarColorsV198.forRows(__qa198.rows()));const chips={};for(const[title,id]of [['업무 일정','work@example.test'],['생활 일정','home@example.test'],['공부 일정','study@example.test'],['업무 반복','work@example.test']]){const data=await computed(page.locator('#calendar .ev').filter({hasText:title}).first());assert.equal(data.source,expected[id]);assert.equal(data.border,hexRgb(expected[id]),title+' actual border defeats generic CSS');assert(data.marked);chips[title]=data}
 assert.equal(new Set(Object.values(chips).slice(0,3).map(row=>row.bg)).size,3,'same Google metadata produces distinct calendar backgrounds');assert.equal(chips['업무 일정'].source,chips['업무 반복'].source);assert.equal(await page.evaluate(()=>JSON.stringify(__qa198.rows())),before,'display does not migrate stored rows');assert.equal(await page.evaluate(()=>__qa198.calls.filter(row=>row.action==='configure'||row.action==='localWrite').length),0);
 for(const[title,id]of [['업무 일정','work@example.test'],['생활 일정','home@example.test']])assert.equal(await page.locator('.agenda-row').filter({hasText:title}).locator('.agenda-owner-dot').evaluate(e=>getComputedStyle(e).backgroundColor),hexRgb(expected[id]));
 await page.locator('#calendar .day[data-date="2026-09-27"]').hover();await page.waitForSelector('.calendar-event-tooltip.visible');const received=page.locator('.calendar-event-tooltip button').filter({hasText:'받은 공유 일정'});assert.equal((await computed(received)).marked,false);assert(await received.evaluate(e=>e.classList.contains('schedule-received-v176')));assert.equal((await computed(page.locator('.calendar-event-tooltip button').filter({hasText:'직접 쓴 일정'}))).marked,false);
 assert.equal((await computed(page.locator('.calendar-event-tooltip button').filter({hasText:'공부 일정'}))).border,hexRgb(expected['study@example.test']));await page.locator('#monthTitle').hover();await page.waitForSelector('.calendar-event-tooltip',{state:'detached'});await page.screenshot({path:path.join(out,'calendar-'+width+'.png'),fullPage:true});
 await page.evaluate(()=>__qa198.picker());assert.equal(await page.locator('[data-google-color-index]').count(),3);assert.equal(await page.locator('[data-google-import-index]:checked').count(),3);await page.locator('[data-google-color-index="0"]').selectOption('#966B4B');assert.equal(await page.locator('[data-google-import-index]:checked').count(),3,'color change does not toggle selected source');assert.equal(await page.locator('.calendar-color-choice-v198').first().locator('i').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(150, 107, 75)');
 const controls=await page.locator('[data-google-color-index]').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,width:innerWidth}}));assert(controls.every(r=>r.left>=0&&r.right<=r.width),'color controls fit viewport');await page.screenshot({path:path.join(out,'picker-'+width+'.png'),fullPage:true});
 await page.locator('#googleCalendarImport').click();await page.waitForFunction(()=>!document.querySelector('#calendarImportModal').classList.contains('open'));const call=await page.evaluate(()=>__qa198.calls.filter(row=>row.action==='configure').at(-1));assert.deepEqual(call.payload.calendarColorOverrides,{'work@example.test':'#966B4B'});assert.equal((await computed(page.locator('#calendar .ev').filter({hasText:'업무 일정'}).first())).border,'rgb(150, 107, 75)');await page.locator('#monthTitle').hover();await page.screenshot({path:path.join(out,'brown-calendar-'+width+'.png'),fullPage:true});
 await page.evaluate(()=>__qa198.picker());assert.equal(await page.locator('[data-google-color-index="0"]').inputValue(),'#966B4B');await page.locator('[data-google-color-index="0"]').selectOption('');await page.locator('#googleCalendarImport').click();await page.waitForFunction(()=>!document.querySelector('#calendarImportModal').classList.contains('open'));assert.equal(await page.evaluate(()=>__qa198.calls.filter(row=>row.action==='configure').at(-1).payload.calendarColorOverrides['work@example.test']),'');
 await page.evaluate(()=>__qa198.picker());await page.locator('[data-google-color-index="1"]').selectOption('#765545');await page.evaluate(()=>__qa198.fail=true);await page.locator('#googleCalendarImport').click();assert(await page.locator('#calendarImportModal').isVisible());assert.equal(await page.locator('[data-google-color-index="1"]').inputValue(),'#765545');assert.match(await page.locator('#toast').textContent(),/색 저장 실패/);await page.evaluate(()=>{__qa198.fail=false;__qa198.close()});
 await page.evaluate(()=>__qa198.legacyImport());const legacy=await page.evaluate(()=>__qa198.rows());assert(legacy.every(row=>row.sourceColor==='#966B4B'&&row.sourceColorVersion===198));assert.equal(legacy.find(row=>row.id==='ancient').unknown.keep,1);assert(legacy.find(row=>row.id==='ancient').shareWithCouple);
 const race=await page.evaluate(()=>__qa198.accountRace());assert.equal(race.count,0,'late calendar colors do not populate another account');assert.notEqual(race.oldKey,race.newKey,'fallback preferences are UID scoped');
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);assert.deepEqual(externalWrites,[]);results.push({width,checks:20,errors,missing,externalWrites,chips});await context.close();}}
 finally{await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2))}console.log(JSON.stringify(results,null,2));})().catch(error=>{console.error(error);process.exitCode=1});
