const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright')}catch{playwright=require(path.join(process.env.USERPROFILE||require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
const root=path.resolve(process.env.AIDERLOG_APP_ASSETS||path.join(__dirname,'../android-src/assets')),out=path.resolve(__dirname,'../work/qa-widget-private-v196');fs.mkdirSync(out,{recursive:true});
const executablePath=[process.env.AIDERLOG_TEST_BROWSER,process.env.ProgramFiles&&path.join(process.env.ProgramFiles,'Google/Chrome/Application/chrome.exe')].find(p=>p&&fs.existsSync(p));
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.gif':'image/gif','.webmanifest':'application/manifest+json'};
(async()=>{const browser=await playwright.chromium.launch({headless:true,...(executablePath?{executablePath}:{})}),context=await browser.newContext({viewport:{width:412,height:915},hasTouch:true,isMobile:true,timezoneId:'Asia/Seoul',serviceWorkers:'block'}),page=await context.newPage(),errors=[],missing=[],network=[],checks=[];const pass=name=>{checks.push(name);console.log('PASS',name)};
try{
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!=='http://widget-private.invalid'){network.push(url.href);return route.abort()}const rel=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname).slice(1);if(rel==='firebase-app.js')return route.fulfill({contentType:'text/javascript',body:'/* Test-only authenticated Firebase boundary. */'});const file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){missing.push(rel);return route.fulfill({status:404,body:''})}return route.fulfill({contentType:mime[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)})});
 await page.addInitScript(()=>{sessionStorage.setItem('aiderlog-splash-shown-session-v150','1');const q=window.__privateQA={user:{uid:'private-a',email:'a@example.invalid'},items:[],claims:[],acks:[],failed:[],snapshots:[],order:[],calls:[],subscribers:[],accepted:[],otherWrites:[],sequence:0,now:Date.parse('2026-09-27T12:00:00+09:00'),receipts:{},gate:null,loseNext:false};const D=Date;window.Date=class extends D{constructor(...args){super(...(args.length?args:[q.now]))}static now(){return q.now}};
 q.cloud={routines:[{id:'routine-a',text:'아침 독서',miniText:'1쪽',moreText:'5쪽',maxText:'10쪽',dailyLevels:{},doneDates:[],updatedAt:100,unknown:{keep:true}}],checklists:[{id:'todo-old',kind:'todo',text:'기존 투두',done:false,updatedAt:100}],memos:Array.from({length:50},(_,i)=>({id:'history-'+i,text:'보관 메모 '+i,updatedAt:q.now+50000+i})),personalItems:[{id:'finance-keep',category:'finance',title:'보존할 금융 기록'}]};
 q.enqueue=(op,id,value,date='',expected=undefined)=>{const same=row=>row.uid===q.user.uid&&row.op===op&&row.id===id&&(op!=='routine'||row.date===date);const unclaimed=q.items.findIndex(row=>row.state==='pending'&&same(row));const predecessor=[...q.items].reverse().find(row=>row.state==='claimed'&&same(row));const row={schema:196,uid:q.user.uid,op,id,value,date,kind:op==='routine'?'RoutineAll':'CalendarSplit',widgetId:7,key:'local-'+(++q.sequence),createdAt:q.now,expectedUpdatedAt:expected,state:'pending',...(predecessor?{parentKey:predecessor.key}:{})};if(unclaimed>=0)q.items[unclaimed]=row;else q.items.push(row);return row.key};
 window.AiderLogNative={syncWidgets(raw){const snapshot=JSON.parse(raw);q.snapshots.push(snapshot);q.raw=snapshot;q.order.push({kind:'sync',key:snapshot.privateReceiptV196?.key})},privatePendingV196(uid){const row=q.items.find(r=>r.uid===uid&&r.state!=='failed');if(!row)return '[]';row.state='claimed';q.claims.push(JSON.parse(JSON.stringify(row)));return JSON.stringify([row])},privateAckV196(uid,key,raw){if(q.ackAllowed===false)return false;const receipt=JSON.parse(raw),row=q.items.find(r=>r.uid===uid&&r.key===key),proof=q.raw?.privateReceiptV196;if(!row||!proof||proof.uid!==uid||proof.key!==key||proof.id!==row.id||proof.op!==row.op||proof.revision!==receipt.revision||proof.rebase!==receipt.rebase)return false;q.acks.push({uid,key,receipt});q.order.push({kind:'ack',key});q.items=q.items.filter(r=>r!==row);for(const child of q.items)if(receipt.rebase&&child.parentKey===key&&child.id===row.id&&child.op===row.op)child.expectedUpdatedAt=receipt.revision;return true},privateFailV196(uid,key,code){const row=q.items.find(r=>r.uid===uid&&r.key===key);if(!row)return false;row.state='failed';row.failure=code;q.failed.push({uid,key,code});return true}};
 });
 await page.goto('http://widget-private.invalid/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.AiderWidgetPrivateV196&&window.AiderWidgetSyncV164);
 await page.evaluate(()=>{const q=__privateQA;const duplicate=value=>JSON.parse(JSON.stringify(value));q.api={getState:()=>({user:q.user,pair:null,friends:[],ready:true}),subscribe(callback){q.subscribers.push(callback);callback(this.getState());return()=>{}},readAppData:async()=>({scheduleEvents:[]}),readScheduleData:async()=>[],readPrivateData:async()=>duplicate(q.cloud),acceptPrivateSnapshot(detail){q.accepted.push(duplicate(detail))},writePrivateData:async submitted=>{if(!q.allowNormal){q.otherWrites.push('private');throw Error('No full private write expected')}q.normalWrites=(q.normalWrites||0)+1;q.cloud=duplicate(submitted);return duplicate(q.cloud)},applyWidgetActionV165:async command=>{q.calls.push(duplicate(command));if(q.gate)await q.gate;if(command.uid!==q.user.uid)throw Object.assign(Error('owner'),{code:'widget/owner-changed'});const previous=q.receipts[command.key];if(previous)return {applied:false,replayed:true,payload:duplicate(q.cloud)};const field=command.op==='routine'?'routines':'checklists',rows=q.cloud[field],index=rows.findIndex(r=>r.id===command.id);if(command.op.startsWith('add-')){if(index>=0)throw Object.assign(Error('exists'),{code:'widget/stale-action'});rows.push({id:command.id,text:command.value,kind:command.op==='add-memo'?'memo':'todo',date:command.op==='add-todo'?command.date:'',done:false,createdAt:q.now,updatedAt:q.now})}else{const row=rows[index];if(!row)throw Object.assign(Error('notfound'),{code:'widget/not-found'});if(row.updatedAt!==command.expectedUpdatedAt)throw Object.assign(Error('stale'),{code:'widget/stale-action'});row.updatedAt=Math.max(q.now,row.updatedAt+1);if(command.op==='todo')row.done=command.value===true||command.value==='true';else{row.dailyLevels={...row.dailyLevels};row.doneDates=row.doneDates.filter(d=>d!==command.date);if(command.value&&command.value!=='SKIP'){row.dailyLevels[command.date]=command.value;row.doneDates.push(command.date)}else if(command.value==='SKIP')row.dailyLevels[command.date]='SKIP';else delete row.dailyLevels[command.date]}}q.receipts[command.key]=duplicate(command);if(q.loseNext){q.loseNext=false;throw Object.assign(Error('lost response'),{code:'unavailable'})}return {applied:true,replayed:false,payload:duplicate(q.cloud)}}};window.AiderDearFirebase=q.api;const sync=window.sync;window.sync=async request=>{const result=await sync(request);if(request?.kind==='private')q.order.push({kind:'coordinator',accepted:result});return result};dispatchEvent(new Event('aiderdear-firebase-ready'));});
 await page.waitForFunction(()=>AiderAppDataScopeV179.ownsPrivate(P)&&AiderWidgetSyncV164.snapshot().uid==='private-a');await page.evaluate(()=>AiderWidgetPrivateV196.flush());assert.equal(await page.evaluate(()=>__privateQA.calls.length),0);pass('Full app bridge with empty native queue performs no command writes or SDK imports');
 await page.evaluate(()=>{__privateQA.enqueue('add-todo','new-todo','우유 사기','2026-09-30');__privateQA.enqueue('add-memo','new-memo','떠오른 생각')});await page.evaluate(()=>AiderWidgetPrivateV196.flush());
 assert.deepEqual(await page.evaluate(()=>P.checklists.filter(r=>r.id.startsWith('new-')).map(r=>[r.id,r.kind,r.text,r.date])),[['new-todo','todo','우유 사기','2026-09-30'],['new-memo','memo','떠오른 생각','']]);assert.equal(await page.evaluate(()=>__privateQA.acks.length),2);assert.equal(await page.evaluate(()=>AiderWidgetSyncV164.snapshot().v165.notes.some(r=>r.id==='new-memo')),false);assert(await page.evaluate(()=>AiderTodoV179.snapshot().checklists.some(r=>r.id==='new-memo'&&r.kind==='memo')));assert(await page.evaluate(()=>P.personalItems.some(r=>r.id==='finance-keep')));pass('Native Todo/Memo publish through real adapter, app P and note controller; offscreen memo can acknowledge without losing other records');
 const ordered=await page.evaluate(()=>__privateQA.order);for(let i=0;i<ordered.length;i++)if(ordered[i].kind==='ack'){assert(ordered.slice(0,i).some(r=>r.kind==='coordinator'&&r.accepted));assert(ordered.slice(0,i).some(r=>r.kind==='sync'&&r.key===ordered[i].key))}assert.equal(await page.evaluate(()=>__privateQA.otherWrites.length),0);pass('Existing save coordinator and verified native receipt projection precede every acknowledgement, without full-document writes');
 await page.evaluate(()=>{for(const value of ['MINI','MORE','MAX'])__privateQA.enqueue('routine','routine-a',value,'2026-09-27',100)});const before=await page.evaluate(()=>__privateQA.calls.length);await page.evaluate(()=>AiderWidgetPrivateV196.flush());assert.equal(await page.evaluate(()=>__privateQA.calls.length),before+1);assert.equal(await page.evaluate(()=>P.routines[0].dailyLevels['2026-09-27']),'MAX');assert.equal(await page.evaluate(()=>AiderWidgetSyncV164.snapshot().v165.routineStats.todayDone),1);assert.equal(await page.evaluate(()=>P.routines[0].unknown.keep),true);pass('Coalesced repeated routine taps publish one latest completion and update actual widget weekly statistics');
 // Commit the route through the actual wheel controller. Direct go() bypasses
 // its saved route, allowing a delayed pageshow/visibility restore to hide the editor.
 await page.evaluate(()=>AiderLogWheelV151.navigate('routine'));
 await page.waitForFunction(()=>document.querySelector('.views>.view.on')?.id==='routine'&&!document.documentElement.classList.contains('aiderlog-route-changing-v154'));
 await page.evaluate(()=>{routineEditorIdV111='routine-a';renderRoutine()});const name=page.locator('#routineEditorFormV111 [name="text"]');await name.waitFor({state:'visible'});await name.fill('저장하지 않은 루틴 이름');await name.focus();
 await page.evaluate(()=>{const q=__privateQA;q.gate=new Promise(resolve=>q.release=resolve);q.enqueue('routine','routine-a','MINI','2026-09-27',q.cloud.routines[0].updatedAt);q.flight=AiderWidgetPrivateV196.flush()});await page.waitForFunction(()=>__privateQA.items.some(r=>r.state==='claimed'));
 await page.evaluate(()=>{P.routines[0].text='행 단위 로컬 초안';__privateQA.release();__privateQA.gate=null});await page.evaluate(()=>__privateQA.flight);assert.equal(await name.inputValue(),'저장하지 않은 루틴 이름');assert.equal(await page.evaluate(()=>P.routines[0].text),'행 단위 로컬 초안');assert.equal(await page.evaluate(()=>AiderWidgetSyncV164.snapshot().v165.routines[0].level),'MINI');assert.equal(await page.evaluate(()=>__privateQA.items.length),0);await page.screenshot({path:path.join(out,'routine-editor-preserved.png')});pass('Focused editor and in-flight local row draft survive authoritative widget publication while coordinator defers UI replacement');
 await page.evaluate(()=>{const q=__privateQA;q.enqueue('routine','routine-a','MORE','2026-09-27',q.cloud.routines[0].updatedAt)});await page.evaluate(()=>AiderWidgetPrivateV196.flush());assert.equal(await page.evaluate(()=>P.routines[0].text),'행 단위 로컬 초안');assert.equal(await name.inputValue(),'저장하지 않은 루틴 이름');
 await page.evaluate(()=>{__privateQA.allowNormal=true;return savePrivate()});assert.equal(await page.evaluate(()=>__privateQA.cloud.routines[0].text),'행 단위 로컬 초안');assert.equal(await page.evaluate(()=>__privateQA.cloud.routines[0].dailyLevels['2026-09-27']),'MORE');pass('Delayed app save after two widget commits keeps the focused row draft and latest completion');
 await page.evaluate(()=>{routineEditorIdV111=null;renderRoutine();document.activeElement?.blur();appDataSyncV191.flush()});
 await page.evaluate(()=>{const q=__privateQA;q.allowNormal=true;q.normalWrites=0;q.gate=new Promise(resolve=>q.release=resolve);q.enqueue('routine','routine-a','MAX','2026-09-27',q.cloud.routines[0].updatedAt);q.flight=AiderWidgetPrivateV196.flush()});await page.waitForFunction(()=>__privateQA.items.some(r=>r.state==='claimed'));
 await page.evaluate(()=>{P.routines[0].text='메타데이터 수정 유지';P.routines[0].updatedAt=__privateQA.now+1;__privateQA.appFlight=savePrivate()});await page.waitForTimeout(40);assert.equal(await page.evaluate(()=>__privateQA.normalWrites||0),0);
 await page.evaluate(()=>{__privateQA.release();__privateQA.gate=null});await page.evaluate(()=>Promise.all([__privateQA.flight,__privateQA.appFlight]));assert.equal(await page.evaluate(()=>__privateQA.cloud.routines[0].text),'메타데이터 수정 유지');assert.equal(await page.evaluate(()=>__privateQA.cloud.routines[0].dailyLevels['2026-09-27']),'MAX');assert.equal(await page.evaluate(()=>__privateQA.normalWrites),1);assert.equal(await page.evaluate(()=>P.routines[0].dailyLevels['2026-09-27']),'MAX');pass('App metadata save waits for in-flight widget commit and preserves both metadata and completion');
 await page.evaluate(()=>{const q=__privateQA;window.__staleP=P;const before=JSON.stringify(P.routines[0]);authState={user:{uid:'private-b'},pair:null};dispatchEvent(new CustomEvent('aiderlog:widget-private-changed',{detail:{uid:'private-b',command:{uid:'private-b',op:'routine',id:'routine-a'},localBefore:before,payload:{routines:[{id:'routine-a',text:'다른 계정 값'}]}}}));q.transitionSafe=JSON.stringify(__staleP.routines[0])===before;authState={user:q.user,pair:null,friends:[],ready:true};});assert(await page.evaluate(()=>__privateQA.transitionSafe));pass('Transitional account change cannot merge another account result into stale P even with matching ID and localBefore');
 await page.evaluate(()=>{const q=__privateQA;q.loseNext=true;q.enqueue('routine','routine-a','MORE','2026-09-27',q.cloud.routines[0].updatedAt)});await page.evaluate(()=>AiderWidgetPrivateV196.flush());assert.equal(await page.evaluate(()=>__privateQA.items[0].state),'claimed');const lost=await page.evaluate(()=>__privateQA.items[0].key);
 await page.evaluate(()=>{const q=__privateQA;const old=q.items[0];q.enqueue('routine','routine-a','MAX','2026-09-27',old.expectedUpdatedAt);q.cloud.routines[0].text='다른 기기의 최신 이름';q.cloud.routines[0].updatedAt+=20;q.now+=15001});await page.evaluate(()=>AiderWidgetPrivateV196.flush());
 assert.equal(await page.evaluate(()=>__privateQA.cloud.routines[0].text),'다른 기기의 최신 이름');assert.equal(await page.evaluate(()=>__privateQA.items[0].state),'failed');assert.equal(await page.evaluate(()=>__privateQA.items[0].failure),'widget/stale-action');assert.equal(await page.evaluate(key=>__privateQA.acks.find(r=>r.key===key).receipt.rebase,lost),false);pass('Lost response replay keeps frozen receipt and never rebases a successor over unrelated remote changes');
 await page.evaluate(()=>{const q=__privateQA;q.ackAllowed=false;q.enqueue('routine','routine-a','MINI','2026-09-27',q.cloud.routines[0].updatedAt)});const cachedCalls=await page.evaluate(()=>__privateQA.calls.length);await page.evaluate(()=>AiderWidgetPrivateV196.flush());
 await page.evaluate(()=>{P.routines[0].text='확인 재시도 사이 앱 저장';P.routines[0].updatedAt=__privateQA.now+40;return savePrivate()});await page.evaluate(()=>{__privateQA.ackAllowed=true;return AiderWidgetPrivateV196.flush()});assert.equal(await page.evaluate(()=>__privateQA.calls.length),cachedCalls+2);assert.equal(await page.evaluate(()=>P.routines[0].text),'확인 재시도 사이 앱 저장');assert.equal(await page.evaluate(()=>__privateQA.acks.at(-1).receipt.rebase),false);pass('App save between commit and acknowledgement invalidates cached response and receipt replay preserves the new metadata');
 await page.evaluate(()=>{const q=__privateQA;q.loseNext=true;q.enqueue('add-memo','deleted-after-commit','삭제 뒤 재생성 금지')});await page.evaluate(()=>AiderWidgetPrivateV196.flush());await page.evaluate(()=>{const q=__privateQA;q.cloud.checklists=q.cloud.checklists.filter(row=>row.id!=='deleted-after-commit');q.now+=15001});await page.evaluate(()=>AiderWidgetPrivateV196.flush());assert.equal(await page.evaluate(()=>__privateQA.items.some(row=>row.id==='deleted-after-commit')),false);assert.equal(await page.evaluate(()=>P.checklists.some(row=>row.id==='deleted-after-commit')),false);assert.deepEqual(await page.evaluate(()=>__privateQA.acks.at(-1).receipt),{revision:0,rebase:false});pass('Replayed confirmed add after remote deletion retires local optimistic state without recreating the note');
 assert.equal(await page.evaluate(()=>__privateQA.otherWrites.length),0);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);assert(!network.some(url=>/firebasejs/.test(url)));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,missing,blockedNetwork:network},null,2));
}catch(error){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(error),errors,missing,checks,body:await page.locator('body').innerText()},null,2));throw error}finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
