const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright')}catch{playwright=require(path.join(process.env.USERPROFILE||require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
const executablePath=[process.env.AIDERLOG_TEST_BROWSER,process.env.ProgramFiles&&path.join(process.env.ProgramFiles,'Google/Chrome/Application/chrome.exe'),process.env['ProgramFiles(x86)']&&path.join(process.env['ProgramFiles(x86)'],'Microsoft/Edge/Application/msedge.exe')].find(file=>file&&fs.existsSync(file));
const root=path.resolve(process.env.AIDERLOG_APP_ASSETS||path.join(__dirname,'../android-src/assets')),out=path.resolve(__dirname,'../work/qa-widget-calendar-v195');fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.gif':'image/gif','.webmanifest':'application/manifest+json'};
const authSDK='export const getAuth=()=>({currentUser:window.__calendarQA.user});';
const firestoreSDK=`export const getFirestore=()=>({fixture:true});export const doc=(db,...parts)=>parts.join('/');export const serverTimestamp=()=>({fixtureTimestamp:true});export async function runTransaction(db,fn){const q=window.__calendarQA;q.transactions++;if(q.fail)throw Object.assign(Error('Fixture offline'),{code:'unavailable'});if(q.gate)await q.gate;await fn({get:async ref=>{q.paths.push(ref);return {exists:()=>q.remote!==null,data:()=>({payload:q.remote})}},set:(ref,data,options)=>{q.writes.push({ref,data,options});q.remote=data.payload}})}`;
(async()=>{const browser=await playwright.chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:executablePath?{executablePath}:{})}),context=await browser.newContext({viewport:{width:412,height:915},hasTouch:true,isMobile:true,serviceWorkers:'block'}),page=await context.newPage(),errors=[],missing=[],sdkRequests=[],checks=[];const pass=name=>{checks.push(name);console.log('PASS',name)};
try{
 page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.href==='https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js'){sdkRequests.push('auth');return route.fulfill({contentType:'text/javascript',body:authSDK})}if(url.href==='https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js'){sdkRequests.push('firestore');return route.fulfill({contentType:'text/javascript',body:firestoreSDK})}if(url.origin!=='http://widget-calendar.invalid')return route.abort();const rel=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname).slice(1);if(rel==='firebase-app.js')return route.fulfill({contentType:'text/javascript',body:'/* Authentication/Firestore boundary replaced by this test only. */'});const file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){missing.push(rel);return route.fulfill({status:404,body:''})}return route.fulfill({contentType:mime[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)})});
 await page.addInitScript(()=>{sessionStorage.setItem('aiderlog-splash-shown-session-v150','1');const q=window.__calendarQA={user:{uid:'calendar-owner-a',email:'a@example.invalid'},pending:[],acks:[],native:[],order:[],subscriptions:[],remote:[],listenerRows:[],paths:[],writes:[],transactions:0,fail:false,gate:null};window.AiderLogNative={syncWidgets(raw){const snapshot=JSON.parse(raw);q.native.push(snapshot);q.order.push({kind:'sync',uid:snapshot.uid,ids:(snapshot.scheduleItems||[]).map(r=>r.id)})},calendarPendingV195(owner){return JSON.stringify(q.pending)},calendarAckV195(owner,id){q.acks.push({owner,id});q.order.push({kind:'ack',owner,id});q.pending=q.pending.filter(r=>r.id!==id);return true}}});
 await page.goto('http://widget-calendar.invalid/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.AiderWidgetCalendarV195&&window.AiderWidgetSyncV164&&window.AiderCoreV195);
 await page.evaluate(()=>{const q=__calendarQA;authState={user:q.user,pair:null,friends:[]};fb={getState:()=>authState,subscribe(callback){q.subscriptions.push(callback);callback(authState);return()=>{}},readAppData:async()=>({scheduleEvents:[]}),readPrivateData:async()=>({routines:[],checklists:[],memos:[]}),readScheduleData:async()=>structuredClone(q.listenerRows)};window.AiderDearFirebase=fb;dispatchEvent(new Event('aiderdear-firebase-ready'));q.makeDraft=(suffix,owner=q.user.uid)=>({schema:195,op:'add-schedule',id:'widget-calendar-'+suffix.padEnd(16,'0'),uid:owner,title:'위젯에서 만든 일정',date:'2026-09-27',endDate:'2026-09-27',time:'14:30',allDay:false,createdAt:Date.now()});q.deliver=(uid,rows)=>dispatchEvent(new CustomEvent('aiderlog:verified-schedule-data-v191',{detail:{uid,pairId:'',payload:rows,hasPendingWrites:false,fromCache:false,exists:true}}));});
 await page.waitForFunction(()=>AiderWidgetSyncV164.snapshot().uid==='calendar-owner-a');await page.evaluate(()=>AiderWidgetCalendarV195.flush());assert.deepEqual(sdkRequests,[]);assert.equal(await page.evaluate(()=>__calendarQA.transactions),0);pass('Full app installs native calendar bridge; empty own queue loads no SDK and starts no transaction');
 await page.evaluate(async()=>{__calendarQA.pending=[__calendarQA.makeDraft('first')];await AiderWidgetCalendarV195.flush()});
 const first=await page.evaluate(async()=>{const codec=await import('./archive-codec-v168.js');return {rows:codec.decodeArchive(__calendarQA.remote),writes:__calendarQA.writes.length,acks:__calendarQA.acks,transactions:__calendarQA.transactions,paths:__calendarQA.paths}});
 assert.equal(first.rows.length,1);assert.equal(first.rows[0].title,'위젯에서 만든 일정');assert.equal(first.rows[0].authorUid,'calendar-owner-a');assert.equal(first.rows[0].time,'14:30');assert.equal(first.rows[0].shareWithCouple,false);assert.equal(first.rows[0].widgetCreatedV195,true);assert.deepEqual(first.paths,['users/calendar-owner-a/schedule/main']);assert.equal(first.writes,1);assert.deepEqual(first.acks,[]);pass('Own native draft uses authenticated schedule transaction and remains pending before real snapshot confirmation');
 await page.evaluate(async()=>{for(let i=0;i<3;i++)await AiderWidgetCalendarV195.flush()});assert.equal(await page.evaluate(()=>__calendarQA.transactions),1);assert.equal(await page.evaluate(()=>__calendarQA.pending.length),1);pass('Waiting for schedule listener does not reread or append on repeated resume');
 await page.evaluate(rows=>{__calendarQA.deliver('other-owner',rows)},first.rows);await page.evaluate(()=>AiderWidgetCalendarV195.flush());assert.equal(await page.evaluate(()=>__calendarQA.acks.length),0);
 for(const changed of [{...first.rows[0],authorUid:'wrong-owner'},{...first.rows[0],widgetCreatedV195:false}]){await page.evaluate(row=>__calendarQA.deliver(__calendarQA.user.uid,[row]),changed);await page.evaluate(()=>AiderWidgetCalendarV195.flush());assert.equal(await page.evaluate(()=>__calendarQA.acks.length),0);assert.equal(await page.evaluate(()=>__calendarQA.pending.length),1)}pass('Matching ID with wrong author or missing native marker never acknowledges a pending draft');
 await page.evaluate(rows=>{__calendarQA.listenerRows=rows;__calendarQA.deliver(__calendarQA.user.uid,rows)},first.rows);await page.evaluate(()=>AiderWidgetCalendarV195.flush());assert.equal(await page.evaluate(()=>__calendarQA.acks.length),1);assert.equal(await page.evaluate(()=>__calendarQA.pending.length),0);assert.equal(await page.evaluate(()=>AiderWidgetSyncV164.snapshot().scheduleItems[0]?.id),first.rows[0].id);
 const order=await page.evaluate(()=>__calendarQA.order),ackIndex=order.findIndex(e=>e.kind==='ack');assert(ackIndex>0&&order.slice(0,ackIndex).some(e=>e.kind==='sync'&&e.uid==='calendar-owner-a'&&e.ids.includes(first.rows[0].id)));pass('Only matching owner listener updates actual widget snapshot, then native sync precedes acknowledgement');
 await page.evaluate(()=>{__calendarQA.pending=[__calendarQA.makeDraft('failure')];__calendarQA.fail=true});await page.evaluate(()=>AiderWidgetCalendarV195.flush());assert.equal(await page.evaluate(()=>__calendarQA.writes.length),1);assert.equal(await page.evaluate(()=>__calendarQA.pending.length),1);assert.equal(await page.evaluate(()=>__calendarQA.acks.length),1);pass('Failed cloud transaction retains native local draft without acknowledging or claiming success');
 await page.evaluate(()=>{const q=__calendarQA;q.fail=false;q.user={uid:'calendar-owner-b',email:'b@example.invalid'};authState={user:q.user,pair:null,friends:[]};q.subscriptions.forEach(callback=>callback(authState));q.pending=[q.makeDraft('switching')];q.gate=new Promise(resolve=>q.release=resolve);q.inFlight=AiderWidgetCalendarV195.flush()});await page.waitForFunction(()=>__calendarQA.transactions>=3);
 await page.evaluate(()=>{const q=__calendarQA;q.user={uid:'calendar-owner-c',email:'c@example.invalid'};authState={user:q.user,pair:null,friends:[]};q.subscriptions.forEach(callback=>callback(authState));q.release()});await page.evaluate(()=>__calendarQA.inFlight);assert.equal(await page.evaluate(()=>__calendarQA.writes.length),1);assert.equal(await page.evaluate(()=>__calendarQA.acks.length),1);assert.equal(await page.evaluate(()=>__calendarQA.pending[0].uid),'calendar-owner-b');pass('Account change during transaction never saves or acknowledges the previous account draft');
 await page.screenshot({path:path.join(out,'calendar-bridge.png')});assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,missing,sdkRequests},null,2));
}catch(error){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(error),errors,missing,sdkRequests,checks},null,2));throw error}finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
