import {test} from 'node:test';
import assert from 'node:assert/strict';
import {calendarDraftV195,appendCalendarDraftV195,createCalendarQueueV195} from '../android-src/assets/widget-calendar-sync-v195.js';
const alice={uid:'alice',email:'Alice@example.test'}, input={schema:195,op:'add-schedule',uid:'alice',id:'widget-calendar-12345678-abcd-1234-5678-abcd12345678',title:'새 일정',date:'2026-09-27',endDate:'2026-09-27',time:'09:30',allDay:false,createdAt:Date.UTC(2026,8,26)};
const draft=()=>calendarDraftV195(input,alice);
function fixture(extra={}){let user=alice,epoch=1,clock=0;const pending=[input],saved=[],acked=[],published=[];const worker=createCalendarQueueV195({getUser:()=>user,getEpoch:()=>epoch,pending:()=>JSON.stringify(pending),save:async row=>saved.push(row),confirm:async(uid,id)=>{published.push(id);return true;},ack:(uid,id)=>{acked.push([uid,id]);pending.splice(pending.findIndex(row=>row.id===id),1);return true;},now:()=>clock,...extra});return{worker,pending,saved,acked,published,user:u=>{user=u;epoch++;},tick:n=>clock+=n};}
test('quick-add validates native input and fixes ownership/private scope',()=>{const row=draft();assert.equal(row.authorUid,'alice');assert.equal(row.authorEmail,'alice@example.test');assert.equal(row.shareWithCouple,false);assert.equal(row.owner,'mine');assert.equal(row.time,'09:30');assert.equal(calendarDraftV195({...input,allDay:true,time:'22:00'},alice).time,'');for(const patch of [{uid:'bob'},{title:' '},{title:'a'.repeat(181)},{id:'bad'},{date:'2026-02-30',endDate:'2026-02-30'},{date:'2026-13-01',endDate:'2026-13-01'},{time:'24:01'},{endDate:'2026-09-28'},{allDay:'true'},{createdAt:1}])assert.throws(()=>calendarDraftV195({...input,...patch},alice));});
test('atomic append preserves all existing records and repeat retries preserve remote edits',()=>{const previous=[{id:'remote',foreign:{x:1}}],row=draft(),first=appendCalendarDraftV195(previous,row);assert.equal(first.changed,true);assert.equal(previous.length,1);assert.equal(first.rows[0],previous[0]);const edited={...row,title:'다른 곳에서 수정'};assert.deepEqual(appendCalendarDraftV195([edited],row),{rows:[edited],changed:false});assert.throws(()=>appendCalendarDraftV195([{id:row.id,authorUid:'bob'}],row),/id-conflict/);assert.throws(()=>appendCalendarDraftV195({broken:true},row),/invalid-store/);});
test('queue acknowledges only after save and native snapshot confirmation',async()=>{const f=fixture();await f.worker.flush();assert.equal(f.saved.length,1);assert.deepEqual(f.acked,[['alice',input.id]]);assert.equal(f.pending.length,0);await f.worker.flush();assert.equal(f.saved.length,1);});
test('slow schedule snapshot retains draft and retries confirmation without cloud writes',async()=>{let ready=false;const f=fixture({confirm:()=>ready});await f.worker.flush();assert.equal(f.saved.length,1);assert.equal(f.acked.length,0);ready=true;await f.worker.flush();assert.equal(f.saved.length,1);assert.equal(f.acked.length,1);});
test('offline and quota failures retain drafts and throttle subsequent reads',async()=>{let attempts=0;const f=fixture({save:async()=>{attempts++;throw Object.assign(Error(),{code:'resource-exhausted'});}});await f.worker.flush();await f.worker.flush();assert.equal(attempts,1);assert.equal(f.pending.length,1);assert.equal(f.acked.length,0);f.tick(1800000);await f.worker.flush();assert.equal(attempts,2);const offline=fixture({online:()=>false});await offline.worker.flush();assert.equal(offline.saved.length,0);});
test('account switch during commit cannot acknowledge or publish another account',async()=>{let finish;const f=fixture({save:()=>new Promise(resolve=>finish=resolve)}),job=f.worker.flush();f.user({uid:'bob',email:'b@example.test'});finish();await job;assert.equal(f.acked.length,0);assert.equal(f.published.length,0);assert.equal(f.pending.length,1);});
test('same-user signout/login during commit also rejects old generation',async()=>{let finish;const f=fixture({save:()=>new Promise(resolve=>finish=resolve)}),job=f.worker.flush();f.user(null);f.user(alice);finish();await job;assert.equal(f.acked.length,0);});
test('malformed native records cannot write cloud or discard valid later drafts',async()=>{const f=fixture();f.pending.unshift({...input,id:'invalid'});await f.worker.flush();assert.equal(f.saved.length,1);assert.equal(f.acked.length,1);assert.equal(f.pending.length,1);assert.equal(f.pending[0].id,'invalid');});
