import test from 'node:test';
import assert from 'node:assert/strict';
import {libraryDispatch,LIBRARY_DOCUMENT,firestoreDocumentBytes,MAX_FIRESTORE_DOCUMENT_BYTES} from '../server/youtube-library-store-v189.mjs';
import {createHandler} from '../api/youtube-library.mjs';
import {createYoutubeClient} from '../youtube-client-v189.js';
const clone=v=>structuredClone(v),a={uid:'owner-a'},b={uid:'owner-b'},video='M7lc1UVf-VE';
function memory(){const docs=new Map([['users/owner-a/private/main',{payload:{checklists:[{text:'keep me'}],schedule:[{title:'keep'}]}}]]),writes=[];return{docs,writes,doc(path){return{path,async get(){const value=docs.get(path);return{exists:!!value,data:()=>clone(value)};}};},async runTransaction(fn){const queued=[];const result=await fn({get:ref=>ref.get(),set(ref,value){queued.push([ref.path,clone(value)]);}});for(const [key,value]of queued){docs.set(key,value);writes.push(key);}return result;}};}
const patch=(v=video)=>({url:`https://www.youtube.com/shorts/${v}`,title:'회화 문장',category:'language',notes:'복습',source:'manual',language:'en',sentences:[{start:null,text:'Could you help me?'},{start:3.25,text:'도와주시겠어요?'}]});
const save=(overrides={})=>({action:'save',videoId:video,requestId:'request-00000000001',expectedRevision:0,expectedLibraryRevision:0,patch:patch(),...overrides});
test('library writes only a separate owner document and preserves existing app records',async()=>{const db=memory(),before=clone(db.docs.get('users/owner-a/private/main'));const result=await libraryDispatch(db,a,save(),{now:100});assert.equal(result.row.url,`https://www.youtube.com/watch?v=${video}`);assert.equal(result.row.revision,1);assert.equal(result.row.sentences[0].start,null);assert.deepEqual(db.docs.get('users/owner-a/private/main'),before);assert.deepEqual(db.writes,[`users/owner-a/private/${LIBRARY_DOCUMENT}`]);assert.equal((await libraryDispatch(db,b,{action:'list'})).rows.length,0);assert.equal((await libraryDispatch(db,a,{action:'list'})).rows.length,1);});
test('receipt retries do not duplicate, edit or delete again; stale revisions never overwrite',async()=>{const db=memory(),command=save();await libraryDispatch(db,a,command);const retry=await libraryDispatch(db,a,clone(command));assert(retry.alreadyApplied);assert.equal(db.writes.length,1);await assert.rejects(libraryDispatch(db,a,save({requestId:'request-00000000002'})),e=>e.status===409);await assert.rejects(libraryDispatch(db,a,save({patch:{...patch(),title:'changed'}})),e=>e.status===409);const edit=await libraryDispatch(db,a,save({expectedRevision:1,requestId:'request-00000000003',patch:{...patch(),notes:'updated'}}));assert.equal(edit.row.revision,2);const remove={action:'delete',videoId:video,expectedRevision:2,requestId:'request-00000000004'};await libraryDispatch(db,a,remove);await libraryDispatch(db,a,remove);assert.equal((await libraryDispatch(db,a,{action:'list'})).rows.length,0);assert.equal(db.writes.length,3);});
test('search and categories cover the complete library and pagination has no missing or duplicate rows',async()=>{const db=memory();for(let i=0;i<43;i++){const id=String(i).padStart(11,'0');await libraryDispatch(db,a,save({videoId:id,expectedLibraryRevision:i,requestId:'paging-request-'+String(i).padStart(5,'0'),patch:{...patch(id),category:i%2?'recipe':'language',title:i===0?'처음 저장한 레시피':'링크 '+i}}),{now:1000+i});}const first=await libraryDispatch(db,a,{action:'list'}),second=await libraryDispatch(db,a,{action:'list',cursor:first.cursor}),third=await libraryDispatch(db,a,{action:'list',cursor:second.cursor});assert.equal(first.rows.length,20);assert.equal(second.rows.length,20);assert.equal(third.rows.length,3);assert.equal(new Set([...first.rows,...second.rows,...third.rows].map(r=>r.videoId)).size,43);assert.equal((await libraryDispatch(db,a,{action:'list',query:'처음 저장한'})).rows[0].videoId,'00000000000');assert.equal((await libraryDispatch(db,a,{action:'list',category:'recipe'})).total,21);assert.equal(db.docs.get(`users/${a.uid}/private/${LIBRARY_DOCUMENT}`).payload.receipts.length,32);});
test('invalid owner, mismatched video, oversized text, source and revision are rejected before writes',async()=>{const db=memory();await assert.rejects(libraryDispatch(db,null,save()),e=>e.status===401);for(const bad of [save({expectedRevision:-1}),save({patch:{...patch(),url:'https://youtu.be/12345678901'}}),save({patch:{...patch(),source:'imagined'}}),save({patch:{...patch(),sentences:[{start:-2,text:'bad'}]}}),save({patch:{...patch(),notes:'x'.repeat(2001)}}),save({patch:{...patch(),sentences:Array.from({length:9},()=>({start:null,text:'x'.repeat(4000)}))}})])await assert.rejects(libraryDispatch(db,a,bad));assert.equal(db.writes.length,0);});
test('library size and malformed existing payload failures preserve original documents',async()=>{const db=memory(),key=`users/${a.uid}/private/${LIBRARY_DOCUMENT}`;const big={revision:0,rows:Array.from({length:400},(_,i)=>({...patch(String(i).padStart(11,'0')),videoId:String(i).padStart(11,'0'),notes:'x'.repeat(1800),createdAt:1,updatedAt:1,revision:1})),receipts:[]};db.docs.set(key,{ownerUid:a.uid,schemaVersion:189,payload:big});await assert.rejects(libraryDispatch(db,a,save()),e=>e.status===413);assert.equal(db.writes.length,0);db.docs.set(key,{ownerUid:b.uid,schemaVersion:189,payload:{revision:0,rows:[],receipts:[]}});await assert.rejects(libraryDispatch(db,a,save()),e=>e.status===409);assert.equal(db.writes.length,0);});
test('Firestore map overhead rejects a sub-700KB JSON library before writes and preserves its original contents',async()=>{
  const db=memory(),key=`users/${a.uid}/private/${LIBRARY_DOCUMENT}`;
  const rows=Array.from({length:125},(_,i)=>({url:'https://www.youtube.com/watch?v='+String(i).padStart(11,'0'),videoId:String(i).padStart(11,'0'),title:'a',category:'language',notes:'',source:'manual',language:'en',sentences:Array.from({length:200},()=>({start:1,text:'a'})),revision:1,createdAt:1,updatedAt:1}));
  const original={ownerUid:a.uid,schemaVersion:189,payload:{rows,receipts:[],revision:0},updatedAt:1};
  assert(Buffer.byteLength(JSON.stringify(original))<700000);
  assert(firestoreDocumentBytes(key,original)>1048576);
  db.docs.set(key,clone(original));
  await assert.rejects(libraryDispatch(db,a,save()),error=>error.status===413&&error.message.includes('저장 용량'));
  assert.equal(db.writes.length,0);assert.deepEqual(db.docs.get(key),original);
});
test('Firestore sizing includes UTF-8 field names, scalar storage and map/path overhead',()=>{
  // Official document-size example: users/jeff/tasks/my_task_id = 44 path bytes,
  // four fields = 71 bytes, and 32 document bytes = 147 total.
  assert.equal(firestoreDocumentBytes('users/jeff/tasks/my_task_id',{type:'Personal',done:false,priority:1,description:'Learn Cloud Firestore'}),147);
  assert.equal(firestoreDocumentBytes('a/b',{가:[{나:'한',n:null,b:true,f:0.5}]}),112);
  assert.equal(MAX_FIRESTORE_DOCUMENT_BYTES,900000);
});
async function http(handler,req){const result={headers:{},setHeader(k,v){this.headers[k]=v;},end(body){this.body=JSON.parse(body);}};await handler(req,result);return result;}
test('HTTP API requires token and trusted origin, health is read-only, and import never saves',async()=>{let verified=0,imports=0,saves=0;const old=process.env.PUBLIC_APP_URL;process.env.PUBLIC_APP_URL='https://aiderdear1.vercel.app';try{const handler=createHandler({getServices:()=>({db:{},auth:{async verifyIdToken(token,revoked){assert.equal(token,'test-token');assert.equal(revoked,true);verified++;return a;}}}),loadVideo:async()=>{imports++;return{captionStatus:'unavailable'};},dispatch:async()=>{saves++;return{rows:[]};}});assert.equal((await http(handler,{method:'GET',url:'/?action=health',headers:{}})).body.version,189);assert.equal(verified,0);assert.equal((await http(handler,{method:'POST',headers:{},body:{action:'list'}})).statusCode,401);assert.equal((await http(handler,{method:'POST',headers:{origin:'https://attacker.invalid',authorization:'Bearer test-token'},body:{action:'import'}})).statusCode,403);const good=await http(handler,{method:'POST',headers:{origin:process.env.PUBLIC_APP_URL,authorization:'Bearer test-token'},body:{action:'import',ownerUid:a.uid,url:patch().url}});assert.equal(good.statusCode,200);assert.equal(imports,1);assert.equal(saves,0);assert.equal(good.headers['Cache-Control'],'private, no-store');}finally{if(old===undefined)delete process.env.PUBLIC_APP_URL;else process.env.PUBLIC_APP_URL=old;}});
function clientFixture(fetchImpl){let user={uid:'a'},listener;const events=new EventTarget();const firebase={getState:()=>({user}),getFirebaseIdToken:async()=> 'test-token',subscribe(fn){listener=fn;fn();return()=>{};}};const client=createYoutubeClient({getFirebase:()=>firebase,events,fetchImpl});return{client,firebase,change(u){user=u;listener();}};}
test('deletion/recreation never reuses revisions and an evicted create retry cannot resurrect a deleted record',async()=>{const db=memory(),original=save();await libraryDispatch(db,a,original);await libraryDispatch(db,a,{action:'delete',videoId:video,expectedRevision:1,requestId:'delete-request-000001'});const readded=await libraryDispatch(db,a,save({expectedLibraryRevision:2,requestId:'recreate-request-0001'}));assert.equal(readded.row.revision,3);await assert.rejects(libraryDispatch(db,a,save({expectedRevision:1,requestId:'stale-editor-request-1'})),e=>e.status===409);await libraryDispatch(db,a,{action:'delete',videoId:video,expectedRevision:3,requestId:'delete-request-000002'});for(let i=0;i<33;i++){const id=String(i).padStart(11,'0');await libraryDispatch(db,a,save({videoId:id,expectedLibraryRevision:i+4,requestId:'later-request-'+String(i).padStart(5,'0'),patch:patch(id)}));}await assert.rejects(libraryDispatch(db,a,original),e=>e.status===409);assert(!db.docs.get('users/'+a.uid+'/private/'+LIBRARY_DOCUMENT).payload.rows.some(row=>row.videoId===video));});
test('client discards a previous owner response and blocks a token resolved after account change',async()=>{let resolveReply,calls=0;const fx=clientFixture(()=>{calls++;return new Promise(r=>resolveReply=r);});const read=fx.client.list();await new Promise(r=>setImmediate(r));fx.change({uid:'b'});resolveReply({ok:true,json:async()=>({rows:[{title:'private-a'}]})});await assert.rejects(read,e=>e.status===401);let resolveToken;fx.firebase.getFirebaseIdToken=()=>new Promise(r=>resolveToken=r);const delayed=fx.client.list();fx.change(null);resolveToken('late');await assert.rejects(delayed,e=>e.status===401);assert.equal(calls,1);});
test('client retry after network loss reuses the mutation id across newly created input objects',async()=>{const bodies=[];const fx=clientFixture(async(url,opts)=>{const body=JSON.parse(opts.body);if(body.action==='list')return{ok:true,json:async()=>({rows:[],libraryRevision:0})};bodies.push(body);if(bodies.length===1)throw new TypeError('network');return{ok:true,json:async()=>({row:{videoId:video,revision:1}})};});await fx.client.list();bodies.length=0;const input={videoId:video,expectedRevision:0,patch:patch()};await assert.rejects(fx.client.save(clone(input)));await fx.client.save(clone(input));assert.equal(bodies[0].requestId,bodies[1].requestId);assert.equal(bodies[0].action,'save');});
