package com.aiderlog.v22app;
import org.json.JSONObject;
import org.json.JSONArray;
import java.util.Calendar;

/** Pure queue/overlay contracts; no Android UI methods run on the JVM. */
public final class WidgetPrivateContractV196 {
    static int checks=0;static final String UID="scope-a";static final String TODAY=WidgetNativeV164.day(Calendar.getInstance());
    static void require(boolean value,String name){checks++;if(!value)throw new AssertionError(name);}
    static JSONObject command(String suffix,String op,String id,String value)throws Exception{return new JSONObject().put("schema",196).put("uid",UID).put("op",op).put("id",id).put("key","widget-private-00000000-0000-0000-0000-"+suffix).put("value",value).put("date",TODAY).put("expectedUpdatedAt",10).put("kind",op.equals("routine")?"RoutineAll":"CalendarSplit").put("createdAt",System.currentTimeMillis()).put("state","pending");}
    static JSONObject snapshot()throws Exception{return new JSONObject().put("uid",UID).put("v165",new JSONObject().put("uid",UID).put("today",TODAY).put("routines",new JSONArray().put(new JSONObject().put("id","r1").put("title","독서").put("updatedAt",10).put("doneDates",new JSONArray()).put("dailyLevels",new JSONObject()))).put("todos",new JSONArray().put(new JSONObject().put("id","t1").put("title","할 일").put("updatedAt",10).put("done",false))).put("notes",new JSONArray()));}
    static JSONObject receipt(JSONObject data,JSONObject action,long revision,boolean rebase)throws Exception{JSONObject out=new JSONObject(data.toString()),proof=new JSONObject();for(String field:new String[]{"uid","key","id","op"})proof.put(field,action.optString(field));proof.put("revision",revision).put("rebase",rebase);return out.put("privateReceiptV196",proof);}
    static JSONObject ack(long revision,boolean rebase)throws Exception{return new JSONObject().put("revision",revision).put("rebase",rebase);}
    public static void main(String[] args)throws Exception{
        JSONObject first=command("111111111111","routine","r1","MAX"),second=command("222222222222","routine","r1","");
        JSONArray queue=WidgetPrivateV196.merge(new JSONArray(),first),coalesced=WidgetPrivateV196.merge(queue,second);require(coalesced.length()==1,"unclaimed routine/day coalesces");require(coalesced.getJSONObject(0).optString("key").equals(second.optString("key")),"latest action gets fresh key");require(coalesced.getJSONObject(0).optString("value").isEmpty(),"undo is explicit blank");
        JSONArray claimed=WidgetPrivateV196.claim(queue);JSONObject claim=WidgetPrivateV196.claimed(claimed);String frozen=claim.toString();require(claim.optString("state").equals("claimed"),"durable claim precedes request");require(WidgetPrivateV196.claim(claimed).toString().equals(claimed.toString()),"claim replay byte stable");JSONArray successor=WidgetPrivateV196.merge(claimed,second);require(successor.length()==2,"inflight command never coalesced");require(successor.getJSONObject(0).toString().equals(frozen),"inflight payload frozen");require(successor.getJSONObject(1).optString("parentKey").equals(first.optString("key")),"successor linked to predecessor");
        JSONObject base=snapshot();JSONArray success=WidgetPrivateV196.acknowledge(successor,receipt(base,first,20,true),UID,first.optString("key"),ack(20,true));require(success.length()==1,"ack removes exactly claimed command");require(success.getJSONObject(0).optLong("expectedUpdatedAt")==20,"fresh successful predecessor rebases successor");require(!success.getJSONObject(0).has("parentKey"),"dependency cleared afterack");require(success.getJSONObject(0).optString("key").equals(second.optString("key")),"unclaimed successor key preserved beforeclaim");
        JSONArray replay=WidgetPrivateV196.acknowledge(successor,receipt(base,first,99,false),UID,first.optString("key"),ack(99,false));require(replay.getJSONObject(0).optLong("expectedUpdatedAt")==10,"replay cannot rebase onto unrelated remote edit");require(WidgetPrivateV196.acknowledge(successor,base,UID,first.optString("key"),ack(20,true))==successor,"proof missing refusesack");require(WidgetPrivateV196.acknowledge(successor,receipt(base,first,20,true),UID,first.optString("key"),ack(21,true))==successor,"wrong revision refusesack");require(WidgetPrivateV196.acknowledge(successor,receipt(base,first,20,false),UID,first.optString("key"),ack(20,true))==successor,"cannot forge rebase");require(WidgetPrivateV196.acknowledge(successor,receipt(base,first,20,true),"other",first.optString("key"),ack(20,true))==successor,"owner cannot acknowledge another queue");
        JSONObject absent=new JSONObject(base.toString());absent.getJSONObject("v165").put("notes",new JSONArray());JSONObject memo=command("333333333333","add-memo","memo1","본문");JSONArray memoClaim=WidgetPrivateV196.claim(new JSONArray().put(memo));require(WidgetPrivateV196.acknowledge(memoClaim,receipt(absent,memo,22,true),UID,memo.optString("key"),ack(22,true)).length()==0,"offscreen memo acknowledges with authenticated receipt proof");
        JSONArray failed=WidgetPrivateV196.failure(claimed,UID,first.optString("key"),"widget/stale-action");require(failed.getJSONObject(0).optString("state").equals("failed"),"terminal failure stored");require(WidgetPrivateV196.claimed(WidgetPrivateV196.claim(failed))==null,"failed does not retry forever");JSONArray next=WidgetPrivateV196.claim(WidgetPrivateV196.merge(failed,command("444444444444","routine","r2","MINI")));require(WidgetPrivateV196.claimed(next).optString("id").equals("r2"),"failed record cannot block unrelated jobs");
        String raw=base.toString();JSONObject projected=WidgetPrivateV196.project(base,queue),routine=projected.getJSONObject("v165").getJSONArray("routines").getJSONObject(0);require(routine.getJSONArray("doneDates").length()==1,"completion overlays one date immediately");require(routine.getJSONObject("dailyLevels").optString(TODAY).equals("MAX"),"MAX overlay immediate");require(projected.getJSONObject("v165").getJSONObject("routineStats").optInt("todayDone")==1,"header reflects optimistic completion");require(WidgetRoutineV195.summary(projected).optInt("occurrences")==1,"weekly graph reflects optimistic completion");require(base.toString().equals(raw),"raw snapshot unchanged");require(routine.optLong("updatedAt")==10,"overlay does not invent cloud revision");
        JSONObject undo=WidgetPrivateV196.project(base,successor);require(undo.getJSONObject("v165").getJSONArray("routines").getJSONObject(0).getJSONArray("doneDates").length()==0,"latest queued undo wins over claimed completion");JSONObject rollback=WidgetPrivateV196.project(base,failed);require(rollback.getJSONObject("v165").getJSONObject("routineStats").optInt("todayDone")==0,"terminal failure rolls back optimistic completion");require(rollback.getJSONObject("v165").getJSONArray("routines").getJSONObject(0).optString("_widgetFailedV196").equals("widget/stale-action"),"failure remains visible");
        JSONObject todo=command("555555555555","todo","t1","true");JSONObject doneTodo=WidgetPrivateV196.project(base,new JSONArray().put(todo));require(doneTodo.getJSONObject("v165").getJSONArray("incompleteTodos").length()==0,"completed todo removed from unfinished list");JSONObject added=WidgetPrivateV196.project(base,new JSONArray().put(memo).put(command("666666666666","add-todo","newtodo","새 할 일")));require(added.getJSONObject("v165").getJSONArray("notes").getJSONObject(0).optString("title").equals("본문"),"memo content immediate");require(added.getJSONObject("v165").getJSONArray("notes").getJSONObject(0).optString("source").equals("checklists"),"memo routes actual legacy collection");require(added.getJSONObject("v165").getJSONArray("todos").getJSONObject(0).optString("title").equals("새 할 일"),"todo add immediate");JSONArray repeated=WidgetPrivateV196.merge(new JSONArray().put(memo),memo);require(repeated.length()==1,"form retry idempotent");
        JSONObject other=new JSONObject(base.toString()).put("uid","other");other.getJSONObject("v165").put("uid","other");require(WidgetPrivateV196.project(other,queue).getJSONObject("v165").getJSONArray("routines").getJSONObject(0).getJSONArray("doneDates").length()==0,"other owner sees no overlay");JSONObject anonymous=new JSONObject(base.toString()).put("uid","");require(WidgetPrivateV196.project(anonymous,queue).toString().equals(anonymous.toString()),"anonymous snapshot untouched");
        JSONObject gesture=new JSONObject(first.toString()).put("toggleComplete",true).put("date","2026-09-26");JSONObject midnight=WidgetPrivateV196.gesture(gesture,base,TODAY);require(midnight.optString("date").equals(TODAY),"stale midnight gesture applies current local day");require(midnight.optString("value").equals("MAX"),"first completion sets MAX");require(WidgetPrivateV196.gesture(gesture,projected,TODAY).optString("value").isEmpty(),"repeated completion undoes before cloud sync");require(WidgetPrivateV196.normalize(first,UID).optString("date").equals(TODAY),"queued date preserved when normalized");
        JSONObject linked=new JSONObject(base.toString());linked.getJSONObject("v165").getJSONArray("routines").getJSONObject(0).put("goalTracking",new JSONObject().put("goal-a",new JSONObject().put(TODAY,true)));require(WidgetPrivateV196.goalLinked(linked.getJSONObject("v165").getJSONArray("routines").getJSONObject(0)),"goal-linked recognized");boolean rejected=false;try{WidgetPrivateV196.gesture(gesture,linked,TODAY);}catch(IllegalArgumentException error){rejected=true;}require(rejected,"goal-linked gesture cannot fake completion");require(WidgetPrivateV196.project(linked,queue).getJSONObject("v165").getJSONArray("routines").getJSONObject(0).getJSONArray("doneDates").length()==0,"goal-linked overlay refuses mutation");
        JSONArray full=new JSONArray();for(int i=0;i<100;i++)full.put(command("700000000000"+i,"add-memo","m"+i,"메모"));rejected=false;try{WidgetPrivateV196.merge(full,memo);}catch(IllegalArgumentException error){rejected=true;}require(rejected,"queue cap100 prevents unbounded storage");require(full.length()==100,"capacity error preserves drafts");rejected=false;try{WidgetPrivateV196.normalize(new JSONObject(first.toString()).put("uid","other"),UID);}catch(IllegalArgumentException error){rejected=true;}require(rejected,"normalizer rejects foreignowner");
        JSONObject newTodo=command("888888888888","add-todo","newtodo","추가 뒤 완료"),completeNew=command("999999999999","todo","newtodo","true").put("expectedUpdatedAt",newTodo.optLong("createdAt"));JSONArray addAndDone=WidgetPrivateV196.merge(new JSONArray().put(newTodo),completeNew);JSONObject localAdded=WidgetPrivateV196.project(base,addAndDone);require(WidgetPrivateV196.modelRow(localAdded,completeNew).optBoolean("done"),"new local todo can complete before anycloudsync");JSONArray addClaim=WidgetPrivateV196.claim(addAndDone);require(addClaim.getJSONObject(1).optString("parentKey").equals(newTodo.optString("key")),"add then complete dependency created atclaim");JSONArray addAck=WidgetPrivateV196.acknowledge(addClaim,receipt(base,newTodo,200,true),UID,newTodo.optString("key"),ack(200,true));require(addAck.getJSONObject(0).optLong("expectedUpdatedAt")==200,"newtodo completion rebases to actual addcloudrevision");
        JSONObject otherDay=command("999999999998","routine","r1","MORE").put("date","2026-09-20");JSONArray twoDates=WidgetPrivateV196.claim(WidgetPrivateV196.merge(queue,otherDay));require(twoDates.length()==2,"different routine dates do notcoalesce");require(twoDates.getJSONObject(1).optString("parentKey").equals(first.optString("key")),"different dates still share rowrevision dependency");require(WidgetPrivateV196.acknowledge(twoDates,receipt(base,first,30,true),UID,first.optString("key"),ack(30,true)).getJSONObject(0).optLong("expectedUpdatedAt")==30,"differentdate successor rebases safely");
        require(WidgetPrivateV196.gesture(todo,doneTodo,TODAY).optString("value").equals("true"),"repeatedtodo completion is idempotent");
        JSONArray archive=new JSONArray();for(int i=0;i<100;i++)archive=WidgetPrivateV196.archive(archive,command("800000000000"+i,"add-memo","memo-"+i,"복구할 본문 "+i).put("state","failed"));for(int i=0;i<30;i++)archive=WidgetPrivateV196.archive(archive,command("900000000000"+i,"routine","routine-"+i,"MAX").put("state","failed"));require(WidgetPrivateV196.addCount(archive)==100,"failurearchive neverevicts addtext");require(archive.length()==120,"mutationfailurestatus bounded20 independentlyof100drafts");require(WidgetPrivateV196.findByKey(archive,"widget-private-00000000-0000-0000-0000-8000000000000").optString("value").equals("복구할 본문 0"),"oldest draft remainsrecoverable");JSONArray retryArchive=WidgetPrivateV196.clearReplaced(archive,memo,"widget-private-00000000-0000-0000-0000-8000000000000");require(WidgetPrivateV196.addCount(retryArchive)==99,"explicitretry freesexactone archiveentry");require(WidgetPrivateV196.addCount(archive)==100,"retry preparation nevermutates persistedarchive");require(WidgetPrivateV196.claim(new JSONArray().put(first)).length()==1,"failedarchive cannotblockactivequeue");
        JSONObject deleted=new JSONObject(base.toString());deleted.getJSONObject("v165").put("notes",new JSONArray());require(WidgetPrivateV196.acknowledge(memoClaim,receipt(deleted,memo,0,false),UID,memo.optString("key"),ack(0,false)).length()==0,"authenticated deletedrecord receipt retiresoverlay withoutresurrection");
        System.out.println("PASS "+checks+" native private queue/overlay contracts");
    }
}
