package com.aiderlog.v22app;
import org.json.JSONObject;
import org.json.JSONArray;

/** Desktop JVM contracts: no Android UI or network calls. */
public final class WidgetCalendarContractV195 {
    static int count=0;
    static void check(boolean condition,String label){count++;if(!condition)throw new AssertionError(label);}
    static JSONObject command(String suffix)throws Exception{return new JSONObject().put("schema",195).put("op","add-schedule").put("uid","owner-a").put("id","widget-calendar-00000000-0000-4000-8000-"+suffix).put("title","위젯에서 추가한 일정").put("date","2026-10-09").put("endDate","2026-10-09").put("time","09:30").put("allDay",false).put("createdAt",System.currentTimeMillis());}
    static void rejects(JSONObject value,String label){boolean failed=false;try{WidgetCalendarV195.normalize(value,"owner-a");}catch(IllegalArgumentException e){failed=true;}check(failed,label);}
    public static void main(String[]args)throws Exception{
        JSONObject add=WidgetCalendarV195.normalize(command("000000000001"),"owner-a");check(add.optString("time").equals("09:30"),"timed title/date entry");JSONObject all=WidgetCalendarV195.normalize(command("000000000002").put("allDay",true),"owner-a");check(all.optString("time").isEmpty(),"all-day canonical empty time");
        for(String bad:new String[]{"2026-02-30","1999-12-31","2200-01-01","2026-1-01"})rejects(command("000000000003").put("date",bad).put("endDate",bad),"invalid date "+bad);
        for(String bad:new String[]{"24:00","09:60","9:00",""})rejects(command("000000000003").put("time",bad),"invalid time "+bad);
        rejects(command("000000000003").put("uid","owner-b"),"other owner rejected");rejects(command("000000000003").put("allDay","false"),"nonboolean allDay rejected");rejects(command("000000000003").put("id","widget-calendar-short"),"short identity rejected");rejects(command("000000000003").put("createdAt",0),"invalid timestamp rejected");rejects(command("000000000003").put("createdAt",System.currentTimeMillis()+172800000L),"future timestamp rejected");rejects(command("000000000003").put("title","   "),"blank title rejected");rejects(command("000000000003").put("title",new String(new char[181]).replace('\0','a')),"oversized title rejected");
        JSONArray queue=WidgetCalendarV195.merge(new JSONArray(),add);check(queue.length()==1,"append one command");check(WidgetCalendarV195.merge(queue,new JSONObject(add.toString())).length()==1,"retry same command is idempotent");boolean mismatch=false;try{WidgetCalendarV195.merge(queue,new JSONObject(add.toString()).put("title","다른 내용"));}catch(IllegalArgumentException e){mismatch=true;}check(mismatch,"same ID cannot replace command");JSONArray full=new JSONArray();for(int i=0;i<100;i++)full.put(command(String.format("%012d",i)));boolean bound=false;try{WidgetCalendarV195.merge(full,command("999999999999"));}catch(IllegalArgumentException e){bound=true;}check(bound&&full.length()==100,"outbox bounded without deleting drafts");
        JSONObject old=new JSONObject().put("id","old").put("title","기존 일정").put("date","2026-10-09").put("endDate","2026-10-09");JSONObject snapshot=new JSONObject().put("uid","owner-a").put("v165",new JSONObject().put("uid","owner-a")).put("scheduleItems",new JSONArray().put(old)).put("unknown","keep");String original=snapshot.toString();JSONObject projected=WidgetCalendarV195.project(snapshot,queue);check(projected.getJSONArray("scheduleItems").length()==2,"pending event appears immediately");check(projected.getJSONArray("scheduleItems").getJSONObject(1).optBoolean("_widgetPendingV195"),"honest pending marker");check(snapshot.toString().equals(original)&&projected.optString("unknown").equals("keep"),"projection preserves raw/unknown data");
        JSONObject foreign=new JSONObject(snapshot.toString()).put("uid","owner-b").put("v165",new JSONObject().put("uid","owner-b"));check(WidgetCalendarV195.project(foreign,queue).getJSONArray("scheduleItems").length()==1,"another owner never sees queue");JSONObject blank=new JSONObject().put("uid","").put("scheduleItems",new JSONArray());check(WidgetCalendarV195.project(blank,queue).getJSONArray("scheduleItems").length()==0&&queue.length()==1,"blank auth snapshot hides but retains queued draft");check(WidgetCalendarV195.owner(new JSONObject(snapshot.toString()).put("uid","owner-b")).isEmpty(),"mismatched snapshot/model UID is unverified");
        check(WidgetCalendarV195.acknowledge(queue,snapshot,"owner-a",add.optString("id")).length()==1,"unconfirmed ack cannot discard local save");JSONObject cloud=new JSONObject(snapshot.toString());cloud.getJSONArray("scheduleItems").put(new JSONObject(add.toString()).put("confirmed",true).put("widgetCreatedV195",true).put("authorUid","owner-a"));JSONObject confirmed=WidgetCalendarV195.project(cloud,queue);check(confirmed.getJSONArray("scheduleItems").length()==2,"confirmed ID dedupes pending projection");check(confirmed.getJSONArray("scheduleItems").getJSONObject(1).optBoolean("confirmed")&&!confirmed.getJSONArray("scheduleItems").getJSONObject(1).optBoolean("_widgetPendingV195"),"confirmed row wins");check(WidgetCalendarV195.acknowledge(queue,cloud,"owner-a",add.optString("id")).length()==0,"confirmed ack retires matching ID");check(queue.length()==1,"ack does not mutate original queue");check(WidgetCalendarV195.acknowledge(queue,cloud,"owner-b",add.optString("id")).length()==1,"other owner cannot acknowledge");JSONObject wrong=new JSONObject(cloud.toString());wrong.getJSONArray("scheduleItems").getJSONObject(1).put("title","different");check(WidgetCalendarV195.acknowledge(queue,wrong,"owner-a",add.optString("id")).length()==0,"later cloud edits acknowledge committed identity without overwrite");wrong.getJSONArray("scheduleItems").getJSONObject(1).put("authorUid","owner-b");check(WidgetCalendarV195.acknowledge(queue,wrong,"owner-a",add.optString("id")).length()==1,"foreign author cannot acknowledge same ID");wrong.getJSONArray("scheduleItems").getJSONObject(1).put("authorUid","owner-a").remove("widgetCreatedV195");check(WidgetCalendarV195.acknowledge(queue,wrong,"owner-a",add.optString("id")).length()==1,"missing cloud marker retains pending draft");
        JSONArray many=new JSONArray();for(int i=0;i<200;i++)many.put(new JSONObject(old.toString()).put("id","event"+i).put("title","일정"+i));check(WidgetCompactCalendarV181.scheduleRows(many,"2026-10-09").size()==200,"day dialog model includes all events beyond cell capacity");check(WidgetCompactCalendarV181.capacity(90,16,true)==WidgetCompactCalendarV181.capacity(90,16,false),"inline holiday consumes no event row");
        JSONArray spanning=new JSONArray().put(new JSONObject(old.toString()).put("allDay",true).put("date","2026-10-08").put("endDate","2026-10-10"));check(WidgetCompactCalendarV181.scheduleRows(spanning,"2026-10-09").size()==1,"multi-day event is listed on middle date");check(WidgetCompactCalendarV181.scheduleRows(spanning,"2026-10-11").isEmpty(),"multi-day event outside range omitted");check(WidgetCompactCalendarV181.eventTimeLabel(spanning.getJSONObject(0)).equals("종일"),"all-day event label");check(WidgetCompactCalendarV181.inlineHoliday("한글날",0).equals("·"),"tiny mini cell uses inline holiday marker");check(WidgetCompactCalendarV181.inlineHoliday("한글날",1).equals("한"),"narrow mini cell uses readable prefix");check(WidgetCompactCalendarV181.inlineHoliday("한글날",4).equals("한글날"),"wide cell retains full holiday");System.out.println("PASS "+count+" native calendar queue/day contracts");
    }
}
