package com.aiderlog.v22app;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.charset.StandardCharsets;
import java.util.List;
import org.json.JSONObject;
import org.json.JSONArray;
public final class WidgetCoreContractV195 {
    static int assertions=0;
    static void require(boolean condition,String name){assertions++;if(!condition)throw new AssertionError(name);}
    public static void main(String[] args)throws Exception{
        JSONObject data=new JSONObject(new String(Files.readAllBytes(Paths.get(args[0])),StandardCharsets.UTF_8));
        for(String kind:new String[]{"CalendarMonth","CalendarCombined","CalendarSplit","CalendarFortnight","RoutineAll"}){require(WidgetProvider.supports(kind),"retained "+kind);require(WidgetProvider.supports("com.aiderlog.v22app.WidgetProvider$"+kind),"component "+kind);}
        for(String kind:new String[]{"RoutineCards","RoutineStats","CalendarAgenda","PersonalTodo","TaskWeek",""}){require(!WidgetProvider.supports(kind),"retired "+kind);require(WidgetNativeV164.rows(null,1,kind,data).isEmpty(),"retired rows "+kind);require(WidgetNativeV164.row(null,1,kind,"{}",0,null,-1)==null,"retired renderer "+kind);}
        List<String> daily=WidgetRoutineV195.rows("RoutineAll",data,new JSONObject().put("id","stretch")),weekly=WidgetRoutineV195.rows("RoutineAll@week",data,new JSONObject());require(daily.size()==5,"all routines retained regardless legacy configured selection");require(weekly.size()==2,"only practiced routines in calendar week");
        JSONObject first=new JSONObject(weekly.get(0)),second=new JSONObject(weekly.get(1));require(first.optString("title").equals("독서")&&second.optString("title").equals("스트레칭"),"named weekly rows preserve identities");require(first.optInt("weekCount")==2&&second.optInt("weekCount")==1,"practice count includes positive level without done date");
        require(WidgetRoutineV194.validOwner(first,data),"weekly owner bound");require(!WidgetRoutineV194.validOwner(first,new JSONObject().put("v165",new JSONObject().put("uid","other"))),"stale row rejected");JSONObject anonymous=new JSONObject(data.toString());anonymous.getJSONObject("v165").put("uid","");require(WidgetRoutineV195.rows("RoutineAll@week",anonymous,new JSONObject()).isEmpty(),"anonymous weekly collection blank");
        JSONArray dates=first.getJSONArray("weekDates"),marks=first.getJSONArray("week");require(dates.optString(0).equals("2026-09-21")&&dates.optString(6).equals("2026-09-27"),"Monday-Sunday current calendar week");require(marks.optBoolean(0)&&marks.optBoolean(1)&&!marks.optBoolean(2),"SKIP overrides legacy doneDates");for(int i=3;i<7;i++)require(!marks.optBoolean(i),"future day excluded "+i);
        require(WidgetDesignV165.stableId(first.toString(),0)!=WidgetDesignV165.stableId(daily.get(0),0),"daily and weekly stable identities distinct");
        for(float height:new float[]{250,280,336,500}){require(Math.abs(WidgetRoutineV195.listHeight(height)-2*WidgetRoutineV195.weekHeight(height))<.01,"body has 2:1 split "+height);require(!WidgetRoutineV195.compactStats(height,1),"minimum250 and normal heights keep full fixed summary "+height);require(WidgetRoutineV195.previewRows(height,12,false)>=1,"minimum preview has complete action row "+height);}
        require(WidgetRoutineV195.compactStats(170,1),"legacy instance uses counts-only fixed summary");
        require(WidgetRoutineV195.previewRows(280,12,false)==2,"compact preview clips no action row");require(!WidgetRoutineV195.showNames(250,1)&&!WidgetRoutineV195.showNames(280,1)&&WidgetRoutineV195.showNames(360,1),"optional names never crowd seven fixed day counts");require(WidgetRoutineV195.previewRows(336,24,false)<WidgetRoutineV195.previewRows(336,12,false),"large font reduces visible preview rows");
        for(String[] boundary:new String[][]{{"2026-09-27","2026-09-21","2026-09-27"},{"2026-09-28","2026-09-28","2026-10-04"},{"2027-01-01","2026-12-28","2027-01-03"}}){JSONArray week=WidgetRoutineV195.weekDates(new JSONObject().put("today",boundary[0]));require(week.optString(0).equals(boundary[1])&&week.optString(6).equals(boundary[2]),"native calendar boundary "+boundary[0]);}
        JSONObject sunday=new JSONObject("{\"v165\":{\"uid\":\"scope-user-a\",\"today\":\"2026-09-27\",\"routineStats\":{\"todayDone\":1,\"total\":1},\"routines\":[{\"id\":\"sunday\",\"title\":\"일요일 기록\",\"level\":\"MAX\",\"doneDates\":[\"2026-09-27\"],\"dailyLevels\":{\"2026-09-27\":\"MAX\"}}]}}");String original=sunday.toString();JSONObject monday=WidgetRoutineV195.atDay(sunday,"2026-09-28"),mondayModel=WidgetDesignV165.model(monday);require(mondayModel.optString("today").equals("2026-09-28"),"runtime uses device local date after stale snapshot");require(mondayModel.getJSONObject("routineStats").optInt("todayDone")==0,"Monday count excludes Sunday completion");require(mondayModel.getJSONArray("routines").getJSONObject(0).optString("level").isEmpty(),"Monday actions have no selected Sunday level");require(WidgetRoutineV195.rowsAt("RoutineAll@week",sunday,new JSONObject(),"2026-09-28").isEmpty(),"Monday starts new calendar week without app sync");JSONObject mondayRow=new JSONObject(WidgetRoutineV195.rowsAt("RoutineAll",sunday,new JSONObject(),"2026-09-28").get(0));require(mondayRow.optString("_date").equals("2026-09-28"),"Monday action payload binds new local day");require(sunday.toString().equals(original),"clock reprojection never changes stored snapshot");
        JSONObject manyModel=new JSONObject().put("uid","scope-user-a").put("today","2026-09-27");JSONArray many=new JSONArray();for(int i=0;i<30;i++){JSONArray done=new JSONArray().put("2026-09-21");if(i%2==0)done.put("2026-09-22");many.put(new JSONObject().put("id","r"+i).put("title","Routine"+i).put("doneDates",done));}manyModel.put("routines",many);JSONObject aggregate=WidgetRoutineV195.summary(new JSONObject().put("v165",manyModel));require(aggregate.optInt("practiced")==30&&aggregate.optInt("total")==30,"aggregate includes all routines beyond visible list rows");require(aggregate.optInt("occurrences")==45,"aggregate totals all practice-day occurrences");require(aggregate.getJSONArray("counts").optInt(0)==30&&aggregate.getJSONArray("counts").optInt(1)==15,"fixed chart daily counts include all30 routines");require(aggregate.optString("names").equals("Routine0, Routine1 외 28개"),"optional compact names summarize identities without shrinking counts");require(WidgetRoutineV195.summary(monday).optInt("occurrences")==0,"fixed summary rebases on Monday too");require(WidgetRoutineV195.summary(anonymous).optInt("total")==0,"anonymous summary hides stored routine totals");
        require(WidgetCompactCalendarV181.memoRows(data).size()==2,"calendar memo model unchanged");require(WidgetCompactCalendarV181.incompleteRows(data,false).size()==1,"calendar todo model unchanged");System.out.println("PASS "+assertions+" v195 native widget assertions");
    }
}
