package com.aiderlog.v22app;
import android.content.*;import android.widget.*;import android.text.*;import android.text.style.*;import org.json.*;import java.util.*;
/** Production color-binding calls; typography/Android span parceling needs device validation. */
public final class WidgetColorRenderContractV198 {
 static int checks;static void check(boolean value,String label){checks++;if(!value)throw new AssertionError(label);}static int id(Context c,String s){return WidgetNativeV164.id(c,s);}
 static List<RemoteViews> all(RemoteViews root){List<RemoteViews> out=new ArrayList<RemoteViews>();out.add(root);for(List<RemoteViews> children:root.children.values())for(RemoteViews child:children)out.addAll(all(child));return out;}
 public static void main(String[] args)throws Exception{
  WidgetTransportContractV197.reset();Context c=WidgetTransportContractV197.c;String today=WidgetTransportContractV197.TODAY;JSONObject data=WidgetTransportContractV197.raw(10);JSONArray events=new JSONArray().put(new JSONObject().put("id","gcal-a-1").put("title","Calendar A").put("date",today).put("color","#966B4B")).put(new JSONObject().put("id","gcal-b-1").put("title","Calendar B").put("date",today).put("color","#765545"));data.put("scheduleItems",events);WidgetTransportContractV197.storage.put("widget_snapshot",data.toString());
  for(String theme:WidgetThemeV190.KEYS){WidgetSizeV169.active.set(new android.util.SizeF(360,480));RemoteViews month=new RemoteViews(c.getPackageName(),1);WidgetCompactCalendarV181.calendar(c,month,7,"CalendarMonth",data,theme,-1,-1);Set<Integer> colors=new HashSet<Integer>();for(RemoteViews view:all(month)){Integer color=view.backgroundColors.get(id(c,"w184_event_title"));if(color!=null)colors.add(color);}check(colors.contains(0x22966b4b)&&colors.contains(0x22765545),"month chip colors retained "+theme);
   RemoteViews mini=new RemoteViews(c.getPackageName(),1);WidgetCompactCalendarV181.calendar(c,mini,7,"CalendarCombined",data,theme,-1,-1);boolean colored=false;for(RemoteViews view:all(mini)){CharSequence text=view.sequences.get(id(c,"w184_dots"));if(text instanceof SpannableString&&text.length()==2){SpannableString spans=(SpannableString)text;check(spans.spans.size()==2,"eachdot has style "+theme);Set<Integer> dots=new HashSet<Integer>();for(Object span:spans.spans)dots.add(((ForegroundColorSpan)span).getForegroundColor());colored=dots.contains(0xff966b4b)&&dots.contains(0xff765545);}}check(colored,"mini two calendars use resolvedbrowns "+theme);
   for(int i=0;i<events.length();i++){RemoteViews row=WidgetCompactCalendarV181.row(c,7,"CalendarFortnight",events.getJSONObject(i).toString(),i,theme,-1);check(row.backgroundColors.get(id(c,"w184_event_mark")).intValue()==WidgetCompactCalendarV181.eventColor(events.getJSONObject(i)),"agenda stripe retainscolor "+theme+i);check(row.textColors.get(id(c,"w184_event_title")).intValue()==WidgetThemeV190.color(theme,4),"agenda keeps readablethemetext "+theme+i);}
  }WidgetSizeV169.active.remove();System.out.println("PASS "+checks+" production calendar color binding contracts (recorded Android API boundary)");
 }
}