package com.aiderlog.v22app;
import android.content.*;import android.app.*;import android.appwidget.*;import android.widget.*;import org.json.*;import java.util.*;import java.lang.reflect.*;
/** Executes production render/Intent/receiver/queue code against recording Android boundaries. */
public final class WidgetTransportContractV197 {
 static int checks;static final String UID="scope-a",TODAY=WidgetNativeV164.day(Calendar.getInstance());static Context c;static Map<String,Object> storage=new HashMap<String,Object>();
 static void check(boolean yes,String message){checks++;if(!yes)throw new AssertionError(message);}
 static SharedPreferences prefs(){return (SharedPreferences)Proxy.newProxyInstance(WidgetTransportContractV197.class.getClassLoader(),new Class[]{SharedPreferences.class},(proxy,m,args)->{String n=m.getName();if(n.equals("edit")){Map<String,Object> changes=new HashMap<String,Object>();Set<String> removed=new HashSet<String>();return Proxy.newProxyInstance(WidgetTransportContractV197.class.getClassLoader(),new Class[]{SharedPreferences.Editor.class},(editor,e,a)->{String en=e.getName();if(en.startsWith("put")){changes.put((String)a[0],a[1]);return editor;}if(en.equals("remove")){removed.add((String)a[0]);return editor;}if(en.equals("clear")){storage.clear();return editor;}if(en.equals("commit")||en.equals("apply")){for(String key:removed)storage.remove(key);storage.putAll(changes);return en.equals("commit")?true:null;}return null;});}if(n.equals("getAll"))return new HashMap<String,Object>(storage);if(n.equals("contains"))return storage.containsKey(args[0]);if(n.startsWith("get"))return storage.containsKey(args[0])?storage.get(args[0]):args[1];return null;});}
 static JSONObject raw(long revision)throws Exception{return new JSONObject().put("uid",UID).put("v165",new JSONObject().put("uid",UID).put("today",TODAY).put("routines",new JSONArray().put(new JSONObject().put("id","r1").put("title","독서").put("updatedAt",revision).put("dailyLevels",new JSONObject()).put("doneDates",new JSONArray()))).put("todos",new JSONArray().put(new JSONObject().put("id","t1").put("title","할 일").put("updatedAt",revision).put("done",false))).put("notes",new JSONArray()));}
 static void reset()throws Exception{storage.clear();storage.put("widget_snapshot",raw(10).toString());c=new Context();c.preferences=prefs();RemoteViews.failInline=false;android.os.Build.VERSION.SDK_INT=35;AppWidgetManager.instance.options=new android.os.Bundle();AppWidgetManager.instance.updated.clear();AppWidgetManager.instance.infos.clear();AppWidgetProviderInfo info=new AppWidgetProviderInfo();info.provider=new ComponentName(c.getPackageName(),c.getPackageName()+".WidgetProvider$RoutineAll");AppWidgetManager.instance.infos.put(7,info);}
 static int id(String name){return WidgetNativeV164.id(c,name);}static RemoteViews render(){return WidgetRoutineV195.render(c,7,"RoutineAll",false,null,-1,-1);}static RemoteViews first(RemoteViews root){return root.collections.get(id("widget_items_v164")).rows.get(0);}static Intent delivered(RemoteViews root,int index){return root.templates.get(id("widget_items_v164")).deliver(first(root).fills.get(id("w194_level_"+index)));}
 static JSONObject decode(Intent intent)throws Exception{return new JSONObject(android.net.Uri.decode(intent.getStringExtra("action").substring("widget-v165:".length())));}
 static String level(){return WidgetDesignV165.model(WidgetNativeV164.snapshot(c)).optJSONArray("routines").optJSONObject(0).optString("level");}
 public static void main(String[] args)throws Exception{
  reset();RemoteViews before=render();PendingIntent pi=before.templates.get(id("widget_items_v164"));check(pi.type.equals("broadcast"),"routine template direct broadcast");check((pi.flags&PendingIntent.FLAG_MUTABLE)!=0,"API31 template mutable");check(!pi.base.hasExtra("action"),"base template does not overwrite row action");check(first(before).text.get(id("w194_level_2")).equals("MAX"),"unselected MAX exactlabel");Intent max=delivered(before,2);check(decode(max).optString("value").equals("MAX"),"actual rendered MAX fillin survives AOSP extrasmerge");check(max.getStringExtra("boundUid").equals(UID),"template owner survivesmerge");check(decode(max).optLong("expectedUpdatedAt")==10,"rendered expectedrevision survivesmerge");new WidgetActionReceiverV196().onReceive(c,max);check(level().equals("MAX"),"real receiver path overlays MAX withoutWebView");check(WidgetPrivateV196.read(c,UID).length()==1,"click stores one durable command");RemoteViews refreshed=AppWidgetManager.instance.updated.get(7);check(refreshed!=null,"clicked instance directly refreshed with no installedprovider enumeration");check(first(refreshed).text.get(id("w194_level_2")).equals("MAX"),"selected MAX exactlabel");check(first(refreshed).background.get(id("w194_level_2"))!=first(before).background.get(id("w194_level_2")),"selectedbackground changes");check(refreshed.text.get(id("widget_subtitle")).contains("1 / 1"),"header immediate completion");check(refreshed.text.get(id("w195_week_title")).contains("총 1회"),"weekly aggregate immediate completion");new WidgetActionReceiverV196().onReceive(c,max);check(level().isEmpty(),"repeat same alreadydelivered MAX uses currentoverlay andundoes");check(WidgetPrivateV196.read(c,UID).length()==1,"rapidundo coalesces freshkey");check(WidgetRoutineV195.summary(WidgetNativeV164.snapshot(c)).optInt("occurrences")==0,"undo updatesaggregate");
  for(int button:new int[]{0,1,3}){new WidgetActionReceiverV196().onReceive(c,delivered(render(),button));check(level().equals(new String[]{"MINI","MORE","MAX","SKIP"}[button]),"other button actualtransport "+button);}
  check(WidgetRoutineV195.summary(WidgetNativeV164.snapshot(c)).optInt("occurrences")==0,"SKIP excluded from aggregate");
  reset();before=render();max=delivered(before,2);storage.put("widget_snapshot",raw(20).toString());new WidgetActionReceiverV196().onReceive(c,max);check(WidgetPrivateV196.read(c,UID).length()==0,"stale host fillin revision rejected withoutbypassing conflictguard");check(Toast.last.contains("다른 곳"),"stale row gives visible explanation");refreshed=AppWidgetManager.instance.updated.get(7);check(decode(delivered(refreshed,2)).optLong("expectedUpdatedAt")==20,"rejection refreshes visible actionrevision");new WidgetActionReceiverV196().onReceive(c,delivered(refreshed,2));check(level().equals("MAX"),"rebound freshclick accepted");
  reset();android.os.Build.VERSION.SDK_INT=30;before=render();Intent service=before.services.get(id("widget_items_v164"));check(service!=null&&service.getData().toString().contains("/v197/"),"API26to30 uses newadapter identity");WidgetRowsV164.Rows factory=new WidgetRowsV164.Rows(c,service);check(factory.getCount()==1,"initial factory count refreshes before onDataSetChanged");RemoteViews row=factory.getViewAt(0);Intent cached=before.templates.get(id("widget_items_v164")).deliver(row.fills.get(id("w194_level_2")));check(decode(cached).optLong("expectedUpdatedAt")==10,"initial service row revision");factory.onDataSetChanged();storage.put("widget_snapshot",raw(20).toString());check(factory.items.get(0).contains("\"updatedAt\":10"),"reproduced previous cachedfactory revision after app snapshotchange");RemoteViews current=factory.getViewAt(0);check(decode(current.fills.get(id("w194_level_2"))).optLong("expectedUpdatedAt")==20,"factoryrefreshes before delayed datasetnotification");RemoteViews changed=render();check(!changed.services.get(id("widget_items_v164")).getData().toString().equals(service.getData().toString()),"contentchange forces newserviceidentity");
  reset();RemoteViews.failInline=true;before=render();check(before.services.containsKey(id("widget_items_v164")),"collectionconstructor failure fallsbacktoservice");check(before.templates.get(id("widget_items_v164")).type.equals("broadcast"),"fallback retains routinetemplate");RemoteViews.failInline=false;check(WidgetNativeV164.inlineCollection(31,"RoutineAll",40)&&!WidgetNativeV164.inlineCollection(31,"RoutineAll",41),"inline cap explicit");check(!WidgetNativeV164.inlineCollection(30,"RoutineAll",1),"API30 service supported");List<String> many=new ArrayList<String>();for(int i=0;i<41;i++)many.add(WidgetNativeV164.rows(c,7,"RoutineAll",WidgetNativeV164.snapshot(c)).get(0));RemoteViews large=new RemoteViews(c.getPackageName(),1);WidgetNativeV164.collection(c,large,7,"RoutineAll",many);check(large.services.size()==1&&large.collections.isEmpty(),"overcap realbranch service");
  reset();ArrayList<android.util.SizeF> sizes=new ArrayList<android.util.SizeF>();sizes.add(new android.util.SizeF(220,250));sizes.add(new android.util.SizeF(360,360));AppWidgetManager.instance.options.putParcelableArrayList("appWidgetSizes",sizes);RemoteViews variants=WidgetSizeV169.render(c,7,"RoutineAll");check(variants.variants.size()==2,"exactsize variants rendered");for(Object v:variants.variants.values()){RemoteViews one=(RemoteViews)v;check(first(one).fills.containsKey(id("w194_level_2")),"eachvariant hasMAX fillin");check(one.templates.get(id("widget_items_v164")).type.equals("broadcast"),"eachvariant directreceiver");}
  reset();before=render();max=delivered(before,2);JSONObject other=raw(10).put("uid","other");other.getJSONObject("v165").put("uid","other");storage.put("widget_snapshot",other.toString());new WidgetActionReceiverV196().onReceive(c,max);check(WidgetPrivateV196.read(c,UID).length()==0,"oldowner click noqueue");
  reset();PendingIntent note=WidgetPrivateV196.noteCollection(c,9,"CalendarSplit@todos",UID);check(note.type.equals("activity")&&note.base.component.endsWith("WidgetNoteActivityV196"),"TODOtemplate directly nativeform noMainActivity");Intent add=note.deliver(WidgetNoteActivityV196.addFill(UID,"todo",TODAY));check(!WidgetActionReceiverV196.consume(c,add),"addfill doesnot consume mutation branch");check(add.getStringExtra("date").equals(TODAY),"date survivesbase withoutdate");check(add.getStringExtra("uid").equals(add.getStringExtra("boundUid")),"addowner matchesbound template");JSONObject data=WidgetNativeV164.snapshot(c),todo=WidgetDesignV165.model(data).getJSONArray("todos").getJSONObject(0);Intent done=note.deliver(WidgetDesignV165.action(data,9,"CalendarSplit",todo,"todo","true"));check(WidgetActionReceiverV196.consume(c,done),"checkbox nativeActivity consumes mutation before form");check(WidgetDesignV165.model(WidgetNativeV164.snapshot(c)).getJSONArray("incompleteTodos").length()==0,"checkbox immediate todo completion");check(WidgetPrivateV196.noteCollection(c,9,"CalendarSplit@notes",UID).type.equals("activity"),"MEMO collectiondirectform");
  reset();List<String> todoRows=WidgetNativeV164.rows(c,9,"CalendarSplit@todos",WidgetNativeV164.snapshot(c));RemoteViews pane=new RemoteViews(c.getPackageName(),1);WidgetNativeV164.collection(c,pane,9,"CalendarSplit@todos",todoRows,id("w165_secondary_list"));PendingIntent paneTemplate=pane.templates.get(id("w165_secondary_list"));RemoteViews todoView=pane.collections.get(id("w165_secondary_list")).rows.get(0);check(paneTemplate.type.equals("activity"),"actual Native.collection TODO routes directActivity");check(!paneTemplate.deliver(todoView.fills.get(id("w184_todo_title"))).hasExtra("action"),"actual TODO title opens add");check(decode(paneTemplate.deliver(todoView.fills.get(id("w184_check_hit")))).optString("op").equals("todo"),"actual TODO checkbox retainscompletion");new WidgetActionReceiverV196().onReceive(c,paneTemplate.deliver(todoView.fills.get(id("w184_check_hit"))));check(WidgetDesignV165.model(WidgetNativeV164.snapshot(c)).getJSONArray("incompleteTodos").length()==0,"actual calendar checkbox productionrow dispatch succeeds");JSONObject withMemo=raw(10);withMemo.getJSONObject("v165").getJSONArray("notes").put(new JSONObject().put("id","m1").put("title","메모").put("source","memos"));storage.put("widget_snapshot",withMemo.toString());List<String> noteRows=WidgetNativeV164.rows(c,9,"CalendarSplit@notes",WidgetNativeV164.snapshot(c));RemoteViews memoPane=new RemoteViews(c.getPackageName(),1);WidgetNativeV164.collection(c,memoPane,9,"CalendarSplit@notes",noteRows,id("w194_notes_list"));check(memoPane.templates.get(id("w194_notes_list")).type.equals("activity"),"actual Native.collection MEMO routes directActivity");RemoteViews emptyMemo=memoPane.collections.get(id("w194_notes_list")).rows.get(0);check(!memoPane.templates.get(id("w194_notes_list")).deliver(emptyMemo.fills.get(id("w194_note_title"))).hasExtra("action"),"actual MEMO row opens native add");
  for(String method:new String[]{"onCreate","onDataSetChanged","onDestroy","getCount","getViewAt","getItemId"}){Method m=method.equals("getViewAt")||method.equals("getItemId")?WidgetRowsV164.Rows.class.getDeclaredMethod(method,int.class):WidgetRowsV164.Rows.class.getDeclaredMethod(method);check(Modifier.isSynchronized(m.getModifiers()),"shared factory callbacks serialize "+method);}
  System.out.println("PASS "+checks+" production render/Intent/receiver/factory contracts (recording Android API boundary; no device runtime)");
 }
}